BDE 3.0: bdldfp_decimalplatform.h Reference
Quick Links:
bal | bbl | bdl | bsl | btl
bdldfp_decimalplatform.h File Reference
Provide decimal floating-point platform information macros.
Defines
#define BDLDFP_DECIMALPLATFORM_SOFTWARE 1
#define BDLDFP_DECIMALPLATFORM_SNPRINTF_BUFFER_SIZE 256
#define BDLDFP_DECIMALPLATFORM_INTELDFP 1
#define BDLDFP_DECIMALPLATFORM_BININT 1
#define BDLDFP_DECIMALPLATFORM_COMPILER_ERROR BSLMF_ASSERT(false)
Functions
BSLMF_ASSERT (false)
Detailed Description
Define Documentation
#define BDLDFP_DECIMALPLATFORM_SOFTWARE 1
#define BDLDFP_DECIMALPLATFORM_SNPRINTF_BUFFER_SIZE 256
#define BDLDFP_DECIMALPLATFORM_INTELDFP 1
#define BDLDFP_DECIMALPLATFORM_BININT 1
#define BDLDFP_DECIMALPLATFORM_COMPILER_ERROR BSLMF_ASSERT(false)
Function Documentation
BSLMF_ASSERT (false)
Referenced by bslalg::ScalarPrimitives_Imp::construct(), btlso::InetStreamSocket< ADDRESS >::shutdown(), and btlso::SocketImpUtil_Address< class IPv4Address >::SocketImpUtil_Address().