BDE 3.0: Class btlso::IPv4Address
Quick Links:
bal | bbl | bdl | bsl | btl
btlso::IPv4Address Class Reference
#include <btlso_ipv4address.h>
Public Types
enum { k_ANY_ADDRESS = 0, k_ANY_PORT = 0 }
Public Member Functions
IPv4Address ()
IPv4Address (const char *address, int portNumber)
IPv4Address (int address, int portNumber)
IPv4Address (const IPv4Address &original)
~IPv4Address ()
IPv4Address & operator= (const IPv4Address &rhs)
int setIpAddress (const char *address)
void setIpAddress (int address)
void setPortNumber (int portNumber)
template<class STREAM >
STREAM & bdexStreamIn (STREAM &stream, int version)
int loadIpAddress (char *result) const
int formatIpAddress (char *result) const
int ipAddress () const
int portNumber () const
bsl::ostream & streamOut (bsl::ostream &stream) const
template<class STREAM >
STREAM & bdexStreamOut (STREAM &stream, int version) const
Static Public Member Functions
static bool isValidAddress (const char *address)
static int isLocalBroadcastAddress (const char *address)
static int maxSupportedBdexVersion (int versionSelector)
Detailed Description
Each instance of this class represents an IPv4 address. A static method isValidAddress is provided to verify that an IP address in dotted decimal notation is valid before it is used to create or modify an IPv4 address object. More generally, this class supports a complete set of value semantic operations, including copy construction, assignment, equality comparison, ostream printing, and BDEX serialization. (A precise operational definition of when two instances have the same value can be found in the description of operator== for the class.) This class is exception neutral with no guarantee of rollback: if an exception is thrown during the invocation of a method on a pre-existing instance, the object is left in a valid state, but its value is undefined. In no event is memory leaked. Finally, aliasing (e.g., using all or part of an object as both source and destination) is supported in all cases.
Member Enumeration Documentation
anonymous enum
Enumerator:
k_ANY_ADDRESS
Indicate that it is up to the service provider to assign an appropriate IP. Note that a local platform usually defines INADDR_ANY to have value 0 for the same implication.
k_ANY_PORT
Indicate that it is up to the service provider to assign an appropriate port.
Constructor & Destructor Documentation
btlso::IPv4Address::IPv4Address ()
Create a IPv4Address object having an IP of k_ANY_ADDRESS value and a port number of k_ANY_PORT value.
btlso::IPv4Address::IPv4Address (const char * address, int portNumber)
Create a IPv4Address object having the value given by the specified IP address and portNumber. The value is undefined unless portNumber is in the range [0, 65535] and the IP address is valid. See Valid String Representations of IPv4 Addresses under DESCRIPTION for details of valid string representations of IP addresses.
btlso::IPv4Address::IPv4Address (int address, int portNumber)
Create a IPv4Address object having the value given by the specified IP address and portNumber. The value is undefined unless address specifies a 32-bit IP address in network byte order as an int on the local platform and portNumber is in the range [0, 65535].
btlso::IPv4Address::IPv4Address (const IPv4Address & original)
Create a IPv4Address object having the value of the specified original object.
btlso::IPv4Address::~IPv4Address ()
Destroy this object.
Member Function Documentation
static bool btlso::IPv4Address::isValidAddress (const char * address) [static]
Return true if the specified IP address is valid, and false otherwise. See Valid String Representations of IPv4 Addresses under DESCRIPTION for details of valid string representations of IP addresses.
static int btlso::IPv4Address::isLocalBroadcastAddress (const char * address) [static]
Return 0 if the IP address is invalid or does not represent 255.255.255.255, and non-zero otherwise. See Valid String Representations of IPv4 Addresses under DESCRIPTION for details of valid string representations of IP addresses.
Windows XP currently does not support the inet_aton function as specified by the contract above (inet_pton does not handle hexadecimal or octal numerals.) In some cases 255.255.255.255, while being a valid address, is not parsed correctly by inet_addr because -1 is used as an error code. This function checks if the specified address is an IP representation of a address with an integer value of -1. This function is intended to detect all cases in which a valid address of 255.255.255.255 is wrongfully detected as an invalid address by inet_addr.
IPv4Address& btlso::IPv4Address::operator= (const IPv4Address & rhs)
Assign to this object the value of the specified rhs object and return a reference to this modifiable object.
int btlso::IPv4Address::setIpAddress (const char * address)
Set this object to have the specified IP address. Return 0 if the IP address is valid, and non-zero otherwise. See Valid String Representations of IPv4 Addresses under DESCRIPTION for details of valid string representations of IP addresses.
Referenced by btlso::SocketImpUtil_Address< class IPv4Address >::fromSocketAddress().
void btlso::IPv4Address::setIpAddress (int address)
Set this object to have the specified IP address. The behavior is undefined unless address specifies a 32-bit IP address in network byte order as an int on the local platform.
void btlso::IPv4Address::setPortNumber (int portNumber)
Set this object to have the specified portNumber. The behavior is undefined unless portNumber is in the range [0, 65535].
Referenced by btlso::SocketImpUtil_Address< class IPv4Address >::fromSocketAddress().
template<class STREAM > STREAM& btlso::IPv4Address::bdexStreamIn (STREAM & stream, int version)
Assign to this object the value read from the specified input stream using the specified version format, and return a reference to stream. If stream is initially invalid, this operation has no effect. If version is not supported, this object is unaltered and stream is invalidated but otherwise unmodified. If version is supported but stream becomes invalid during this operation, this object has an undefined, but valid, state. Note that no version is read from stream. See the bslx package-level documentation for more information on BDEX streaming of value-semantic types and containers.
int btlso::IPv4Address::loadIpAddress (char * result) const
Load into the specified result this object's logical IP address represented in the dotted decimal notation as a null-terminated string and return number of bytes used to store the result (including the null character). The behavior is undefined unless result refers to a valid array of at least 16 characters.
int btlso::IPv4Address::formatIpAddress (char * result) const
Load into the specified result this object's logical IP address and port represented in the dotted decimal notation followed by a colon and the port as a null-terminated string and return the number of bytes used to store the result (including the null character). The behavior is undefined unless result refers to a valid array of at least 22 characters.
int btlso::IPv4Address::ipAddress () const
Return the 32-bit IP address of this object in network byte order as an int on the local platform.
Referenced by btlso::SocketImpUtil_Address< class IPv4Address >::SocketImpUtil_Address().
int btlso::IPv4Address::portNumber () const
Return the port number of this object.
Referenced by btlso::SocketImpUtil_Address< class IPv4Address >::SocketImpUtil_Address().
static int btlso::IPv4Address::maxSupportedBdexVersion (int versionSelector) [static]
Return the maximum valid BDEX format version, as indicated by the specified versionSelector, to be passed to the bdexStreamOut method. Note that the versionSelector is expected to be formatted as yyyymmdd, a date representation. See the bslx package-level documentation for more information on BDEX streaming of value-semantic types and containers.
bsl::ostream& btlso::IPv4Address::streamOut (bsl::ostream & stream) const
Write the specified IPv4 address value to the specified output stream in the format of address:portNumber, e.g., "127.0.0.1:5".
template<class STREAM > STREAM& btlso::IPv4Address::bdexStreamOut (STREAM & stream, int version) const
Assign to this object the value read from the specified input stream using the specified version format, and return a reference to stream. If stream is initially invalid, this operation has no effect. If version is not supported, this object is unaltered and stream is invalidated but otherwise unmodified. If version is supported but stream becomes invalid during this operation, this object has an undefined, but valid, state. Note that no version is read from stream. See the bslx package-level documentation for more information on BDEX streaming of value-semantic types and containers.
The documentation for this class was generated from the following file:
btlso_ipv4address.h