BDE 3.0: Class bdlb::VariantImp
Quick Links:
bal | bbl | bdl | bsl | btl
bdlb::VariantImp< TYPES > Class Template Reference
#include <bdlb_variant.h>
Public Member Functions
BSLMF_NESTED_TRAIT_DECLARATION_IF (VariantImp, bslma::UsesBslmaAllocator, Traits::k_VARIANT_USES_BSLMA_ALLOCATOR)
BSLMF_NESTED_TRAIT_DECLARATION_IF (VariantImp, bsl::is_trivially_copyable, Traits::k_VARIANT_IS_BITWISE_COPYABLE)
BSLMF_NESTED_TRAIT_DECLARATION_IF (VariantImp, bslmf::IsBitwiseMoveable, Traits::k_VARIANT_IS_BITWISE_MOVEABLE)
BSLMF_NESTED_TRAIT_DECLARATION (VariantImp, HasPrintMethod)
VariantImp ()
template<class TYPE_OR_ALLOCATOR >
VariantImp (const TYPE_OR_ALLOCATOR &typeOrAlloc)
template<class TYPE >
VariantImp (const TYPE &value, bslma::Allocator *basicAllocator)
VariantImp (const VariantImp &original, bslma::Allocator *basicAllocator=0)
~VariantImp ()
template<class TYPE >
VariantImp & operator= (const TYPE &value)
VariantImp & operator= (const VariantImp &rhs)
template<class VISITOR >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==1,
typename VISITOR::ResultType >
::type apply (VISITOR &visitor)
template<class VISITOR >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==1,
typename VISITOR::ResultType >
::type apply (const VISITOR &visitor)
template<class VISITOR , class TYPE >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==1,
typename VISITOR::ResultType >
::type apply (VISITOR &visitor, const TYPE &defaultValue)
template<class VISITOR , class TYPE >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==1,
typename VISITOR::ResultType >
::type apply (const VISITOR &visitor, const TYPE &defaultValue)
template<class VISITOR >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==0, void >
::type apply (VISITOR &visitor)
template<class VISITOR >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==0, void >
::type apply (const VISITOR &visitor)
template<class VISITOR , class TYPE >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==0, void >
::type apply (VISITOR &visitor, const TYPE &defaultValue)
template<class VISITOR , class TYPE >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==0, void >
::type apply (const VISITOR &visitor, const TYPE &defaultValue)
template<class RET_TYPE , class VISITOR >
RET_TYPE apply (VISITOR &visitor)
template<class RET_TYPE , class VISITOR >
RET_TYPE apply (const VISITOR &visitor)
template<class RET_TYPE , class VISITOR , class TYPE >
RET_TYPE apply (VISITOR &visitor, const TYPE &defaultValue)
template<class RET_TYPE , class VISITOR , class TYPE >
RET_TYPE apply (const VISITOR &visitor, const TYPE &defaultValue)
template<class VISITOR >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==1,
typename VISITOR::ResultType >
::type applyRaw (VISITOR &visitor)
template<class VISITOR >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==1,
typename VISITOR::ResultType >
::type applyRaw (const VISITOR &visitor)
template<class VISITOR >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==0, void >
::type applyRaw (VISITOR &visitor)
template<class VISITOR >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==0, void >
::type applyRaw (const VISITOR &visitor)
template<class RET_TYPE , class VISITOR >
RET_TYPE applyRaw (VISITOR &visitor)
template<class RET_TYPE , class VISITOR >
RET_TYPE applyRaw (const VISITOR &visitor)
template<class TYPE >
VariantImp & assign (const TYPE &value)
template<class TYPE , class SOURCE_TYPE >
VariantImp & assignTo (const SOURCE_TYPE &value)
template<class TYPE >
void createInPlace ()
template<class TYPE , class A1 >
void createInPlace (const A1 &a1)
template<class TYPE , class A1 , class A2 >
void createInPlace (const A1 &a1, const A2 &a2)
template<class TYPE , class A1 , class A2 , class A3 >
void createInPlace (const A1 &a1, const A2 &a2, const A3 &a3)
template<class TYPE , class A1 , class A2 , class A3 , class A4 >
void createInPlace (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4)
template<class TYPE , class A1 , class A2 , class A3 , class A4 , class A5 >
void createInPlace (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5)
template<class TYPE , class A1 , class A2 , class A3 , class A4 , class A5 , class A6 >
void createInPlace (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6)
template<class TYPE , class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 >
void createInPlace (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7)
template<class TYPE , class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 >
void createInPlace (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8)
template<class TYPE , class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 >
void createInPlace (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8, const A9 &a9)
template<class TYPE , class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 , class A10 >
void createInPlace (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8, const A9 &a9, const A10 &a10)
template<class TYPE , class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 , class A10 , class A11 >
void createInPlace (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8, const A9 &a9, const A10 &a10, const A11 &a11)
template<class TYPE , class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 , class A10 , class A11 , class A12 >
void createInPlace (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8, const A9 &a9, const A10 &a10, const A11 &a11, const A12 &a12)
template<class TYPE , class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 , class A10 , class A11 , class A12 , class A13 >
void createInPlace (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8, const A9 &a9, const A10 &a10, const A11 &a11, const A12 &a12, const A13 &a13)
template<class TYPE , class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 , class A10 , class A11 , class A12 , class A13 , class A14 >
void createInPlace (const A1 &a1, const A2 &a2, const A3 &a3, const A4 &a4, const A5 &a5, const A6 &a6, const A7 &a7, const A8 &a8, const A9 &a9, const A10 &a10, const A11 &a11, const A12 &a12, const A13 &a13, const A14 &a14)
void reset ()
void swap (VariantImp &other)
template<class TYPE >
TYPE & the ()
template<class VISITOR >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==1,
typename VISITOR::ResultType >
::type apply (VISITOR &visitor) const
template<class VISITOR >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==1,
typename VISITOR::ResultType >
::type apply (const VISITOR &visitor) const
template<class VISITOR , class TYPE >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==1,
typename VISITOR::ResultType >
::type apply (VISITOR &visitor, const TYPE &defaultValue) const
template<class VISITOR , class TYPE >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==1,
typename VISITOR::ResultType >
::type apply (const VISITOR &visitor, const TYPE &defaultValue) const
template<class VISITOR >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==0, void >
::type apply (VISITOR &visitor) const
template<class VISITOR >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==0, void >
::type apply (const VISITOR &visitor) const
template<class VISITOR , class TYPE >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==0, void >
::type apply (VISITOR &visitor, const TYPE &defaultValue) const
template<class VISITOR , class TYPE >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==0, void >
::type apply (const VISITOR &visitor, const TYPE &defaultValue) const
template<class RET_TYPE , class VISITOR >
RET_TYPE apply (VISITOR &visitor) const
template<class RET_TYPE , class VISITOR >
RET_TYPE apply (const VISITOR &visitor) const
template<class RET_TYPE , class VISITOR , class TYPE >
RET_TYPE apply (VISITOR &visitor, const TYPE &defaultValue) const
template<class RET_TYPE , class VISITOR , class TYPE >
RET_TYPE apply (const VISITOR &visitor, const TYPE &defaultValue) const
template<class VISITOR >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==1,
typename VISITOR::ResultType >
::type applyRaw (VISITOR &visitor) const
template<class VISITOR >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==1,
typename VISITOR::ResultType >
::type applyRaw (const VISITOR &visitor) const
template<class VISITOR >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==0, void >
::type applyRaw (VISITOR &visitor) const
template<class VISITOR >
bsl::enable_if
< Variant_ReturnValueHelper
< VISITOR >::value==0, void >
::type applyRaw (const VISITOR &visitor) const
template<class RET_TYPE , class VISITOR >
RET_TYPE applyRaw (VISITOR &visitor) const
template<class RET_TYPE , class VISITOR >
RET_TYPE applyRaw (const VISITOR &visitor) const
template<class TYPE >
bool is () const
bool isUnset () const
bsl::ostream & print (bsl::ostream &stream, int level=0, int spacesPerLevel=4) const
template<class TYPE >
const TYPE & the () const
int typeIndex () const
Detailed Description
template<class TYPES>
class bdlb::VariantImp< TYPES >
This class provides the implementation of Variant (except for the creators) given a list of template parameter TYPES.
More generally, if each of the types in the list of TYPES is value-semantic, then this class also supports a complete set of value semantic operations, including copy construction, assignment, equality comparison, and ostream printing. A precise operational definition of when two instances have the same value can be found in the description of operator== for the class. This class is exception neutral with no guarantee of rollback: if an exception is thrown during the invocation of a method on a pre-existing instance, the object is left in a valid state, but its value is undefined. In no event is memory leaked. Finally, aliasing (e.g., using all or part of an object as both source and destination) is supported in all cases.
If any of the types in the list of TYPES does not support operator==, or any of the value-semantic operations mentioned above, then this variant also does not support that operation and attempts to invoke it will trigger a compilation diagnostic.
Constructor & Destructor Documentation
template<class TYPES> bdlb::VariantImp< TYPES >::VariantImp ()
Create a variant object in the unset state that uses the currently installed default allocator to supply memory.
template<class TYPES> template<class TYPE_OR_ALLOCATOR > bdlb::VariantImp< TYPES >::VariantImp (const TYPE_OR_ALLOCATOR & typeOrAlloc) [explicit]
Create a variant object with the specified typeOrAlloc that can be either a value of a type that the variant can hold or an allocator to supply memory. If typeOrAlloc is not a bslma::Allocator *, then the variant will hold the value and type of typeOrAlloc, and use the currently installed default allocator to supply memory. Otherwise, the variant will be unset and use typeOrAlloc to supply memory. Note that this parameterized constructor is defined instead of two constructors (one taking a bslma::Allocator * and the other not) because template parameter arguments are always a better match than derived-to-base conversion (a concrete allocator pointer converted to bslma::Allocator *).
template<class TYPES> template<class TYPE > bdlb::VariantImp< TYPES >::VariantImp (const TYPE & value, bslma::Allocator * basicAllocator)
Create a variant object having the specified value and that uses the specified basicAllocator to supply memory. If basicAllocator is 0, the currently installed default allocator is used.
template<class TYPES> bdlb::VariantImp< TYPES >::VariantImp (const VariantImp< TYPES > & original, bslma::Allocator * basicAllocator = 0)
Create a variant object having the type and value of the specified original variant. Optionally specify a basicAllocator used to supply memory. If basicAllocator is 0, the currently installed / default allocator is used.
template<class TYPES> bdlb::VariantImp< TYPES >::~VariantImp ()
Destroy this variant object, invoking the destructor of the type of object contained (if any) on the value of that type.
Member Function Documentation
template<class TYPES> bdlb::VariantImp< TYPES >::BSLMF_NESTED_TRAIT_DECLARATION_IF (VariantImp< TYPES > , bslma::UsesBslmaAllocator , Traits::k_VARIANT_USES_BSLMA_ALLOCATOR)
template<class TYPES> bdlb::VariantImp< TYPES >::BSLMF_NESTED_TRAIT_DECLARATION_IF (VariantImp< TYPES > , bsl::is_trivially_copyable , Traits::k_VARIANT_IS_BITWISE_COPYABLE)
template<class TYPES> bdlb::VariantImp< TYPES >::BSLMF_NESTED_TRAIT_DECLARATION_IF (VariantImp< TYPES > , bslmf::IsBitwiseMoveable , Traits::k_VARIANT_IS_BITWISE_MOVEABLE)
template<class TYPES> bdlb::VariantImp< TYPES >::BSLMF_NESTED_TRAIT_DECLARATION (VariantImp< TYPES > , HasPrintMethod)
template<class TYPES> template<class TYPE > VariantImp& bdlb::VariantImp< TYPES >::operator= (const TYPE & value)
Assign to this object the specified value of template parameter TYPE, and return a reference providing modifiable access to this object. The value previously held by this variant (if any) will be destroyed if the value's type is different from the template parameter TYPE.
Reimplemented in bdlb::Variant< A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20 >, bdlb::Variant2< A1, A2 >, bdlb::Variant3< A1, A2, A3 >, bdlb::Variant4< A1, A2, A3, A4 >, bdlb::Variant5< A1, A2, A3, A4, A5 >, bdlb::Variant6< A1, A2, A3, A4, A5, A6 >, bdlb::Variant7< A1, A2, A3, A4, A5, A6, A7 >, bdlb::Variant8< A1, A2, A3, A4, A5, A6, A7, A8 >, bdlb::Variant9< A1, A2, A3, A4, A5, A6, A7, A8, A9 >, bdlb::Variant10< A1, A2, A3, A4, A5, A6, A7, A8, A9, A10 >, bdlb::Variant11< A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11 >, bdlb::Variant12< A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12 >, bdlb::Variant13< A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13 >, bdlb::Variant14< A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14 >, bdlb::Variant15< A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15 >, bdlb::Variant16< A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16 >, bdlb::Variant17< A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17 >, bdlb::Variant18< A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18 >, bdlb::Variant19< A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19 >, bdlb::Variant< int, bsls::Types::Int64, bsl::string >, and bdlb::Variant< bsl::int64_t, double, bsl::string, bdlt::DatetimeTz >.
Referenced by bdlb::Variant15< A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15 >::operator=(), bdlb::Variant14< A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14 >::operator=(), bdlb::Variant13< A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13 >::operator=(), bdlb::Variant12< A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12 >::operator=(), bdlb::Variant11< A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11 >::operator=(), bdlb::Variant10< A1, A2, A3, A4, A5, A6, A7, A8, A9, A10 >::operator=(), bdlb::Variant9< A1, A2, A3, A4, A5, A6, A7, A8, A9 >::operator=(), bdlb::Variant8< A1, A2, A3, A4, A5, A6, A7, A8 >::operator=(), bdlb::Variant7< A1, A2, A3, A4, A5, A6, A7 >::operator=(), bdlb::Variant6< A1, A2, A3, A4, A5, A6 >::operator=(), bdlb::Variant5< A1, A2, A3, A4, A5 >::operator=(), bdlb::Variant4< A1, A2, A3, A4 >::operator=(), bdlb::Variant3< A1, A2, A3 >::operator=(), and bdlb::Variant2< A1, A2 >::operator=().
template<class TYPES> VariantImp& bdlb::VariantImp< TYPES >::operator= (const VariantImp< TYPES > & rhs)
Assign to this object the type and value currently held by the specified rhs object, and return a reference providing modifiable access to this object. The value previously held by this variant (if any) will be destroyed if the value's type is different from the type held by the rhs object.
template<class TYPES> template<class VISITOR > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 1, typename VISITOR::ResultType>::type bdlb::VariantImp< TYPES >::apply (VISITOR & visitor) [inline]
< Apply the specified visitor to this modifiable variant by passing the value this variant currently holds to the visitor object's operator(), and return the value returned by the visitor. If the variant is unset, a default constructed bslmf::Nil is passed to the visitor. Note that this method is selected only if the template parameter type VISITOR defines a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
template<class TYPES> template<class VISITOR > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 1, typename VISITOR::ResultType>::type bdlb::VariantImp< TYPES >::apply (const VISITOR & visitor) [inline]
< Apply the specified visitor to this modifiable variant by passing the value this variant currently holds to the visitor object's operator(), and return the value returned by the visitor. If If the variant is unset, a default constructed bslmf::Nil is passed to the visitor. Note that this method is selected only if the template parameter type VISITOR defines a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
template<class TYPES> template<class VISITOR , class TYPE > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 1, typename VISITOR::ResultType>::type bdlb::VariantImp< TYPES >::apply (VISITOR & visitor, const TYPE & defaultValue) [inline]
< Apply the specified visitor to this modifiable variant by passing the value this variant currently holds to the visitor object's operator(), and return the value returned by the visitor. If the variant is unset, the specified defaultValue is passed to the visitor. Note that this method is selected only if the template parameter type VISITOR defines a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
template<class TYPES> template<class VISITOR , class TYPE > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 1, typename VISITOR::ResultType>::type bdlb::VariantImp< TYPES >::apply (const VISITOR & visitor, const TYPE & defaultValue) [inline]
< Apply the specified visitor to this modifiable variant by passing the value this variant currently holds to the visitor object's operator(), and return the value returned by the visitor. If the variant is unset, the specified defaultValue is passed to the visitor. Note that this method is selected only if the template parameter type VISITOR defines a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
template<class TYPES> template<class VISITOR > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 0, void>::type bdlb::VariantImp< TYPES >::apply (VISITOR & visitor) [inline]
< Apply the specified visitor to this modifiable variant by passing the value this variant currently holds to the visitor object's operator(). This method does not return a value. If the variant is unset, a default constructed bslmf::Nil is passed to the visitor. Note that this method is selected only if the template parameter type VISITOR does not define a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
RETURN
template<class TYPES> template<class VISITOR > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 0, void>::type bdlb::VariantImp< TYPES >::apply (const VISITOR & visitor) [inline]
< Apply the specified visitor to this modifiable variant by passing the value this variant currently holds to the visitor object's operator(). This method does not return a value. If the variant is unset, a default constructed bslmf::Nil is passed to the visitor. Note that this method is selected only if the template parameter type VISITOR does not define a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
RETURN
template<class TYPES> template<class VISITOR , class TYPE > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 0, void>::type bdlb::VariantImp< TYPES >::apply (VISITOR & visitor, const TYPE & defaultValue) [inline]
< Apply the specified visitor to this modifiable variant by passing the value this variant currently holds to the visitor object's operator(). This method does not return a value. If the variant is unset, the specified defaultValue is passed to the visitor. Note that this method is selected only if the template parameter type VISITOR does not define a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
RETURN
template<class TYPES> template<class VISITOR , class TYPE > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 0, void>::type bdlb::VariantImp< TYPES >::apply (const VISITOR & visitor, const TYPE & defaultValue) [inline]
< Apply the specified visitor to this modifiable variant by passing the value this variant currently holds to the visitor object's operator(). This method does not return a value. If the variant is unset, the specified defaultValue is passed to the visitor. Note that this method is selected only if the template parameter type VISITOR does not define a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
RETURN
template<class TYPES> template<class RET_TYPE , class VISITOR > RET_TYPE bdlb::VariantImp< TYPES >::apply (VISITOR & visitor)
template<class TYPES> template<class RET_TYPE , class VISITOR > RET_TYPE bdlb::VariantImp< TYPES >::apply (const VISITOR & visitor)
Apply the specified visitor to this modifiable variant by passing the value this variant currently holds to the visitor object's operator(), and return the value (of template parameter RET_TYPE) returned by the visitor. If the variant is unset, a default constructed bslmf::Nil is passed to the visitor.
template<class TYPES> template<class RET_TYPE , class VISITOR , class TYPE > RET_TYPE bdlb::VariantImp< TYPES >::apply (VISITOR & visitor, const TYPE & defaultValue)
template<class TYPES> template<class RET_TYPE , class VISITOR , class TYPE > RET_TYPE bdlb::VariantImp< TYPES >::apply (const VISITOR & visitor, const TYPE & defaultValue)
Apply the specified visitor to this modifiable variant by passing the value this variant currently holds to the visitor object's operator(), and return the value (of template parameter RET_TYPE) returned by the visitor. If the variant is unset, the specified defaultValue is passed to the visitor.
template<class TYPES> template<class VISITOR > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 1, typename VISITOR::ResultType>::type bdlb::VariantImp< TYPES >::applyRaw (VISITOR & visitor) [inline]
< Apply the specified visitor to this modifiable variant by passing the value this variant currently holds to visitor object's operator(), and return the value returned by the visitor. The behavior is undefined if this variant is unset. Note that this method is selected only if the template parameter type VISITOR defines a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
template<class TYPES> template<class VISITOR > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 1, typename VISITOR::ResultType>::type bdlb::VariantImp< TYPES >::applyRaw (const VISITOR & visitor) [inline]
< Apply the specified visitor to this modifiable variant by passing the value this variant currently holds to the visitor object's operator(), and return the value returned by the visitor. The behavior is undefined if this variant is unset. Note that this method is selected only if the template parameter type VISITOR defines a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
template<class TYPES> template<class VISITOR > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 0, void>::type bdlb::VariantImp< TYPES >::applyRaw (VISITOR & visitor) [inline]
< Apply the specified visitor to this modifiable variant by passing the value this variant currently holds to the visitor object's operator(). This method does not return a value. The behavior is undefined if this variant is unset. Note that this method is selected only if the template parameter type VISITOR does not define a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
template<class TYPES> template<class VISITOR > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 0, void>::type bdlb::VariantImp< TYPES >::applyRaw (const VISITOR & visitor) [inline]
< Apply the specified visitor to this modifiable variant by passing the value this variant currently holds to the visitor object's operator(). This method does not return a value. The behavior is undefined if this variant is unset. Note that this method is selected only if the template parameter type VISITOR does not define a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
template<class TYPES> template<class RET_TYPE , class VISITOR > RET_TYPE bdlb::VariantImp< TYPES >::applyRaw (VISITOR & visitor)
template<class TYPES> template<class RET_TYPE , class VISITOR > RET_TYPE bdlb::VariantImp< TYPES >::applyRaw (const VISITOR & visitor)
Apply the specified visitor to this modifiable variant by passing the value this variant currently holds to the visitor object's operator(), and return the value (of template parameter RET_TYPE) returned by the visitor. The behavior is undefined if this variant is unset.
template<class TYPES> template<class TYPE > VariantImp& bdlb::VariantImp< TYPES >::assign (const TYPE & value)
Assign to this object the specified value of template parameter TYPE, and return a reference providing modifiable access to this object. The value previously held by this variant (if any) will be destroyed if the value's type is different from TYPE.
template<class TYPES> template<class TYPE , class SOURCE_TYPE > VariantImp& bdlb::VariantImp< TYPES >::assignTo (const SOURCE_TYPE & value)
Assign to this object the specified value of template parameter SOURCE_TYPE, and return a reference providing modifiable access to this object. The value previously held by this variant (if any) will be destroyed if the value's type is different from the template parameter TYPE.
template<class TYPES> template<class TYPE > void bdlb::VariantImp< TYPES >::createInPlace ()
template<class TYPES> template<class TYPE , class A1 > void bdlb::VariantImp< TYPES >::createInPlace (const A1 & a1)
template<class TYPES> template<class TYPE , class A1 , class A2 > void bdlb::VariantImp< TYPES >::createInPlace (const A1 & a1, const A2 & a2)
template<class TYPES> template<class TYPE , class A1 , class A2 , class A3 > void bdlb::VariantImp< TYPES >::createInPlace (const A1 & a1, const A2 & a2, const A3 & a3)
template<class TYPES> template<class TYPE , class A1 , class A2 , class A3 , class A4 > void bdlb::VariantImp< TYPES >::createInPlace (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4)
template<class TYPES> template<class TYPE , class A1 , class A2 , class A3 , class A4 , class A5 > void bdlb::VariantImp< TYPES >::createInPlace (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5)
template<class TYPES> template<class TYPE , class A1 , class A2 , class A3 , class A4 , class A5 , class A6 > void bdlb::VariantImp< TYPES >::createInPlace (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6)
template<class TYPES> template<class TYPE , class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 > void bdlb::VariantImp< TYPES >::createInPlace (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7)
template<class TYPES> template<class TYPE , class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 > void bdlb::VariantImp< TYPES >::createInPlace (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8)
template<class TYPES> template<class TYPE , class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 > void bdlb::VariantImp< TYPES >::createInPlace (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8, const A9 & a9)
template<class TYPES> template<class TYPE , class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 , class A10 > void bdlb::VariantImp< TYPES >::createInPlace (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8, const A9 & a9, const A10 & a10)
template<class TYPES> template<class TYPE , class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 , class A10 , class A11 > void bdlb::VariantImp< TYPES >::createInPlace (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8, const A9 & a9, const A10 & a10, const A11 & a11)
template<class TYPES> template<class TYPE , class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 , class A10 , class A11 , class A12 > void bdlb::VariantImp< TYPES >::createInPlace (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8, const A9 & a9, const A10 & a10, const A11 & a11, const A12 & a12)
template<class TYPES> template<class TYPE , class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 , class A10 , class A11 , class A12 , class A13 > void bdlb::VariantImp< TYPES >::createInPlace (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8, const A9 & a9, const A10 & a10, const A11 & a11, const A12 & a12, const A13 & a13)
template<class TYPES> template<class TYPE , class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 , class A9 , class A10 , class A11 , class A12 , class A13 , class A14 > void bdlb::VariantImp< TYPES >::createInPlace (const A1 & a1, const A2 & a2, const A3 & a3, const A4 & a4, const A5 & a5, const A6 & a6, const A7 & a7, const A8 & a8, const A9 & a9, const A10 & a10, const A11 & a11, const A12 & a12, const A13 & a13, const A14 & a14)
Create an instance of the template parameter TYPE in this variant object with up to 14 parameters using the allocator currently held by this variant to supply memory. This method first destroys the current value held by the variant (even if TYPE is the same as the current type held). The behavior is undefined unless TYPE is one of the types that this variant holds. Note the order of the template arguments was chosen so that TYPE must always be specified.
template<class TYPES> void bdlb::VariantImp< TYPES >::reset ()
Destroy the current value held by this variant (if any), and reset this variant to the unset state.
template<class TYPES> void bdlb::VariantImp< TYPES >::swap (VariantImp< TYPES > & other)
Swap the value of this object with the value of the specified other object. This method provides the no-throw guarantee if the TYPE template parameter has a no-throw swap and the two variant objects being swapped have the same type; otherwise this method provides the basic guarantee.
template<class TYPES> template<class TYPE > TYPE& bdlb::VariantImp< TYPES >::the ()
Return a reference providing modifiable access to the value of the template parameter TYPE held by this variant object. The behavior is undefined unless is<TYPE>() returns true and TYPE is not void. Note that TYPE must be specified explicitly, e.g., myValue.the<int>().
template<class TYPES> template<class VISITOR > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 1, typename VISITOR::ResultType>::type bdlb::VariantImp< TYPES >::apply (VISITOR & visitor) const [inline]
< Apply the specified visitor to this variant by passing the value this variant currently holds to the visitor object's operator(), and return the value returned by the visitor. If the variant is unset, a default constructed bslmf::Nil is passed to the visitor. Note that this method is selected only if the template parameter type VISITOR defines a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
template<class TYPES> template<class VISITOR > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 1, typename VISITOR::ResultType>::type bdlb::VariantImp< TYPES >::apply (const VISITOR & visitor) const [inline]
< Apply the specified visitor to this variant by passing the value this variant currently holds to the visitor object's operator(), and return the value returned by the 'visitor. If the variant is unset, a default constructed bslmf::Nil is passed to the visitor. Note that this method is selected only if the template parameter type VISITOR defines a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
template<class TYPES> template<class VISITOR , class TYPE > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 1, typename VISITOR::ResultType>::type bdlb::VariantImp< TYPES >::apply (VISITOR & visitor, const TYPE & defaultValue) const [inline]
< Apply the specified visitor to this variant by passing the value this variant currently holds to the visitor object's operator(), and return the value returned by the visitor. If the variant is unset, the specified defaultValue is passed to the visitor. Note that this method is selected only if the template parameter type VISITOR defines a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
template<class TYPES> template<class VISITOR , class TYPE > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 1, typename VISITOR::ResultType>::type bdlb::VariantImp< TYPES >::apply (const VISITOR & visitor, const TYPE & defaultValue) const [inline]
< Apply the specified visitor to this variant by passing the value this variant currently holds to the visitor object's operator(), and return the value returned by the visitor. If the variant is unset, the specified defaultValue is passed to the visitor. Note that this method is selected only if the template parameter type VISITOR defines a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
template<class TYPES> template<class VISITOR > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 0, void>::type bdlb::VariantImp< TYPES >::apply (VISITOR & visitor) const [inline]
< Apply the specified visitor to this variant by passing the value this variant currently holds to the visitor object's operator(). This method does not return a value. If the variant is unset, a default constructed bslmf::Nil is passed to the visitor. Note that this method is selected only if the template parameter type VISITOR does not define a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
RETURN
template<class TYPES> template<class VISITOR > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 0, void>::type bdlb::VariantImp< TYPES >::apply (const VISITOR & visitor) const [inline]
< Apply the specified visitor to this variant by passing the value this variant currently holds to the visitor object's operator(). This method does not return a value. If the variant is unset, a default constructed bslmf::Nil is passed to the visitor. Note that this method is selected only if the template parameter type VISITOR does not define a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
RETURN
template<class TYPES> template<class VISITOR , class TYPE > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 0, void>::type bdlb::VariantImp< TYPES >::apply (VISITOR & visitor, const TYPE & defaultValue) const [inline]
< Apply the specified visitor to this variant by passing the value this variant currently holds to the visitor object's operator(). This method does not return a value. If the variant is unset, the specified defaultValue is passed to the visitor. Note that this method is selected only if the template parameter type VISITOR does not define a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
RETURN
template<class TYPES> template<class VISITOR , class TYPE > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 0, void>::type bdlb::VariantImp< TYPES >::apply (const VISITOR & visitor, const TYPE & defaultValue) const [inline]
< Apply the specified visitor to this variant by passing the value this variant currently holds to the visitor object's operator(). This method does not return a value. If the variant is unset, the specified defaultValue is passed to the visitor. Note that this method is selected only if the template parameter type VISITOR does not define a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
RETURN
template<class TYPES> template<class RET_TYPE , class VISITOR > RET_TYPE bdlb::VariantImp< TYPES >::apply (VISITOR & visitor) const
template<class TYPES> template<class RET_TYPE , class VISITOR > RET_TYPE bdlb::VariantImp< TYPES >::apply (const VISITOR & visitor) const
Apply the specified visitor to this variant by passing the value this variant currently holds to the visitor object's operator(), and return the value (of template parameter RET_TYPE) returned by the visitor. If the variant is unset, a default constructed bslmf::Nil is passed to the visitor.
template<class TYPES> template<class RET_TYPE , class VISITOR , class TYPE > RET_TYPE bdlb::VariantImp< TYPES >::apply (VISITOR & visitor, const TYPE & defaultValue) const
template<class TYPES> template<class RET_TYPE , class VISITOR , class TYPE > RET_TYPE bdlb::VariantImp< TYPES >::apply (const VISITOR & visitor, const TYPE & defaultValue) const
Apply the specified visitor to this variant by passing the value this variant currently holds to the visitor object's operator(), and return the value (of template parameter RET_TYPE) returned by the visitor. If the variant is unset, the specified defaultValue is passed to the visitor.
template<class TYPES> template<class VISITOR > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 1, typename VISITOR::ResultType>::type bdlb::VariantImp< TYPES >::applyRaw (VISITOR & visitor) const [inline]
< Apply the specified visitor to this variant by passing the value this variant currently holds to the visitor object's operator(), and return the value (of template parameter RET_TYPE) returned by the visitor. The behavior is undefined if this variant is unset. Note that this method is selected only if the template parameter type VISITOR defines a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
template<class TYPES> template<class VISITOR > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 1, typename VISITOR::ResultType>::type bdlb::VariantImp< TYPES >::applyRaw (const VISITOR & visitor) const [inline]
< Apply the specified visitor to this variant by passing the value this variant currently holds to the visitor object's operator(), and return the value returned by the visitor. The behavior is undefined if this variant is unset. Note that this method is selected only if the template parameter type VISITOR defines a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
template<class TYPES> template<class VISITOR > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 0, void>::type bdlb::VariantImp< TYPES >::applyRaw (VISITOR & visitor) const [inline]
< Apply the specified visitor to this variant by passing the value this variant currently holds to the visitor object's operator(). This method does not return a value. The behavior is undefined if this variant is unset. Note that this method is selected only if the template parameter type VISITOR does not define a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
template<class TYPES> template<class VISITOR > bsl::enable_if<Variant_ReturnValueHelper<VISITOR>::value == 0, void>::type bdlb::VariantImp< TYPES >::applyRaw (const VISITOR & visitor) const [inline]
< Apply the specified visitor to this variant by passing the value this variant currently holds to the visitor object's operator(). This method does not return a value. The behavior is undefined if this variant is unset. Note that this method is selected only if the template parameter type VISITOR does not define a typedef of ResultType in its public interface. Also note that this method is defined inline to work around a Windows compiler bug with SFINAE functions.
template<class TYPES> template<class RET_TYPE , class VISITOR > RET_TYPE bdlb::VariantImp< TYPES >::applyRaw (VISITOR & visitor) const
template<class TYPES> template<class RET_TYPE , class VISITOR > RET_TYPE bdlb::VariantImp< TYPES >::applyRaw (const VISITOR & visitor) const
Apply the specified visitor to this variant by passing the value this variant currently holds to the visitor object's operator(), and return the value (of template parameter RET_TYPE) returned by the visitor. The behavior is undefined if this variant is unset.
template<class TYPES> template<class TYPE > bool bdlb::VariantImp< TYPES >::is () const
Return true if the value held by this variant object is of the template parameter TYPE, and false otherwise. Note that TYPE must be specified explicitly, e.g., myValue.is<int>().
template<class TYPES> bool bdlb::VariantImp< TYPES >::isUnset () const
Return true if this variant is currently unset, and false otherwise. An unset variant does not hold a value or type. Note that this method should be preferred over checking the type index of the variant.
template<class TYPES> bsl::ostream& bdlb::VariantImp< TYPES >::print (bsl::ostream & stream, int level = 0, int spacesPerLevel = 4) const
Format this object to the specified output stream at the (absolute value of) the optionally specified indentation level and return a reference to stream. If level is specified, optionally specify spacesPerLevel, the number of spaces per indentation level for this and all of its nested objects. If level is negative, suppress indentation of the first line. If spacesPerLevel is negative, format the entire output on one line, suppressing all but the initial indentation (as governed by level). If stream is not valid on entry, this operation has no effect. Note that the string "(* UNPRINTABLE *)" will be printed if the object held by this variant is not printable, and the string "(* NULL *)" will be printed if this variant holds no object.
template<class TYPES> template<class TYPE > const TYPE& bdlb::VariantImp< TYPES >::the () const
Return a reference providing non-modifiable access to the value of the template parameter TYPE held by this variant object. The behavior is undefined unless is<TYPE>() returns true and TYPE is not void. Note that TYPE must be specified explicitly, e.g., myValue.the<int>().
template<class TYPES> int bdlb::VariantImp< TYPES >::typeIndex () const
Return the index in the list of TYPES corresponding to the type of the value currently held by this variant object (starting at 1), or 0 if this object is unset. Note that instead of switching code on the type index, calling apply is the preferred method of manipulating different types stored inside a variant.
The documentation for this class was generated from the following file:
bdlb_variant.h