BDE 3.0: Class balxml::Formatter
Quick Links:
bal | bbl | bdl | bsl | btl
balxml::Formatter Class Reference
#include <balxml_formatter.h>
Classes
class ElemContext
Public Types
enum WhitespaceType { e_PRESERVE_WHITESPACE, e_WORDWRAP, e_WORDWRAP_INDENT, e_NEWLINE_INDENT }
Public Member Functions
Formatter (bsl::streambuf *output, int indentLevel=0, int spacesPerLevel=4, int wrapColumn=80, bslma::Allocator *basic_allocator=0)
Formatter (bsl::ostream &output, int indentLevel=0, int spacesPerLevel=4, int wrapColumn=80, bslma::Allocator *basic_allocator=0)
~Formatter ()
template<class TYPE >
void addAttribute (const bslstl::StringRef &name, const TYPE &value, int formattingMode=0)
void addBlankLine ()
void addComment (const bslstl::StringRef &comment, bool forceNewline=true)
template<class TYPE >
void addData (const TYPE &value, int formattingMode=0)
template<class TYPE >
void addListData (const TYPE &value, int formattingMode=0)
template<class TYPE >
void addElementAndData (const bslstl::StringRef &name, const TYPE &value, int formattingMode=0)
void addHeader (const bslstl::StringRef &encoding="UTF-8")
void addNewline ()
void closeElement (const bslstl::StringRef &name)
void flush ()
void openElement (const bslstl::StringRef &name, WhitespaceType ws=e_PRESERVE_WHITESPACE)
bsl::ostream & rawOutputStream ()
void reset ()
int outputColumn () const
int indentLevel () const
int spacesPerLevel () const
int status () const
int wrapColumn () const
Friends
class ElemContext
Detailed Description
This class provides a set of XML-style formatting utilities that enable transparent indentation and wrapping for users attempting to format data with XML tags and attributes. A formatter object is instantiated with a pointer to an output stream or streambuf. Users can then use the provided utilities to write element tags, attributes, data in a valid XML sequence into the underlying stream.
This class has no features that would impair thread safety. However, it does not mediate between two threads attempting to access the same stream.
Member Enumeration Documentation
enum balxml::Formatter::WhitespaceType
This describes options available when outputting textual data of an element between its pair of opening and closing tags.
Enumerator:
e_PRESERVE_WHITESPACE
data is output as is
e_WORDWRAP
data may be wrapped if output otherwise exceeds the wrap column
e_WORDWRAP_INDENT
in addition to allowing wrapping, indent properly before continuing to output on the next line after wrapping
e_NEWLINE_INDENT
in addition to allowing wrapping and indentation, the tags do not share their respective lines with data Current implementation does not provide the capability of analyzing the internal whitespace in individual textual data and breaking the line at such whitespace. However, these options are meaningful when individual data is output as part of a list, as in the case of consecutive calls to addListData.
Constructor & Destructor Documentation
balxml::Formatter::Formatter (bsl::streambuf * output, int indentLevel = 0, int spacesPerLevel = 4, int wrapColumn = 80, bslma::Allocator * basic_allocator = 0)
balxml::Formatter::Formatter (bsl::ostream & output, int indentLevel = 0, int spacesPerLevel = 4, int wrapColumn = 80, bslma::Allocator * basic_allocator = 0)
Construct an object to format XML data into the specified output stream or streambuf. Optionally specify initial indentLevel, spacesPerLevel, and wrapColumn for formatting. An indentLevel of 0 (the default) indicates the root element will have no indentation. A wrapColumn of 0 will cause the formatter to behave as though the line length were infinite, but will still insert newlines and indent when starting a new element. A wrapColumn of -1 will cause output to be formatted in "compact" mode -- with no added newlines or indentation. The behavior is undefined if the output stream or streambuf is destroyed before this object goes out of scope.
balxml::Formatter::~Formatter ()
Destroy this object.
Member Function Documentation
template<class TYPE > void balxml::Formatter::addAttribute (const bslstl::StringRef & name, const TYPE & value, int formattingMode = 0)
Add an attribute the specified name and specified value to the currently open element. value can be of the following types: char, short, int, bsls::Types::Int64, float, double, bsl::string, bdlt::Datetime, bdlt::Date, and bdlt::Time. Precede this name="value" pair with a single space. Wrap line (write the attribute on next line with proper indentation), if the length of name="value" is too long. The behavior is undefined unless the last manipulator was openElement or addAttribute. If value is of type bsl::string, it is truncated at any invalid UTF-8 byte-sequence or any control character [0x00, 0x20) except 0x9, 0xA, and 0x0D, and escaped for five special characters: apostrophe, double quote, ampersand, less than, and greater than. If value is of type char, it is cast to a signed byte value with a range [ -128 .. 127 ].
Referenced by balxml::Encoder_Context::addAttribute().
void balxml::Formatter::addBlankLine ()
Insert one or two newline characters into the output stream such that a blank line results. If the last output was a newline, then only one newline is added, otherwise two newlines are added. If following a call to openElement, or addAttribute, add a closing > to the opened tag.
void balxml::Formatter::addComment (const bslstl::StringRef & comment, bool forceNewline = true)
Write the specified comment into the stream. The specified forceNewLine, if true, forces to start a new line solely for the comment if it's not on a new line already. Otherwise, comments continue on current line. If an element-opening tag is not completed with a >, addComment will add >.
template<class TYPE > void balxml::Formatter::addData (const TYPE & value, int formattingMode = 0)
template<class TYPE > void balxml::Formatter::addListData (const TYPE & value, int formattingMode = 0)
Add the specified value as the data content, where value can be of the following types: char, short, int, bsls::Types::Int64, float, double, bsl::string, bdlt::Datetime, bdlt::Date, and bdlt::Time. addListData prefixes the value with a space(0x20) unless the data being added is the first data on a line. In the case of addData, perform no line-wrapping or indentation as if the whitespace constraint were always BAEXML_PRESERVE_WHITESPACE in openElement, with the only exception that an initial newline and an initial indent is added when openElement specifies BAEXML_NEWLINE_INDENT option. In the case of addListData, when adding the data makes the line too long, perform line-wrapping and indentation as determined by the whitespace constraint used when the current element is opened with openElement. Behavior is undefined if the call is made when there are no opened elements. If value is of type bsl::string, it is truncated at invalid UTF-8 byte-sequence or any control character [0x00, 0x20) except 0x9, 0xA, and 0xD, and escaped for five special characters: apostrophe, double quote, ampersand, less than, and greater than. If value is of type char, it is cast to a signed byte value with a range of [ -128 .. 127 ]. Optionally specify the formattingMode.
template<class TYPE > void balxml::Formatter::addElementAndData (const bslstl::StringRef & name, const TYPE & value, int formattingMode = 0)
Add element of the specified name and the specified value as the data content. This has the same effect as calling the following sequence: openElement(name); addData(value), closeElement(name);. Optionally specify the formattingMode.
void balxml::Formatter::addHeader (const bslstl::StringRef & encoding = "UTF-8")
Add XML header with optionally specified encoding. Version is always "1.0". Behavior is undefined unless addHeader is the first manipulator (with the exception of rawOutputStream) after construction or reset.
void balxml::Formatter::addNewline ()
Insert a literal newline into the XML output. If following a call to openElement, or addAttribute, add a closing > to the opened tag.
void balxml::Formatter::closeElement (const bslstl::StringRef & name)
Decrement the indent level and add the closing tag for the element of the specified name. If the element does not have content, write /> and a newline into stream. Otherwise, write </name> and a newline. If this </name> does not share the same line with data, or it follows another element's closing tag, indent properly before writing </name> and the newline. If name is root element, flush the output stream. Behavior is undefined if name is not the most recently opened element that's yet to be closed.
Referenced by balxml::Encoder_Context::closeElement().
void balxml::Formatter::flush ()
Insert the closing > if there is an incomplete tag, and flush the output stream.
void balxml::Formatter::openElement (const bslstl::StringRef & name, WhitespaceType ws = e_PRESERVE_WHITESPACE)
Open an element of the specified name at current indent level with the optionally specified whitespace constraint ws for its textual data and increment indent level. ws constrains how textual data is written with addListData for the current element, but not its nested elements. Behavior is undefined if openELement is called after the root element is closed and there is no subsequent call to reset.
Referenced by balxml::Encoder_Context::openElement().
bsl::ostream& balxml::Formatter::rawOutputStream ()
Return a reference to the underlining output stream. This method is provided in order to enable user to temporarily jump out of the formatter and write user's own free-lance content directly to the stream.
Referenced by balxml::Encoder_Context::rawOutputStream().
void balxml::Formatter::reset ()
Reset the formatter such that it can be used to format a new XML document as if the formatter were just constructed
int balxml::Formatter::outputColumn () const
Return the current column position at a line where next output starts. This is unreliable if called after free-lance information is written onto the stream returned by rawOutputStream
int balxml::Formatter::indentLevel () const
Return the current level of indentation.
int balxml::Formatter::spacesPerLevel () const
Return the number of spaces per indentation level
int balxml::Formatter::status () const
Return 0 if no errors have been detected since construction or since the last call to reset, otherwise return a negative value.
Referenced by balxml::Encoder_Context::status().
int balxml::Formatter::wrapColumn () const
Return the line width where line-wrapping takes place
Friends And Related Function Documentation
friend class ElemContext [friend]
The documentation for this class was generated from the following file:
balxml_formatter.h