BDE 3.0: Class bdlf::MemFn
Quick Links:
bal | bbl | bdl | bsl | btl
bdlf::MemFn< PROTOTYPE > Class Template Reference
#include <bdlf_memfn.h>
Public Types
typedef Traits::ResultType ResultType
typedef Traits::ArgumentList Args
typedef Traits::ClassType ObjectType
typedef PROTOTYPE Prototype
typedef PROTOTYPE ProtoType
Public Member Functions
BSLMF_NESTED_TRAIT_DECLARATION (MemFn, bsl::is_trivially_copyable)
BSLMF_NESTED_TRAIT_DECLARATION (MemFn, bslmf::IsBitwiseMoveable)
MemFn (PROTOTYPE func)
MemFn (const MemFn< PROTOTYPE > &original)
template<class INSTANCE >
ResultType operator() (INSTANCE &object) const
template<class INSTANCE >
ResultType operator() (INSTANCE &object, A1 a1) const
template<class INSTANCE >
ResultType operator() (INSTANCE &object, A1 a1, A2 a2) const
template<class INSTANCE >
ResultType operator() (INSTANCE &object, A1 a1, A2 a2, A3 a3) const
template<class INSTANCE >
ResultType operator() (INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4) const
template<class INSTANCE >
ResultType operator() (INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5) const
template<class INSTANCE >
ResultType operator() (INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6) const
template<class INSTANCE >
ResultType operator() (INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7) const
template<class INSTANCE >
ResultType operator() (INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8) const
template<class INSTANCE >
ResultType operator() (INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9) const
template<class INSTANCE >
ResultType operator() (INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10) const
template<class INSTANCE >
ResultType operator() (INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10, A11 a11) const
template<class INSTANCE >
ResultType operator() (INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10, A11 a11, A12 a12) const
template<class INSTANCE >
ResultType operator() (INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10, A11 a11, A12 a12, A13 a13) const
template<class INSTANCE >
ResultType operator() (INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10, A11 a11, A12 a12, A13 a13, A14 a14) const
template<class INSTANCE >
ResultType operator() (const INSTANCE &object) const
template<class INSTANCE >
ResultType operator() (const INSTANCE &object, A1 a1) const
template<class INSTANCE >
ResultType operator() (const INSTANCE &object, A1 a1, A2 a2) const
template<class INSTANCE >
ResultType operator() (const INSTANCE &object, A1 a1, A2 a2, A3 a3) const
template<class INSTANCE >
ResultType operator() (const INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4) const
template<class INSTANCE >
ResultType operator() (const INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5) const
template<class INSTANCE >
ResultType operator() (const INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6) const
template<class INSTANCE >
ResultType operator() (const INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7) const
template<class INSTANCE >
ResultType operator() (const INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8) const
template<class INSTANCE >
ResultType operator() (const INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9) const
template<class INSTANCE >
ResultType operator() (const INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10) const
template<class INSTANCE >
ResultType operator() (const INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10, A11 a11) const
template<class INSTANCE >
ResultType operator() (const INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10, A11 a11, A12 a12) const
template<class INSTANCE >
ResultType operator() (const INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10, A11 a11, A12 a12, A13 a13) const
template<class INSTANCE >
ResultType operator() (const INSTANCE &object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10, A11 a11, A12 a12, A13 a13, A14 a14) const
Detailed Description
template<class PROTOTYPE>
class bdlf::MemFn< PROTOTYPE >
This class encapsulates a member function pointer having the parameterized PROTOTYPE, such that the member function pointer can be invoked in syntactically the same manner as a free function pointer. When invoking a member function through this wrapper, the first argument must be a pointer or reference to the instance on which to invoke the member function pointer. Zero to fourteen additional arguments may be specified depending on PROTOTYPE.
Member Typedef Documentation
template<class PROTOTYPE> typedef Traits::ResultType bdlf::MemFn< PROTOTYPE >::ResultType
template<class PROTOTYPE> typedef Traits::ArgumentList bdlf::MemFn< PROTOTYPE >::Args
template<class PROTOTYPE> typedef Traits::ClassType bdlf::MemFn< PROTOTYPE >::ObjectType
template<class PROTOTYPE> typedef PROTOTYPE bdlf::MemFn< PROTOTYPE >::Prototype
template<class PROTOTYPE> typedef PROTOTYPE bdlf::MemFn< PROTOTYPE >::ProtoType
Constructor & Destructor Documentation
template<class PROTOTYPE> bdlf::MemFn< PROTOTYPE >::MemFn (PROTOTYPE func) [explicit]
Create a member function pointer wrapper holding the address of the specified func member function having the parameterized PROTOTYPE.
template<class PROTOTYPE> bdlf::MemFn< PROTOTYPE >::MemFn (const MemFn< PROTOTYPE > & original)
Create a member function pointer wrapper holding the address of the same member function as the specified original object.
Member Function Documentation
template<class PROTOTYPE> bdlf::MemFn< PROTOTYPE >::BSLMF_NESTED_TRAIT_DECLARATION (MemFn< PROTOTYPE > , bsl::is_trivially_copyable)
template<class PROTOTYPE> bdlf::MemFn< PROTOTYPE >::BSLMF_NESTED_TRAIT_DECLARATION (MemFn< PROTOTYPE > , bslmf::IsBitwiseMoveable)
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (INSTANCE & object) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a modifiable instance of the parameterized INSTANCE type, with no specified arguments, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (INSTANCE & object, A1 a1) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a modifiable instance of the parameterized INSTANCE type, with the specified argument a1, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (INSTANCE & object, A1 a1, A2 a2) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a modifiable instance of the parameterized INSTANCE type, with the specified argument a1 up to a2, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (INSTANCE & object, A1 a1, A2 a2, A3 a3) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a modifiable instance of the parameterized INSTANCE type, with the specified argument a1 up to a3, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a modifiable instance of the parameterized INSTANCE type, with the specified argument a1 up to a4, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a modifiable instance of the parameterized INSTANCE type, with the specified argument a1 up to a5, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a modifiable instance of the parameterized INSTANCE type, with the specified argument a1 up to a6, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a modifiable instance of the parameterized INSTANCE type, with the specified argument a1 up to a7, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a modifiable instance of the parameterized INSTANCE type, with the specified argument a1 up to a8, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a modifiable instance of the parameterized INSTANCE type, with the specified argument a1 up to a9, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a modifiable instance of the parameterized INSTANCE type, with the specified argument a1 up to a10, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10, A11 a11) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a modifiable instance of the parameterized INSTANCE type, with the specified argument a1 up to a11, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10, A11 a11, A12 a12) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a modifiable instance of the parameterized INSTANCE type, with the specified argument a1 up to a12, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10, A11 a11, A12 a12, A13 a13) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a modifiable instance of the parameterized INSTANCE type, with the specified argument a1 up to a13, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10, A11 a11, A12 a12, A13 a13, A14 a14) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a modifiable instance of the parameterized INSTANCE type, with the specified argument a1 up to a14, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (const INSTANCE & object) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a non-modifiable instance of the parameterized INSTANCE type, with no arguments, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (const INSTANCE & object, A1 a1) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a non-modifiable instance of the parameterized INSTANCE type, with the specified argument a1, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (const INSTANCE & object, A1 a1, A2 a2) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a non-modifiable instance of the parameterized INSTANCE type, with the specified arguments a1 up to a2, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (const INSTANCE & object, A1 a1, A2 a2, A3 a3) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a non-modifiable instance of the parameterized INSTANCE type, with the specified arguments a1 up to a3, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (const INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a non-modifiable instance of the parameterized INSTANCE type, with the specified arguments a1 up to a4, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (const INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a non-modifiable instance of the parameterized INSTANCE type, with the specified arguments a1 up to a5, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (const INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a non-modifiable instance of the parameterized INSTANCE type, with the specified arguments a1 up to a6, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (const INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a non-modifiable instance of the parameterized INSTANCE type, with the specified arguments a1 up to a7, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (const INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a non-modifiable instance of the parameterized INSTANCE type, with the specified arguments a1 up to a8, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (const INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a non-modifiable instance of the parameterized INSTANCE type, with the specified arguments a1 up to a9, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (const INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a non-modifiable instance of the parameterized INSTANCE type, with the specified arguments a1 up to a10, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (const INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10, A11 a11) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a non-modifiable instance of the parameterized INSTANCE type, with the specified arguments a1 up to a11, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (const INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10, A11 a11, A12 a12) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a non-modifiable instance of the parameterized INSTANCE type, with the specified arguments a1 up to a12, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (const INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10, A11 a11, A12 a12, A13 a13) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a non-modifiable instance of the parameterized INSTANCE type, with the specified arguments a1 up to a13, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class PROTOTYPE> template<class INSTANCE > ResultType bdlf::MemFn< PROTOTYPE >::operator() (const INSTANCE & object, A1 a1, A2 a2, A3 a3, A4 a4, A5 a5, A6 a6, A7 a7, A8 a8, A9 a9, A10 a10, A11 a11, A12 a12, A13 a13, A14 a14) const [inline]
< Invoke the member function pointer held by this wrapper on the specified object reference to a non-modifiable instance of the parameterized INSTANCE type, with the specified arguments a1 up to a14, and return the result of this invocation, or void if this member function pointer does not return a result.
References bdlf::MemFn_Dereference< OBJTYPE >::deref().
The documentation for this class was generated from the following file:
bdlf_memfn.h