BDE 3.0: Class btlso::InetStreamSocketCloseGuard
Quick Links:
bal | bbl | bdl | bsl | btl
btlso::InetStreamSocketCloseGuard Class Reference
#include <btlso_inetstreamsocket.h>
Public Member Functions
InetStreamSocketCloseGuard (SocketHandle::Handle socketHandle)
~InetStreamSocketCloseGuard ()
void release ()
Detailed Description
This class implements a proctor that automatically closes the managed socket at destruction unless its release method is invoked.
Constructor & Destructor Documentation
btlso::InetStreamSocketCloseGuard::InetStreamSocketCloseGuard (SocketHandle::Handle socketHandle) [inline, explicit]
Create a proctor object to manage socket having the specified socketHandle.
btlso::InetStreamSocketCloseGuard::~InetStreamSocketCloseGuard () [inline]
Destroy this proctor object and, unless the release method has been previously called, close the managed socket.
References btlso::SocketImpUtil::close().
Member Function Documentation
void btlso::InetStreamSocketCloseGuard::release () [inline]
Release from management the socket currently managed by this proctor. If no socket is currently being managed, this operation has no effect.
Referenced by btlso::InetStreamSocket< ADDRESS >::accept(), and btlso::InetStreamSocketFactory< ADDRESS >::allocate().
The documentation for this class was generated from the following file:
btlso_inetstreamsocket.h