BDE 3.0: Class balxml::Encoder_Context
Quick Links:
bal | bbl | bdl | bsl | btl
balxml::Encoder_Context Class Reference
#include <balxml_encoder.h>
Public Member Functions
Encoder_Context (Formatter *formatter, Encoder *encoder)
int status () const
const EncoderOptions & encoderOptions () const
bsl::ostream & rawOutputStream ()
void invalidate ()
ErrorInfo::Severity logError (const char *text, const bslstl::StringRef &tag, int formattingMode, int index=-1)
template<class NAME_TYPE , class VALUE_TYPE >
void addAttribute (const NAME_TYPE &name, const VALUE_TYPE &value, int formattingMode)
template<class NAME_TYPE , class VALUE_TYPE >
void addAttribute (const NAME_TYPE &name, const VALUE_TYPE &value)
template<class NAME_TYPE >
void openElement (const NAME_TYPE &name)
template<class NAME_TYPE >
void closeElement (const NAME_TYPE &name)
Static Public Member Functions
template<class TYPE >
static void encode (const TYPE &object)
Detailed Description
This struct contains state that is maintained during encoding. It also contains methods for switching between pretty formatting and compact formatting, based on the encoding options.
Constructor & Destructor Documentation
balxml::Encoder_Context::Encoder_Context (Formatter * formatter, Encoder * encoder)
Member Function Documentation
int balxml::Encoder_Context::status () const [inline]
References balxml::Formatter::status().
const EncoderOptions& balxml::Encoder_Context::encoderOptions () const [inline]
References balxml::Encoder::options().
bsl::ostream& balxml::Encoder_Context::rawOutputStream () [inline]
References balxml::Formatter::rawOutputStream().
Referenced by invalidate().
void balxml::Encoder_Context::invalidate () [inline]
References rawOutputStream().
ErrorInfo::Severity balxml::Encoder_Context::logError (const char * text, const bslstl::StringRef & tag, int formattingMode, int index = -1) [inline]
template<class TYPE > static void balxml::Encoder_Context::encode (const TYPE & object) [static]
template<class NAME_TYPE , class VALUE_TYPE > void balxml::Encoder_Context::addAttribute (const NAME_TYPE & name, const VALUE_TYPE & value, int formattingMode) [inline]
References balxml::Formatter::addAttribute().
template<class NAME_TYPE , class VALUE_TYPE > void balxml::Encoder_Context::addAttribute (const NAME_TYPE & name, const VALUE_TYPE & value) [inline]
References balxml::Formatter::addAttribute(), and bdlat_FormattingMode::e_DEFAULT.
template<class NAME_TYPE > void balxml::Encoder_Context::openElement (const NAME_TYPE & name) [inline]
References balxml::Formatter::openElement().
template<class NAME_TYPE > void balxml::Encoder_Context::closeElement (const NAME_TYPE & name) [inline]
References balxml::Formatter::closeElement().
The documentation for this class was generated from the following file:
balxml_encoder.h