BDE 2.16 BETA: bslstl_ostringstream Component
Quick Links:
bsl+bslhdrs | bsl+stdhdrs | bslalg | bsldoc | bslim | bslma | bslmf | bsls | bslscm | bslstl | bsltf
Component bslstl_ostringstream
[Package bslstl]
Provide a C++03-compatible ostringstream class.
Classes
class bsl::basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >
Typedefs
typedef CHAR_TYPE bsl::basic_ostringstream::char_type
typedef CHAR_TRAITS bsl::basic_ostringstream::traits_type
typedef ALLOCATOR bsl::basic_ostringstream::allocator_type
typedef traits_type::int_type bsl::basic_ostringstream::int_type
typedef traits_type::off_type bsl::basic_ostringstream::off_type
typedef traits_type::pos_type bsl::basic_ostringstream::pos_type
Functions
bsl::basic_ostringstream::basic_ostringstream (const allocator_type &allocator=allocator_type())
bsl::basic_ostringstream::basic_ostringstream (ios_base::openmode modeBitMask, const allocator_type &allocator=allocator_type())
bsl::basic_ostringstream::basic_ostringstream (const StringType &initialString, const allocator_type &allocator=allocator_type())
bsl::basic_ostringstream::basic_ostringstream (const StringType &initialString, ios_base::openmode modeBitMask, const allocator_type &allocator=allocator_type())
bsl::basic_ostringstream::~basic_ostringstream ()
void bsl::basic_ostringstream::str (const StringType &value)
StringType bsl::basic_ostringstream::str () const
StreamBufType * bsl::basic_ostringstream::rdbuf () const
Detailed Description
Outline
Purpose
Classes
Description
Memory Allocation
bslma-Style Allocators
Usage
Example 1: Basic Output Operations
Purpose:
Provide a C++03-compatible ostringstream class.
Classes:
bsl::ostringstream C++03-compatible ostringstream class
See also:
Description:
This component is for internal use only. Please include <bsl_sstream.h> instead.
This component defines a class template, bsl::basic_ostringstream, implementing a standard output stream that provides a method for obtaining a bsl::basic_string, which contains the characters that have been written to the stream (see 27.8.4 [ostringstream] of the C++11 standard). This component also defines two standard aliases, bsl::ostringstream and bsl::wostringstream, that refer to specializations of the bsl::basic_ostringstream template for char and wchar_t types, respectively. The bsl::basic_ostringstream template has three parameters, CHAR_TYPE, CHAR_TRAITS, and ALLOCATOR. The CHAR_TYPE and CHAR_TRAITS parameters respectively define the character type for the string-stream and a type providing a set of operations the string-stream will use to manipulate characters of that type, which must meet the character traits requirements defined by the C++11 standard, 21.2 [char.traits]. The ALLOCATOR template parameter is described in the "Memory Allocation" section below.
Memory Allocation:
The type supplied as a string-stream's ALLOCATOR template parameter determines how that string-stream will allocate memory. The basic_ostringstream template supports allocators meeting the requirements of the C++11 standard, 17.6.3.5 [allocator.requirements]; in addition, it supports scoped-allocators derived from the bslma::Allocator memory allocation protocol. Clients intending to use bslma-style allocators should use bsl::allocator, which provides a C++11 standard-compatible adapter for a bslma::Allocator object. Note that the standard aliases bsl::ostringstream and bsl::wostringstream both use bsl::allocator.
bslma-Style Allocators:
If the type supplied for the ALLOCATOR template parameter of an ostringstream instantiation is bsl::allocator, then objects of that string-stream type will conform to the standard behavior of a bslma-allocator-enabled type. Such a string-stream accepts an optional bslma::Allocator argument at construction. If the address of a bslma::Allocator object is explicitly supplied at construction, it will be used to supply memory for the string-stream throughout its lifetime; otherwise, the string-stream will use the default allocator installed at the time of the string-stream's construction (see bslma_default).
Usage:
This section illustrates intended use of this component.
Example 1: Basic Output Operations:
The following example demonstrates the use of bsl::ostringstream to write data of various types into a bsl::string object.
Suppose we want to implement a simplified converter from a generic type, TYPE, to bsl::string. We use bsl::ostringstream to implement the toString function. We write the data into the stream with operator<< and then use the str method to retrieve the resulting string from the stream:
  template <class TYPE>
  bsl::string toString(const TYPE& what)
  {
      bsl::ostringstream out;
      out << what;
      return out.str();
  }
Finally, we verify that our toString function works on some simple test cases:
  assert(toString(1234) == "1234");
  assert(toString<short>(-5) == "-5");
  assert(toString("abc") == "abc");
Typedef Documentation
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > typedef CHAR_TYPE bsl::basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::char_type [inherited]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > typedef CHAR_TRAITS bsl::basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::traits_type [inherited]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > typedef ALLOCATOR bsl::basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::allocator_type [inherited]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > typedef traits_type::int_type bsl::basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::int_type [inherited]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > typedef traits_type::off_type bsl::basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::off_type [inherited]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > typedef traits_type::pos_type bsl::basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::pos_type [inherited]
Function Documentation
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > bsl::basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::basic_ostringstream (const allocator_type & allocator = allocator_type()) [inline, explicit, inherited]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > bsl::basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::basic_ostringstream (ios_base::openmode modeBitMask, const allocator_type & allocator = allocator_type()) [inline, explicit, inherited]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > bsl::basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::basic_ostringstream (const StringType & initialString, const allocator_type & allocator = allocator_type()) [inline, explicit, inherited]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > bsl::basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::basic_ostringstream (const StringType & initialString, ios_base::openmode modeBitMask, const allocator_type & allocator = allocator_type()) [inline, inherited]
Create a basic_ostringstream object. Optionally specify a modeBitMask indicating whether the underlying stream-buffer may also be read from (rdbuf is created using modeBitMask | ios_base::out). If modeBitMask is not supplied, rdbuf will be created using ios_base::out. Optionally specify an initialString indicating the value that will be returned by a call to str prior to any streaming operations performed on this object. If initialString is not supplied, str will initially return an empty string. Optionally specify an allocator used to supply memory. If allocator is not supplied, a default-constructed object of the (template parameter) ALLOCATOR type is used. If the ALLOCATOR argument is of type bsl::allocator (the default), then allocator, if supplied, shall be convertible to bslma::Allocator *. If the ALLOCATOR argument is of type bsl::allocator and allocator is not supplied, the currently installed default allocator will be used to supply memory.
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > bsl::basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::~basic_ostringstream () [inherited]
Destroy this object.
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > void bsl::basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::str (const StringType & value) [inline, inherited]
Reset the internally buffered sequence of characters maintained by this stream object to the specified value.
References bsl::basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rdbuf(), and bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::str().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::StringType bsl::basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::str () const [inline, inherited]
Return the sequence of characters that have been written to this stream object.
References bsl::basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rdbuf(), and bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::str().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::StreamBufType * bsl::basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rdbuf () const [inline, inherited]
Return an address providing modifiable access to the basic_stringbuf object that is internally used by this string stream to buffer unformatted characters.
Reimplemented from bsl::StringBufContainer< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >.
References bsl::StringBufContainer< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rdbuf().
Referenced by bsl::basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::str().