BDE 2.16 BETA: bslstl_stringbuf Component
Quick Links:
bsl+bslhdrs | bsl+stdhdrs | bslalg | bsldoc | bslim | bslma | bslmf | bsls | bslscm | bslstl | bsltf
Component bslstl_stringbuf
[Package bslstl]
Provide a C++03-compatible stringbuf class.
Classes
class bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >
Typedefs
typedef CHAR_TYPE bsl::basic_stringbuf::char_type
typedef CHAR_TRAITS bsl::basic_stringbuf::traits_type
typedef ALLOCATOR bsl::basic_stringbuf::allocator_type
typedef traits_type::int_type bsl::basic_stringbuf::int_type
typedef traits_type::off_type bsl::basic_stringbuf::off_type
typedef traits_type::pos_type bsl::basic_stringbuf::pos_type
Functions
virtual pos_type bsl::basic_stringbuf::seekoff (off_type offset, ios_base::seekdir whence, ios_base::openmode modeBitMask=ios_base::in|ios_base::out)
virtual pos_type bsl::basic_stringbuf::seekpos (pos_type absoluteOffset, ios_base::openmode modeBitMask=ios_base::in|ios_base::out)
virtual native_std::streamsize bsl::basic_stringbuf::xsgetn (char_type *result, native_std::streamsize numCharacters)
virtual int_type bsl::basic_stringbuf::underflow ()
virtual int_type bsl::basic_stringbuf::uflow ()
virtual int_type bsl::basic_stringbuf::pbackfail (int_type character=traits_type::eof())
virtual native_std::streamsize bsl::basic_stringbuf::xsputn (const char_type *inputString, native_std::streamsize numCharacters)
virtual int_type bsl::basic_stringbuf::overflow (int_type character=traits_type::eof())
bsl::basic_stringbuf::basic_stringbuf (const allocator_type &allocator=allocator_type())
bsl::basic_stringbuf::basic_stringbuf (ios_base::openmode modeBitMask, const allocator_type &allocator=allocator_type())
bsl::basic_stringbuf::basic_stringbuf (const StringType &initialString, const allocator_type &allocator=allocator_type())
bsl::basic_stringbuf::basic_stringbuf (const StringType &initialString, ios_base::openmode modeBitMask, const allocator_type &allocator=allocator_type())
bsl::basic_stringbuf::~basic_stringbuf ()
void bsl::basic_stringbuf::str (const StringType &value)
StringType bsl::basic_stringbuf::str () const
bsl::StringBufContainer::StringBufContainer (const ALLOCATOR &allocator)
bsl::StringBufContainer::StringBufContainer (ios_base::openmode modeBitMask, const ALLOCATOR &allocator)
bsl::StringBufContainer::StringBufContainer (const StringType &initialString, const ALLOCATOR &allocator)
bsl::StringBufContainer::StringBufContainer (const StringType &initialString, ios_base::openmode modeBitMask, const ALLOCATOR &allocator)
bsl::StringBufContainer::~StringBufContainer ()
StreamBufType * bsl::StringBufContainer::rdbuf () const
Detailed Description
Outline
Purpose
Classes
Description
Memory Allocation
bslma-Style Allocators
Usage
Example 1: Basic Operations
Purpose:
Provide a C++03-compatible stringbuf class.
Classes:
bsl::stringbuf C++03-compatible stringbuf class
bsl::StringBufContainer wrapper for basic_stringbuf
See also:
Component bslstl_stringstream, Component bslstl_ostringstream, Component bslstl_istringstream
Description:
This component is for internal use only. Please include <bsl_sstream.h> instead.
This component defines a class template, bsl::basic_stringbuf, that implements a standard string buffer, providing an unformatted character input sequence and an unformatted character output sequence that may be initialized or accessed using a string value (see 27.8.2 [stringbuf] of the C++11 standard). This component also defines two standard aliases, bsl::stringbuf and bsl::wstringbuf, that refer to specializations of the bsl::basic_stringbuf template for char and wchar_t types, respectively. As with any stream buffer class, bsl::basic_stringbuf is rarely used directly. Stream buffers provide low-level unformatted input/output. They are usually plugged into std::basic_stream classes to provide higher-level formatted input and output via operator<< and operator>>. bsl::basic_stringbuf is used in the bsl::basic_stringstream family of classes and users should prefer those classes over direct use of bsl::basic_stringbuf.
bsl::basic_stringbuf derives from std::basic_streambuf and implements the necessary protected virtual methods. In this way bsl::basic_stringbuf customizes the behavior of std::basic_streambuf to redirect the reading and writing of characters to an internally-maintained sequence of characters that can be initialized or accessed using a bsl::basic_string. Note that although the standard mandates functions that access and modify the buffered sequence using a basic_string, it does not mandate that a basic_stringbuf internally store this buffer in a basic_string; this implementation currently uses a basic_string as its internal buffer, but that is subject to change without warning.
The bsl::stringbuf template has three parameters, CHAR_TYPE, CHAR_TRAITS, and ALLOCATOR. The CHAR_TYPE and CHAR_TRAITS parameters respectively define the character type for the stream buffer and a type providing a set of operations the stream buffer will use to manipulate characters of that type, which must meet the character traits requirements defined by the C++11 standard, 21.2 [char.traits]. The ALLOCATOR template parameter is described in the "Memory Allocation" section below.
Memory Allocation:
The type supplied as a stream buffer's ALLOCATOR template parameter determines how that stream buffer will allocate memory. The basic_stringbuf template supports allocators meeting the requirements of the C++11 standard, 17.6.3.5 [allocator.requirements]; in addition, it supports scoped-allocators derived from the bslma::Allocator memory allocation protocol. Clients intending to use bslma-style allocators should use bsl::allocator, which provides a C++11 standard-compatible adapter for a bslma::Allocator object. Note that the standard aliases bsl::stringbuf and bsl::wstringbuf both use bsl::allocator.
bslma-Style Allocators:
If the type supplied for the ALLOCATOR template parameter of a stringbuf instantiation is bsl::allocator, then objects of that stream buffer type will conform to the standard behavior of a bslma-allocator-enabled type. Such a stream buffer accepts an optional bslma::Allocator argument at construction. If the address of a bslma::Allocator object is explicitly supplied at construction, it will be used to supply memory for the stream buffer throughout its lifetime; otherwise, the stream buffer will use the default allocator installed at the time of the stream buffer's construction (see bslma_default).
Usage:
This section illustrates intended use of this component.
Example 1: Basic Operations:
The following example demonstrates the use of bsl::stringbuf to read and write character data from and to a bsl::string object.
Suppose we want to implement a simplified converter from unsigned int to bsl::string and back. First, we define the prototypes of two conversion functions:
  bsl::string  toString(unsigned int from);
  unsigned int fromString(const bsl::string& from);
Then, we use bsl::stringbuf to implement the toString function. We write all digits into bsl::stringbuf individually using sputc methods and then return the resulting bsl::string object:
  #include <algorithm>
  bsl::string toString(unsigned int from)
  {
      bsl::stringbuf out;
      for (; from != 0; from /= 10) {
          out.sputc('0' + from % 10);
      }
      bsl::string result(out.str());
      std::reverse(result.begin(), result.end());
      return result;
  }
Now, we implement the fromString function that converts from bsl::string to unsigned int by using bsl::stringbuf to read individual digits from the string object:
  unsigned int fromString(const bsl::string& from)
  {
      unsigned int result = 0;
      for (bsl::stringbuf in(from); in.in_avail(); ) {
          result = result * 10 + (in.sbumpc() - '0');
      }
      return result;
  }
Finally, we verify that the result of the round-trip conversion is identical to the original value:
  unsigned int orig   = 92872498;
  unsigned int result = fromString(toString(orig));
  assert(orig == result);
Typedef Documentation
template<class CHAR_TYPE, class CHAR_TRAITS, class ALLOCATOR> typedef CHAR_TYPE bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::char_type [inherited]
template<class CHAR_TYPE, class CHAR_TRAITS, class ALLOCATOR> typedef CHAR_TRAITS bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::traits_type [inherited]
template<class CHAR_TYPE, class CHAR_TRAITS, class ALLOCATOR> typedef ALLOCATOR bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::allocator_type [inherited]
template<class CHAR_TYPE, class CHAR_TRAITS, class ALLOCATOR> typedef traits_type::int_type bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::int_type [inherited]
template<class CHAR_TYPE, class CHAR_TRAITS, class ALLOCATOR> typedef traits_type::off_type bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::off_type [inherited]
template<class CHAR_TYPE, class CHAR_TRAITS, class ALLOCATOR> typedef traits_type::pos_type bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::pos_type [inherited]
Function Documentation
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::pos_type bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::seekoff (off_type offset, ios_base::seekdir whence, ios_base::openmode modeBitMask = ios_base::in | ios_base::out) [protected, virtual, inherited]
Set the current input position or the current output position (or both) to the specified offset from the specified whence location. Optionally specify a modeBitMask indicating whether to set the current input position, current output position, or both. If whence is ios_base::beg, set the current position to the indicated offset from the beginning of the stream; if whence is ios_base::end, set the current position to the indicated offset from the end of the stream; and if whence is ios_base::cur, set the current input or output position to the indicated offset from its current position. If whence is ios_base::cur, then modeBitMask may be either ios_base::in or ios_base::out, but not both. Return the offset of the new position on success, and pos_type(off_type(-1)) otherwise.
References BSLS_ASSERT_OPT.
Referenced by bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::seekpos().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::pos_type bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::seekpos (pos_type absoluteOffset, ios_base::openmode modeBitMask = ios_base::in | ios_base::out) [inline, protected, virtual, inherited]
Set the current input position or the current output position (or both) to the specified absoluteOffset from the beginning of the stream. Optionally specify a modeBitMask indicating whether to set the current input position, current output position, or both. Return the offset of the new position on success, and pos_type(off_type(-1)) otherwise.
References bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::seekoff().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > native_std::streamsize bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::xsgetn (char_type * result, native_std::streamsize numCharacters) [protected, virtual, inherited]
Read up to the specified numCharacters from this stringbuf object and store them in the specified result array. Return the number of characters loaded into result. Note that if fewer than numCharacters characters are available in the buffer, all available characters are loaded into result. The behavior is undefined unless result refers to a contiguous sequence of characters of at least numCharacters.
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::int_type bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::underflow () [protected, virtual, inherited]
Return the character at the current input position, if a character is available, and traits_type::eof() otherwise. Update the end of the input area, egptr, if additional characters are available (as may occur if additional characters have been written to the string buffer). Note that this operation is similar to uflow, but does not advance the current input position.
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::int_type bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::uflow () [protected, virtual, inherited]
Return the character at the current input position and advance the input position by 1. If no character is available at the current input position, return traits_type::eof(). Update the end of the input area, egptr, if additional characters are available (as may occur if additional characters have been written to the string buffer). Note that this operation is similar to underflow, but advances the current input position.
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::int_type bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::pbackfail (int_type character = traits_type::eof()) [protected, virtual, inherited]
Put back the specified character into the input sequence so that the next character read from the input sequence will be character. If character is either traits_type::eof() or is the same as the previously read character from the input sequence, then adjust the current input position, gptr, back one position. If character is neither traits_type::eof() nor the character previously read from the input sequence, but this string buffer was opened for writing (ios_base::out), then adjust the input sequence back one position and write character to that position. Return the character that was put back on success and traits_type::eof() if either the input position is currently at the beginning of the sequence or if the previous character in the input sequence is not character and this buffer was not opened for writing.
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > native_std::streamsize bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::xsputn (const char_type * inputString, native_std::streamsize numCharacters) [protected, virtual, inherited]
Append the specified numCharacters from the specified inputString to the output sequence starting at the current output position (pptr). Update the current output position of this string buffer to refer to the last appended character. Return the number of characters that were appended. The behavior is undefined unless inputString refers to a contiguous sequence of characters of at least numCharacters.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::append(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::int_type bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::overflow (int_type character = traits_type::eof()) [protected, virtual, inherited]
Append the specified character to the output sequence of this stream buffer at the current output position (pptr), and advance the output position by one. This operation may update the end of output area (epptr) to allow for additional writes (e.g., by the base basic_streambuf type) to the output sequence without calling a method on this type. Return the written character on success, and traits_type::eof() if character is traits_type::eof() or this stream buffer was not opened for writing.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::push_back(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::basic_stringbuf (const allocator_type & allocator = allocator_type()) [explicit, inherited]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::basic_stringbuf (ios_base::openmode modeBitMask, const allocator_type & allocator = allocator_type()) [explicit, inherited]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::basic_stringbuf (const StringType & initialString, const allocator_type & allocator = allocator_type()) [explicit, inherited]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::basic_stringbuf (const StringType & initialString, ios_base::openmode modeBitMask, const allocator_type & allocator = allocator_type()) [inline, inherited]
Create a basic_stringbuf object. Optionally specify a modeBitMask indicating whether this buffer may be read from, written to, or both. If modeBitMask is not supplied, this buffer is created with ios_base::in | ios_base::out. Optionally specify an initialString indicating the initial sequence of characters that this buffer will access or manipulate. If initialString is not supplied, the initial sequence of characters will be empty. Optionally specify an allocator used to supply memory. If allocator is not supplied, a default-constructed object of the (template parameter) ALLOCATOR type is used. If the ALLOCATOR argument is of type bsl::allocator (the default), then allocator, if supplied, shall be convertible to bslma::Allocator *. If the ALLOCATOR argument is of type bsl::allocator and allocator is not supplied, the currently installed default allocator will be used to supply memory.
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::~basic_stringbuf () [inherited]
Destroy this object.
References BSLS_ASSERT, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > void bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::str (const StringType & value) [inherited]
Reset the internally buffered sequence of characters to the specified value. Update the beginning and end of both the input and output sequences to be the beginning and end of the updated buffer, update the current input position to be the beginning of the updated buffer, and update the current output position to be the end of the updated buffer.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size().
Referenced by bsl::basic_stringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::str(), bsl::basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::str(), and bsl::basic_istringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::str().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::StringType bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::str () const [inline, inherited]
Return the currently buffered sequence of characters.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > bsl::StringBufContainer< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::StringBufContainer (const ALLOCATOR & allocator) [inline, explicit, inherited]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > bsl::StringBufContainer< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::StringBufContainer (ios_base::openmode modeBitMask, const ALLOCATOR & allocator) [inline, inherited]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > bsl::StringBufContainer< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::StringBufContainer (const StringType & initialString, const ALLOCATOR & allocator) [inline, inherited]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > bsl::StringBufContainer< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::StringBufContainer (const StringType & initialString, ios_base::openmode modeBitMask, const ALLOCATOR & allocator) [inline, inherited]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > bsl::StringBufContainer< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::~StringBufContainer () [inherited]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > StreamBufType* bsl::StringBufContainer< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rdbuf () const [inline, inherited]
Reimplemented in bsl::basic_istringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >, bsl::basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >, and bsl::basic_stringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >.
Referenced by bsl::basic_stringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rdbuf(), bsl::basic_ostringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rdbuf(), and bsl::basic_istringstream< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rdbuf().