BDE 2.16 BETA: bslstl_list Component
Quick Links:
bsl+bslhdrs | bsl+stdhdrs | bslalg | bsldoc | bslim | bslma | bslmf | bsls | bslscm | bslstl | bsltf
Component bslstl_list
[Package bslstl]
Provide an STL-compliant list class.
Classes
struct bsl::List_Node< VALUE >
class bsl::List_Iterator< VALUE, NODEPTR, DIFFTYPE >
class bsl::list< VALUE, ALLOCATOR >
struct bsl::list< VALUE, ALLOCATOR >::AllocAndSizeWrapper
class bsl::list< VALUE, ALLOCATOR >::NodeProctor
struct bsl::list< VALUE, ALLOCATOR >::Comp_Elems
Typedefs
typedef List_Node * bsl::List_Node::NodePtr
typedef
std::bidirectional_iterator_tag bsl::List_Iterator::iterator_category
typedef NcType bsl::List_Iterator::value_type
typedef DIFFTYPE bsl::List_Iterator::difference_type
typedef VALUE * bsl::List_Iterator::pointer
typedef VALUE & bsl::List_Iterator::reference
typedef VALUE & bsl::list::reference
typedef const VALUE & bsl::list::const_reference
typedef List_Iterator< VALUE,
NodePtr, DiffType > bsl::list::iterator
typedef List_Iterator< const
VALUE, NodePtr, DiffType > bsl::list::const_iterator
typedef allocator_traits
< ALLOCATOR >::pointer bsl::list::pointer
typedef allocator_traits
< ALLOCATOR >::const_pointer bsl::list::const_pointer
typedef AllocTraits::size_type bsl::list::size_type
typedef
AllocTraits::difference_type bsl::list::difference_type
typedef VALUE bsl::list::value_type
typedef ALLOCATOR bsl::list::allocator_type
typedef bsl::reverse_iterator
< iterator > bsl::list::reverse_iterator
typedef bsl::reverse_iterator
< const_iterator > bsl::list::const_reverse_iterator
Functions
void bsl::List_Node::init ()
void bsl::List_Node::destroy ()
bsl::List_Iterator::List_Iterator ()
bsl::List_Iterator::List_Iterator (NODEPTR p)
bsl::List_Iterator::List_Iterator (const NcIter &other)
bsl::List_Iterator::~List_Iterator ()
List_Iterator & bsl::List_Iterator::operator= (const List_Iterator &)
List_Iterator & bsl::List_Iterator::operator++ ()
List_Iterator & bsl::List_Iterator::operator-- ()
List_Iterator bsl::List_Iterator::operator++ (int)
List_Iterator bsl::List_Iterator::operator-- (int)
reference bsl::List_Iterator::operator* () const
pointer bsl::List_Iterator::operator-> () const
template<class T1 , class T2 , class NODEPTR , class DIFFTYPE >
bool bsl::operator== (List_Iterator< T1, NODEPTR, DIFFTYPE > lhs, List_Iterator< T2, NODEPTR, DIFFTYPE > rhs)
template<class T1 , class T2 , class NODEPTR , class DIFFTYPE >
bool bsl::operator!= (List_Iterator< T1, NODEPTR, DIFFTYPE > lhs, List_Iterator< T2, NODEPTR, DIFFTYPE > rhs)
bsl::list::AllocAndSizeWrapper::AllocAndSizeWrapper (const NodeAlloc &allocator, size_type size)
bsl::list::NodeProctor::NodeProctor (list *l, NodePtr p)
bsl::list::NodeProctor::~NodeProctor ()
void bsl::list::NodeProctor::release ()
bsl::list::BSLMF_NESTED_TRAIT_DECLARATION_IF (list, BloombergLP::bslmf::IsBitwiseMoveable, BloombergLP::bslmf::IsBitwiseMoveable< ALLOCATOR >::value)
bsl::list::BSLMF_NESTED_TRAIT_DECLARATION (list, BloombergLP::bslalg::HasStlIterators)
bsl::list::BSLMF_NESTED_TRAIT_DECLARATION_IF (list, BloombergLP::bslma::UsesBslmaAllocator,(is_convertible< BloombergLP::bslma::Allocator *, ALLOCATOR >::value))
bsl::list::list (const ALLOCATOR &allocator=ALLOCATOR())
bsl::list::list (size_type n)
bsl::list::list (size_type n, const VALUE &value, const ALLOCATOR &allocator=ALLOCATOR())
template<class InputIter >
bsl::list::list (InputIter first, InputIter last, const ALLOCATOR &allocator=ALLOCATOR(), typename enable_if< !is_fundamental< InputIter >::value &&!is_enum< InputIter >::value >::type *=0)
bsl::list::list (const list &original)
bsl::list::list (const list &original, const ALLOCATOR &allocator)
bsl::list::~list ()
list & bsl::list::operator= (const list &rhs)
template<class InputIter >
void bsl::list::assign (InputIter first, InputIter last, typename enable_if< !is_fundamental< InputIter >::value &&!is_enum< InputIter >::value >::type *=0)
void bsl::list::assign (size_type n, const VALUE &value)
iterator bsl::list::begin ()
iterator bsl::list::end ()
reverse_iterator bsl::list::rbegin ()
reverse_iterator bsl::list::rend ()
void bsl::list::resize (size_type sz)
void bsl::list::resize (size_type sz, const VALUE &c)
reference bsl::list::front ()
reference bsl::list::back ()
void bsl::list::emplace_front ()
template<class ARG1 >
void bsl::list::emplace_front (const ARG1 &a1)
template<class ARG1 , class ARG2 >
void bsl::list::emplace_front (const ARG1 &a1, const ARG2 &a2)
template<class ARG1 , class ARG2 , class ARG3 >
void bsl::list::emplace_front (const ARG1 &a1, const ARG2 &a2, const ARG3 &a3)
template<class ARG1 , class ARG2 , class ARG3 , class ARG4 >
void bsl::list::emplace_front (const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4)
template<class ARG1 , class ARG2 , class ARG3 , class ARG4 , class ARG5 >
void bsl::list::emplace_front (const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5)
void bsl::list::pop_front ()
void bsl::list::emplace_back ()
template<class ARG1 >
void bsl::list::emplace_back (const ARG1 &a1)
template<class ARG1 , class ARG2 >
void bsl::list::emplace_back (const ARG1 &a1, const ARG2 &a2)
template<class ARG1 , class ARG2 , class ARG3 >
void bsl::list::emplace_back (const ARG1 &a1, const ARG2 &a2, const ARG3 &a3)
template<class ARG1 , class ARG2 , class ARG3 , class ARG4 >
void bsl::list::emplace_back (const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4)
template<class ARG1 , class ARG2 , class ARG3 , class ARG4 , class ARG5 >
void bsl::list::emplace_back (const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5)
void bsl::list::pop_back ()
void bsl::list::push_front (const VALUE &value)
void bsl::list::push_back (const VALUE &vaule)
iterator bsl::list::emplace (const_iterator position)
template<class ARG1 >
iterator bsl::list::emplace (const_iterator position, const ARG1 &a1)
template<class ARG1 , class ARG2 >
iterator bsl::list::emplace (const_iterator position, const ARG1 &a1, const ARG2 &a2)
template<class ARG1 , class ARG2 , class ARG3 >
iterator bsl::list::emplace (const_iterator position, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3)
template<class ARG1 , class ARG2 , class ARG3 , class ARG4 >
iterator bsl::list::emplace (const_iterator position, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4)
template<class ARG1 , class ARG2 , class ARG3 , class ARG4 , class ARG5 >
iterator bsl::list::emplace (const_iterator position, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5)
iterator bsl::list::insert (const_iterator position, const VALUE &value)
iterator bsl::list::insert (const_iterator position, size_type n, const VALUE &value)
template<class InputIter >
iterator bsl::list::insert (const_iterator position, InputIter first, InputIter last, typename enable_if< !is_fundamental< InputIter >::value &&!is_enum< InputIter >::value >::type *=0)
iterator bsl::list::erase (const_iterator position)
iterator bsl::list::erase (const_iterator position, const_iterator last)
void bsl::list::swap (list &other)
void bsl::list::clear ()
void bsl::list::splice (const_iterator position, list &x)
void bsl::list::splice (const_iterator position, list &x, const_iterator i)
void bsl::list::splice (const_iterator position, list &x, const_iterator first, const_iterator last)
void bsl::list::remove (const VALUE &value)
template<class Predicate >
void bsl::list::remove_if (Predicate pred)
void bsl::list::unique ()
template<class EqPredicate >
void bsl::list::unique (EqPredicate binary_pred)
void bsl::list::merge (list &other)
template<class COMPARE >
void bsl::list::merge (list &other, COMPARE comp)
void bsl::list::sort ()
template<class COMPARE >
void bsl::list::sort (COMPARE comp)
void bsl::list::reverse ()
allocator_type bsl::list::get_allocator () const
const_iterator bsl::list::begin () const
const_iterator bsl::list::end () const
const_reverse_iterator bsl::list::rbegin () const
const_reverse_iterator bsl::list::rend () const
const_iterator bsl::list::cbegin () const
const_iterator bsl::list::cend () const
const_reverse_iterator bsl::list::crbegin () const
const_reverse_iterator bsl::list::crend () const
bool bsl::list::empty () const
size_type bsl::list::size () const
size_type bsl::list::max_size () const
const_reference bsl::list::front () const
const_reference bsl::list::back () const
template<class VALUE , class ALLOCATOR >
bool bsl::operator== (const list< VALUE, ALLOCATOR > &lhs, const list< VALUE, ALLOCATOR > &rhs)
template<class VALUE , class ALLOCATOR >
bool bsl::operator!= (const list< VALUE, ALLOCATOR > &lhs, const list< VALUE, ALLOCATOR > &rhs)
template<class VALUE , class ALLOCATOR >
bool bsl::operator< (const list< VALUE, ALLOCATOR > &lhs, const list< VALUE, ALLOCATOR > &rhs)
template<class VALUE , class ALLOCATOR >
bool bsl::operator> (const list< VALUE, ALLOCATOR > &lhs, const list< VALUE, ALLOCATOR > &rhs)
template<class VALUE , class ALLOCATOR >
bool bsl::operator<= (const list< VALUE, ALLOCATOR > &lhs, const list< VALUE, ALLOCATOR > &rhs)
template<class VALUE , class ALLOCATOR >
bool bsl::operator>= (const list< VALUE, ALLOCATOR > &lhs, const list< VALUE, ALLOCATOR > &rhs)
template<class VALUE , class ALLOCATOR >
void bsl::swap (list< VALUE, ALLOCATOR > &lhs, list< VALUE, ALLOCATOR > &rhs)
Variables
NodePtr bsl::List_Node::d_prev
NodePtr bsl::List_Node::d_next
VALUE bsl::List_Node::d_value
size_type bsl::list::AllocAndSizeWrapper::d_size
Friends
class bsl::List_Iterator::List_Iterator< const VALUE, NODEPTR, DIFFTYPE >
struct bsl::list::AllocAndSizeWrapper
class bsl::list::NodeProctor
template<class T1 , class T2 , class NODEP , class DIFFT >
bool bsl::List_Iterator::operator== (List_Iterator< T1, NODEP, DIFFT >, List_Iterator< T2, NODEP, DIFFT >)
Detailed Description
Outline
Purpose
Classes
Description
Memory Allocation
bslma-Style Allocators
Operations
Thread-Safety
Usage
Example 1: Filter "Twinkle Star"
Example 2: Combine Two Star Surveys
Purpose:
Provide an STL-compliant list class.
Classes:
bsl::list STL-compatible list template
See also:
Component bslstl_deque
Description:
This component defines a single class template, list, implementing the standard container holding a sequence of elements (of a template parameter type, VALUE). All list operations involving single element are constant-time, including insertion and removal of elements anywhere in the list. Operations that do not change the number of elements are performed without calling constructors, destructors, swap, or assignment on the individual elements. (I.e., they are performed by pointer-manipulation alone.) A list does not provide random access to its elements; although access to the first and last element of a list is constant-time, other elements can be accessed only by traversing the list (forwards or backwards) from the beginning or end.
An instantiation of list is an allocator-aware, in-core value-semantic type whose salient attributes are its size (number of elements) and the sequence of its contained element values (in order). If list is instantiated with a type that is not itself value-semantic, then it will not retain all of its value-semantic qualities. In particular, if a type cannot be tested for equality, then a list containing that type cannot be tested for equality. It is even possible to instantiate list with a type that does not have a copy-constructor, in which case the list will not be copyable.
A list meets the requirements of a sequence container with bidirectional iterators in the C++ standard [23.3]. The list implemented here adheres to the C++11 standard, except that it does not have interfaces that take rvalue references, initializer_list, emplace, or operations taking a variadic number of template parameters. Note that excluded C++11 features are those that require C++11 compiler support.
Memory Allocation:
The type supplied as a list's ALLOCATOR template parameter determines how that list will allocate memory. The list template supports allocators meeting the requirements of the C++11 standard [17.6.3.5], in addition it supports scoped-allocators derived from the bslma::Allocator memory allocation protocol. Clients intending to use bslma style allocators should use the template's default ALLOCATOR type: The default type for the ALLOCATOR template parameter, bsl::allocator, provides a C++11 standard-compatible adapter for a bslma::Allocator object.
bslma-Style Allocators:
If the parameterized ALLOCATOR type of an list instantiation is bsl::allocator, then objects of that list type will conform to the standard behavior of a bslma-allocator-enabled type. Such a list accepts an optional bslma::Allocator argument at construction. If the address of a bslma::Allocator object is explicitly supplied at construction, it will be used to supply memory for the list throughout its lifetime; otherwise, the list will use the default allocator installed at the time of the list's construction (see bslma_default). In addition to directly allocating memory from the indicated bslma::Allocator, a list supplies that allocator's address to the constructors of contained objects of the (template parameter) VALUE type, if respectively, the parameterized types define the bslma::UsesBslmaAllocator trait.
Operations:
This section describes the run-time complexity of operations on instances of list:
  Legend
  ------
  'V'             - parameterized 'VALUE' type of the list
  'a', 'b'        - two distinct objects of type 'list<V>'
  'n', 'm'        - number of elements in 'a' and 'b' respectively
  'value_type'    - list<V>::value_type
  'al'            - an STL-style memory allocator
  'i1', 'i2'      - two iterators defining a sequence of 'value_type' objects
  'v'             - an object of type 'V'
  'p1', 'p2'      - two iterators belonging to 'a'
  's1', 's2'      - two iterators belonging to 'b'
  'pred'          - a unary predicate
  'binary_pred'   - a binary predicate
  'comp'          - a binary predicate implementing a strict-weak ordering
  'args...'       - a variadic list of (up to 5) arguments
  distance(i1,i2) - the number of elements in the range [i1, i2)
  +----------------------------------------------------+--------------------+
  | Operation                                          | Complexity         |
  +====================================================+====================+
  | list<V> a;    (default construction)               | O(1)               |
  | list<V> a(al);                                     |                    |
  +----------------------------------------------------+--------------------+
  | list<V> a(b); (copy construction)                  | O(n)               |
  | list<V> a(b, al);                                  |                    |
  +----------------------------------------------------+--------------------+
  | list<V> a(n);                                      | O(n)               |
  | list<V> a(n, value_type(v));                       |                    |
  | list<V> a(n, value_type(v), al);                   |                    |
  +----------------------------------------------------+--------------------+
  | list<V> a(i1, i2);                                 | O(distance(i1,i2)) |
  | list<V> a(i1, i2, al);                             |                    |
  +----------------------------------------------------+--------------------+
  | a.~list<V>(); (destruction)                        | O(n)               |
  +----------------------------------------------------+--------------------+
  | a = b;        (assignment)                         | O(n)               |
  +----------------------------------------------------+--------------------+
  | a.begin(), a.end(), a.cbegin(), a.cend(),          | O(1)               |
  | a.rbegin(), a.rend(), a.crbegin(), a.crend()       |                    |
  +----------------------------------------------------+--------------------+
  | a == b, a != b                                     | O(n)               |
  +----------------------------------------------------+--------------------+
  | a < b, a <= b, a > b, a >= b                       | O(n)               |
  +----------------------------------------------------+--------------------+
  | a.swap(b), swap(a,b)                               | O(1) if 'a' and 'b'|
  |                                                    | use the same       |
  |                                                    | allocator,         |
  |                                                    | O[n + m] otherwise |
  +----------------------------------------------------+--------------------+
  | a.size()                                           | O(1)               |
  +----------------------------------------------------+--------------------+
  | a.max_size()                                       | O(1)               |
  +----------------------------------------------------+--------------------+
  | a.empty()                                          | O(1)               |
  +----------------------------------------------------+--------------------+
  | get_allocator()                                    | O(1)               |
  +----------------------------------------------------+--------------------+
  | a.emplace(p1, args...)                             | O(1)               |
  +----------------------------------------------------+--------------------+
  | a.insert(p1, value_type(v))                        | O(1)               |
  +----------------------------------------------------+--------------------+
  | a.insert(p1, n, value_type(v))                     | O(n)               |
  +----------------------------------------------------+--------------------+
  | a.insert(p1, i1, i2)                               | O(distance(i1, i2))|
  +----------------------------------------------------+--------------------+
  | a.erase(p1)                                        | O(1)               |
  +----------------------------------------------------+--------------------+
  | a.erase(p1, p2)                                    | O(distance(p1, p2))|
  +----------------------------------------------------+--------------------+
  | a.clear()                                          | O(n)               |
  +----------------------------------------------------+--------------------+
  | a.assign(i1,i2)                                    | O(distance(i1, i2))|
  +----------------------------------------------------+--------------------+
  | a.assign(n, value_type(v))                         | O(n)               |
  +----------------------------------------------------+--------------------+
  | a.front(), a.back()                                | O(1)               |
  +----------------------------------------------------+--------------------+
  | a.emplace_front(args...), a.emplace_back(args...)  | O(1)               |
  +----------------------------------------------------+--------------------+
  | a.push_front(value_type(v)),                       |                    |
  | a.push_back(value_type(v))                         | O(1)               |
  +----------------------------------------------------+--------------------+
  | a.pop_front(), a.pop_back()                        | O(1)               |
  +----------------------------------------------------+--------------------+
  | a.resize(n), a.resize(n, value_type(v))            | O(n)               |
  +----------------------------------------------------+--------------------+
  | a.splice(p, b), a.splice(p, b, s1)                 | O(1)               |
  +----------------------------------------------------+--------------------+
  | a.splice(p, b, s1, s2)                             | O(distance(s1, s2))|
  +----------------------------------------------------+--------------------+
  | a.remove(t), a.remove_if(pred)                     | O(n)               |
  +----------------------------------------------------+--------------------+
  | a.unique(), a.unique(binary_pred)                  | O(n)               |
  +----------------------------------------------------+--------------------+
  | a.merge(b), a.merge(b, comp)                       | O(n)               |
  +----------------------------------------------------+--------------------+
  | a.sort(), a.sort(comp)                             | O(n*log(n))        |
  +----------------------------------------------------+--------------------+
  | a.reverse()                                        | O(n)               |
  +----------------------------------------------------+--------------------+
Thread-Safety:
list is const Thread-Safe [TS.2] (see bsldoc_glossary). Separate threads can safely access and modify separate list objects. Separate threads can safely perform const operations on a single list object. Separate threads cannot safely perform operations on a single list object if at least one of those operations modifies the list. If an iterator or reference to a list element is obtained in one thread, it may become invalidated if the list is modified in the same or another thread, even if the iterator is a const_iterator or the reference is a reference-to-'const'.
Usage:
This section illustrates intended usage of this component.
Example 1: Filter "Twinkle Star":
Suppose an observatory needs to analyze the results of a sky survey. The raw data is a text file of star observations where each star is represented by a tuple of three numbers: (x, y, b), where x and y represent the angular coordinates of the star in the sky and b represents its brightness on a scale of 0 to 100. A star having brightness 75 or higher is of particular interest, which is called "twinkle star".
Our first example will read such a data file as described above, filter out the dim stars (brightness less than 75), and count the twinkle stars left in the list. Our test data set has been selected such that there are 10 stars in the set, of which 4 are sufficiently bright as to pass our filter.
First, we define the class Star that encapsulates a single tuple, and provides accessors functions x, y, and brightness, file I/O functions read and write, and free operators ==, !=, and <:
  #include <cstdio>
  using namespace std;
  class Star
      // This class represents a star as seen through a digital telescope.
  {
      // DATA
      double d_x, d_y;     // coordinates
      int    d_brightness; // brightness on a scale of 0 to 100
  public:
      // CREATORS
      Star()
          // Create a 'Star' object located at coordinates '(0, 0)' having
          // '0' brightness.
      : d_x(0), d_y(0), d_brightness(0)
      {
      }
      Star(double x, double y, int b)
          // Create a 'Star' object located at the specified coordinates
          // '(x, y)' having the specified 'b' brightness.
      : d_x(x), d_y(y), d_brightness(b)
      {
      }
      // Compiler-generated copy construction, assignment, and destructor
      // Star(const Star&) = default;
      // Star& operator=(const Star&) = default;
      // ~Star() = default;
      // MANIPULATORS
      bool read(FILE *input);
          // Read x, y, and brightness from the specified 'input' file.
          // Return 'true' if the read succeeded and 'false' otherwise.
      void write(FILE *output) const;
          // Write x, y, and brightness to the specified 'output' file
          // followed by a newline.
      // ACCESSORS
      double x() const
          // Return the x coordinate of this 'Star' object.
      {
          return d_x;
      }
      double y() const
          // Return the y coordinate of this 'Star' object.
      {
          return d_y;
      }
      int brightness() const
          // Return the brightness of this 'Star' object.
      {
          return d_brightness;
      }
  };
  // FREE FUNCTIONS
  bool operator==(const Star& lhs, const Star& rhs);
  bool operator!=(const Star& lhs, const Star& rhs);
  bool operator< (const Star& lhs, const Star& rhs);
Then, we define a readData method that reads a file of data points and appends each onto a list. The stars are stored in the data file in ascending sorted order by x and y coordinates.
  void readData(list<Star> *starList, FILE *input)
  {
      Star s;
      while (s.read(input)) {
          starList->push_back(s);
      }
  }
Now, we define the filter method, which is responsible for removing stars with a brightness of less than 75 from the data set. It does this by iterating over the list and erasing any element that does not pass the filter. The list object features a fast erase member function. The return value of erase is an iterator to the element immediately following the erased element:
  void filter(list<Star> *starList)
  {
      static const int threshold = 75;
      list<Star>::iterator i = starList->begin();
      while (i != starList->end()) {
          if (i->brightness() < threshold) {
              i = starList->erase(i);  // Erase and advance to next element.
          }
          else {
              ++i;  // Advance to next element without erasing
          }
      }
  }
Finally, we use the methods defined in above steps to put together our program to find twinkle stars:
  int usageExample1(int verbose)
  {
      FILE *input = fopen("star_data1.txt", "r");  // Open input file.
      assert(input);
      list<Star> starList;                         // Define a list of stars.
      assert(starList.empty());                    // A list should be empty
                                                   // after default
                                                   // construction.
      readData(&starList, input);                  // Read input to the list.
      assert(10 == starList.size());               // Verify correct reading.
      fclose(input);                               // Close input file.
      filter(&starList);                           // Pick twinkle stars.
      assert(4 == starList.size());                // Verify correct filter.
      // Print out twinkle stars.
      if (verbose) {
          for (list<Star>::const_iterator i = starList.begin();
               i != starList.end(); ++i) {
              i->write(stdout);
          }
      }
      return 0;
  }
Example 2: Combine Two Star Surveys:
In the second example, we want to combine the results from two star surveys into a single list, using the same Star class defined in the first usage example.
First, we begin by reading both lists and filtering them. (Our test data is selected so that the second data file contains 8 stars of which 3 are sufficiently bright as to pass our filter:
  int usageExample2(int verbose)
  {
      FILE *input = fopen("star_data1.txt", "r");  // Open first input file.
      assert(input);
      list<Star> starList1;                        // Define first star list.
      assert(starList1.empty());
      readData(&starList1, input);                 // Read input into list.
      assert(10 == starList1.size());
      fclose(input);                               // Close first input file.
      input = fopen("star_data2.txt", "r");        // Open second input file.
      assert(input);
      list<Star> starList2;                        // Define second list.
      assert(starList2.empty());
      readData(&starList2, input);                 // Read input into list.
      assert(8 == starList2.size());
      fclose(input);                               // Close input file.
      filter(&starList1);                          // Pick twinkle stars from
                                                   // the first star list.
      assert(4 == starList1.size());
      filter(&starList2);                          // Pick twinkle stars from
                                                   // the second star list.
      assert(3 == starList2.size());
Then, we combine the two lists, starList1 and starList2. One way to do this is to simply insert the second list at the end of the first:
      list<Star> tmp1(starList1);  // Make a copy of the first list
      list<Star> tmp2(starList2);  // Make a copy of the second list
      tmp1.insert(tmp1.end(), tmp2.begin(), tmp2.end());
      assert(7 == tmp1.size());    // Verify combined size.
      assert(3 == tmp2.size());    // 'tmp2' should be unchanged.
Next, let's have a closer look of the above code and see if we can improve the combination performance. The above insert method appends a copy of each element in tmp2 onto the end of tmp1. This copy is unnecessary because we have no need for tmp2 after the lists have been combined. A faster and less-memory-intensive technique is to use the splice function, which moves rather than copies elements from one list to another:
      tmp1 = starList1;
      tmp2 = starList2;
      tmp1.splice(tmp1.begin(), tmp2);
      assert(7 == tmp1.size());    // Verify combined size.
      assert(0 == tmp2.size());    // 'tmp2' should be emptied by the splice.
Notice that, while the original lists were sorted in ascending order (because the data files were originally sorted), the combined list is no longer sorted. To fix it, we sort tmp1 using the sort member function:
      tmp1.sort();
Then, we suggest a third, and also the best approach to combine two lists, which is to take advantage of the fact that the lists were originally sorted, using the merge function:
      starList1.merge(starList2);     // Merge 'starList2' into 'starList1'.
      assert(7 == starList1.size());  // Verify combined size.
      assert(0 == starList2.size());  // starList2 should be emptied by the
                                      // merge.
Now, since the two star surveys may overlap, we want to eliminate duplicates. We accomplish this by using the unique member function:
      starList1.unique();             // Eliminate duplicates in 'starList1'.
      assert(6 == starList1.size());  // Verify size after elimination.
Finally, we print the result:
      if (verbose) {
          for (list<Star>::const_iterator i = starList1.begin();
               i != starList1.end(); ++i) {
              i->write(stdout);
          }
      }
      return 0;
  }
For completeness, the implementations of the read, write, and comparison functions for class Star are shown below:
  bool Star::read(FILE *input)
  {
      int ret = fscanf(input, "%lf %lf %d", &d_x, &d_y, &d_brightness);
      return 3 == ret;
  }
  void Star::write(FILE *output) const
  {
      fprintf(output, "%f %f %d\n", d_x, d_y, d_brightness);
  }
  bool operator==(const Star& lhs, const Star& rhs)
  {
      return lhs.x() == rhs.x()
          && lhs.y() == rhs.y()
          && lhs.brightness() == rhs.brightness();
  }
  bool operator!=(const Star& lhs, const Star& rhs)
  {
      return ! (lhs == rhs);
  }
  bool operator<(const Star& lhs, const Star& rhs)
  {
      if (lhs.x() < rhs.x())
          return true;
      else if (rhs.x() < lhs.x())
          return false;
      else if (lhs.y() < rhs.y())
          return true;
      else if (rhs.y() < lhs.y())
          return true;
      else
          return lhs.brightness() < rhs.brightness();
  }
Typedef Documentation
template<class VALUE > typedef List_Node* bsl::List_Node< VALUE >::NodePtr [inherited]
template<class VALUE, class NODEPTR, class DIFFTYPE> typedef std::bidirectional_iterator_tag bsl::List_Iterator< VALUE, NODEPTR, DIFFTYPE >::iterator_category [inherited]
template<class VALUE, class NODEPTR, class DIFFTYPE> typedef NcType bsl::List_Iterator< VALUE, NODEPTR, DIFFTYPE >::value_type [inherited]
template<class VALUE, class NODEPTR, class DIFFTYPE> typedef DIFFTYPE bsl::List_Iterator< VALUE, NODEPTR, DIFFTYPE >::difference_type [inherited]
template<class VALUE, class NODEPTR, class DIFFTYPE> typedef VALUE* bsl::List_Iterator< VALUE, NODEPTR, DIFFTYPE >::pointer [inherited]
template<class VALUE, class NODEPTR, class DIFFTYPE> typedef VALUE& bsl::List_Iterator< VALUE, NODEPTR, DIFFTYPE >::reference [inherited]
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> typedef VALUE& bsl::list< VALUE, ALLOCATOR >::reference [inherited]
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> typedef const VALUE& bsl::list< VALUE, ALLOCATOR >::const_reference [inherited]
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> typedef List_Iterator<VALUE,NodePtr,DiffType> bsl::list< VALUE, ALLOCATOR >::iterator [inherited]
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> typedef List_Iterator<const VALUE,NodePtr,DiffType> bsl::list< VALUE, ALLOCATOR >::const_iterator [inherited]
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> typedef allocator_traits<ALLOCATOR>::pointer bsl::list< VALUE, ALLOCATOR >::pointer [inherited]
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> typedef allocator_traits<ALLOCATOR>::const_pointer bsl::list< VALUE, ALLOCATOR >::const_pointer [inherited]
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> typedef AllocTraits::size_type bsl::list< VALUE, ALLOCATOR >::size_type [inherited]
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> typedef AllocTraits::difference_type bsl::list< VALUE, ALLOCATOR >::difference_type [inherited]
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> typedef VALUE bsl::list< VALUE, ALLOCATOR >::value_type [inherited]
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> typedef ALLOCATOR bsl::list< VALUE, ALLOCATOR >::allocator_type [inherited]
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> typedef bsl::reverse_iterator<iterator> bsl::list< VALUE, ALLOCATOR >::reverse_iterator [inherited]
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> typedef bsl::reverse_iterator<const_iterator> bsl::list< VALUE, ALLOCATOR >::const_reverse_iterator [inherited]
Function Documentation
template<class VALUE > void bsl::List_Node< VALUE >::init () [inherited]
Value-initialize the d_prev and d_next members of this node, but do not touch d_value. The behavior is undefined unless this points to allocated (uninitialized) storage'. Note: d_value continues to hold uninitialized storage after this call.
template<class VALUE > void bsl::List_Node< VALUE >::destroy () [inherited]
Release the d_prev and d_next members of this node but do not touch d_value. After calling destroy, this points to allocated (uninitialized) storage. The behavior is undefined unless d_prev and d_next have valid values and d_value holds allocated (uninitialized) storage.
template<class VALUE, class NODEPTR, class DIFFTYPE> bsl::List_Iterator< VALUE, NODEPTR, DIFFTYPE >::List_Iterator () [inherited]
Create a singular iterator (i.e., one that cannot be incremented, decremented, or dereferenced.
template<class VALUE, class NODEPTR, class DIFFTYPE> bsl::List_Iterator< VALUE, NODEPTR, DIFFTYPE >::List_Iterator (NODEPTR p) [explicit, inherited]
Create an iterator that references the value pointed to by the specified pointer p.
template<class VALUE, class NODEPTR, class DIFFTYPE> bsl::List_Iterator< VALUE, NODEPTR, DIFFTYPE >::List_Iterator (const NcIter & other) [inherited]
Create an iterator to VALUE from the corresponding iterator to non-const VALUE. If VALUE is not const-qualified, then this constructor becomes the copy constructor. Otherwise, the copy constructor is implicitly generated.
template<class VALUE, class NODEPTR, class DIFFTYPE> bsl::List_Iterator< VALUE, NODEPTR, DIFFTYPE >::~List_Iterator () [inherited]
template<class VALUE, class NODEPTR, class DIFFTYPE> List_Iterator& bsl::List_Iterator< VALUE, NODEPTR, DIFFTYPE >::operator= (const List_Iterator< VALUE, NODEPTR, DIFFTYPE > &) [inherited]
template<class VALUE, class NODEPTR, class DIFFTYPE> List_Iterator& bsl::List_Iterator< VALUE, NODEPTR, DIFFTYPE >::operator++ () [inherited]
Advance this iterator to the next element in this list and return its new value. The behavior is undefined unless this iterator is in the range [ begin(), end()) for some list (i.e., the iterator is not singular, is not end() and has not be invalidated).
template<class VALUE, class NODEPTR, class DIFFTYPE> List_Iterator& bsl::List_Iterator< VALUE, NODEPTR, DIFFTYPE >::operator-- () [inherited]
Move this iterator to the previous element in this list and return its new value. The behavior is undefined unless this iterator is in the range (begin(), end() ] for some list (i.e., the iterator is not singular, is not begin() and has not be invalidated).
template<class VALUE, class NODEPTR, class DIFFTYPE> List_Iterator bsl::List_Iterator< VALUE, NODEPTR, DIFFTYPE >::operator++ (int) [inherited]
Advance this iterator to the next element in this list and return its previous value. The behavior is undefined unless this iterator is in the range [ begin(), end()) for some list (i.e., the iterator is not singular, is not end() and has not be invalidated).
template<class VALUE, class NODEPTR, class DIFFTYPE> List_Iterator bsl::List_Iterator< VALUE, NODEPTR, DIFFTYPE >::operator-- (int) [inherited]
Move this iterator to the previous element in this list and return its previous value. The behavior is undefined unless this iterator is in the range (begin(), end() ] for some list (i.e., the iterator is not singular, is not begin() and has not be invalidated).
template<class VALUE, class NODEPTR, class DIFFTYPE> reference bsl::List_Iterator< VALUE, NODEPTR, DIFFTYPE >::operator* () const [inherited]
Return a reference to this list object referenced by this iterator. The behavior is undefined unless this iterator is in the range [ begin(), end()) for some list (i.e., the iterator is not singular, is not end() and has not be invalidated).
template<class VALUE, class NODEPTR, class DIFFTYPE> pointer bsl::List_Iterator< VALUE, NODEPTR, DIFFTYPE >::operator-> () const [inherited]
Return a pointer to this list object referenced by this iterator. The behavior is undefined unless this iterator is in the range [ begin(), end()) for some list (i.e., the iterator is not singular, is not end() and has not be invalidated).
template<class T1 , class T2 , class NODEPTR , class DIFFTYPE > bool bsl::operator== (List_Iterator< T1, NODEPTR, DIFFTYPE > lhs, List_Iterator< T2, NODEPTR, DIFFTYPE > rhs)
Return true if the specified iterators lhs and rhs have the same value and false otherwise. Two iterators have the same value if both refer to the same element of the same list or both are the end() iterator of the same list. The return value is undefined unless both lhs and rhs are non-singular.
template<class T1 , class T2 , class NODEPTR , class DIFFTYPE > bool bsl::operator!= (List_Iterator< T1, NODEPTR, DIFFTYPE > lhs, List_Iterator< T2, NODEPTR, DIFFTYPE > rhs)
Return true if the specified iterators lhs and rhs do not have the same value and false otherwise. Two iterators have the same value if both refer to the same element of the same list or both are the end() iterator of the same list. The return value is undefined unless both lhs and rhs are non-singular.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> bsl::list< VALUE, ALLOCATOR >::AllocAndSizeWrapper::AllocAndSizeWrapper (const NodeAlloc & allocator, size_type size) [inline, explicit, inherited]
< Create an allocator wrapper having the specified allocator type allocator and the specified allocated size.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> bsl::list< VALUE, ALLOCATOR >::NodeProctor::NodeProctor (list * l, NodePtr p) [inline, explicit, inherited]
Parameters:
p Create a node proctor object that will use the specified list l to free the specified node p.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> bsl::list< VALUE, ALLOCATOR >::NodeProctor::~NodeProctor () [inline, inherited]
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> void bsl::list< VALUE, ALLOCATOR >::NodeProctor::release () [inline, inherited]
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> bsl::list< VALUE, ALLOCATOR >::BSLMF_NESTED_TRAIT_DECLARATION_IF (list< VALUE, ALLOCATOR > , BloombergLP::bslmf::IsBitwiseMoveable , BloombergLP::bslmf::IsBitwiseMoveable< ALLOCATOR >::value) [inherited]
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> bsl::list< VALUE, ALLOCATOR >::BSLMF_NESTED_TRAIT_DECLARATION (list< VALUE, ALLOCATOR > , BloombergLP::bslalg::HasStlIterators) [inherited]
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> bsl::list< VALUE, ALLOCATOR >::BSLMF_NESTED_TRAIT_DECLARATION_IF (list< VALUE, ALLOCATOR > , BloombergLP::bslma::UsesBslmaAllocator , (is_convertible< BloombergLP::bslma::Allocator *, ALLOCATOR >::value)) [inherited]
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> bsl::list< VALUE, ALLOCATOR >::list (const ALLOCATOR & allocator = ALLOCATOR()) [explicit, inherited]
Create an empty list that allocates memory using the specified allocator.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> bsl::list< VALUE, ALLOCATOR >::list (size_type n) [explicit, inherited]
Create a list containing the specified n elements and using a default-constructed allocator. The initial elements in this list are constructed by "default-insertion".
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> bsl::list< VALUE, ALLOCATOR >::list (size_type n, const VALUE & value, const ALLOCATOR & allocator = ALLOCATOR()) [inherited]
Create a list using the specified allocator and insert the specified n number of elements created by "copy-insertion" from value.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class InputIter > bsl::list< VALUE, ALLOCATOR >::list (InputIter first, InputIter last, const ALLOCATOR & allocator = ALLOCATOR(), typename enable_if< !is_fundamental< InputIter >::value &&!is_enum< InputIter >::value >::type * = 0) [inline, inherited]
References bsl::list< VALUE, ALLOCATOR >::begin(), and bsl::list< VALUE, ALLOCATOR >::insert().
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> bsl::list< VALUE, ALLOCATOR >::list (const list< VALUE, ALLOCATOR > & original) [inherited]
Create a list having the same value as that of the specified original. If ALLOCATOR is convertible from bslma_Allocator*, then the resulting list will use the default allocator; otherwise, the resulting list will use a copy of original.get_allocator(). Each element in the resulting list is constructed by "copy-insertion" from the corresponding element in original.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> bsl::list< VALUE, ALLOCATOR >::list (const list< VALUE, ALLOCATOR > & original, const ALLOCATOR & allocator) [inherited]
Create a list having the same value as that of the specified original that will use the specified allocator to supply memory. Each element in the resulting list is constructed by "copy-insertion" from the corresponding element in allocator.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> bsl::list< VALUE, ALLOCATOR >::~list () [inherited]
Destroy this list by calling the destructor for each element and deallocating all allocated storage.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> list& bsl::list< VALUE, ALLOCATOR >::operator= (const list< VALUE, ALLOCATOR > & rhs) [inherited]
Assign to this list the value of the specified list rhs, and return a reference providing modifiable access to this list. Each element of this list is either copy-assigned or copy-inserted from the corresponding element of rhs.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class InputIter > void bsl::list< VALUE, ALLOCATOR >::assign (InputIter first, InputIter last, typename enable_if< !is_fundamental< InputIter >::value &&!is_enum< InputIter >::value >::type * = 0) [inline, inherited]
References bsl::list< VALUE, ALLOCATOR >::begin(), bsl::list< VALUE, ALLOCATOR >::emplace(), bsl::list< VALUE, ALLOCATOR >::end(), and bsl::list< VALUE, ALLOCATOR >::erase().
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> void bsl::list< VALUE, ALLOCATOR >::assign (size_type n, const VALUE & value) [inherited]
Replace the contents of this list with the specified n copies of the specified value. Each element in this list is set by either copy-assignment or "copy-insertion" from value.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> iterator bsl::list< VALUE, ALLOCATOR >::begin () [inherited]
Return a mutating iterator referring to the first element in the list, if any, or one past the end of this list if this list is empty.
Referenced by bsl::list< VALUE, ALLOCATOR >::assign(), and bsl::list< VALUE, ALLOCATOR >::list().
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> iterator bsl::list< VALUE, ALLOCATOR >::end () [inherited]
Return a mutating iterator referring to one past the end of this list.
Referenced by bsl::list< VALUE, ALLOCATOR >::assign().
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> reverse_iterator bsl::list< VALUE, ALLOCATOR >::rbegin () [inherited]
Return a mutating reverse iterator referring to the last element of this list (i.e., the first element of the reverse sequence), if any, or one before the start if this list is empty.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> reverse_iterator bsl::list< VALUE, ALLOCATOR >::rend () [inherited]
Return a mutating reverse iterator referring to one before the start of this list.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> void bsl::list< VALUE, ALLOCATOR >::resize (size_type sz) [inherited]
Resize this list to the specified sz elements. If sz is less than or equal to the previous size of this list, then erase the excess elements from the end. Otherwise, append additional elements to the end using "default-insertion" until there are a total of sz elements.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> void bsl::list< VALUE, ALLOCATOR >::resize (size_type sz, const VALUE & c) [inherited]
Resize this list to the specified sz elements, with added elements being copies of the specified value c. If sz is less than or equal to the previous size of this list, then erase the excess elements from the end. Otherwise, append additional elements to the end using "copy-insertion" from c until there are a total of sz elements.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> reference bsl::list< VALUE, ALLOCATOR >::front () [inherited]
Return a reference providing modifiable access to the first element of this list. The behavior is undefined unless this list contains at least one element.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> reference bsl::list< VALUE, ALLOCATOR >::back () [inherited]
Return a reference providing modifiable access to the last element of this list. The behavior is undefined unless this list contains at least one element.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> void bsl::list< VALUE, ALLOCATOR >::emplace_front () [inherited]
Insert a new element at the front of this list and construct it using "default-insertion".
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class ARG1 > void bsl::list< VALUE, ALLOCATOR >::emplace_front (const ARG1 & a1) [inherited]
Insert a new element at the front of this list and construct it using "emplace-construction" from the specified argument a1.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class ARG1 , class ARG2 > void bsl::list< VALUE, ALLOCATOR >::emplace_front (const ARG1 & a1, const ARG2 & a2) [inherited]
Insert a new element at the front of this list and construct it using "emplace-construction" from the specified arguments a1 and a2.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class ARG1 , class ARG2 , class ARG3 > void bsl::list< VALUE, ALLOCATOR >::emplace_front (const ARG1 & a1, const ARG2 & a2, const ARG3 & a3) [inherited]
Insert a new element at the front of this list and construct it using "emplace-construction" from the specified arguments a1, a2, and a3.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class ARG1 , class ARG2 , class ARG3 , class ARG4 > void bsl::list< VALUE, ALLOCATOR >::emplace_front (const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4) [inherited]
Insert a new element at the front of this list and construct it using "emplace-construction" from the specified arguments a1, a2, a3, and a4.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class ARG1 , class ARG2 , class ARG3 , class ARG4 , class ARG5 > void bsl::list< VALUE, ALLOCATOR >::emplace_front (const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5) [inherited]
Insert a new element at the front of this list and construct it using "emplace-construction" from the specified arguments a1, a2, a3, a4, and a5.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> void bsl::list< VALUE, ALLOCATOR >::pop_front () [inherited]
Remove and destroy the first element of this list. The behavior is undefined unless this list contains at least one element.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> void bsl::list< VALUE, ALLOCATOR >::emplace_back () [inherited]
Insert a new element at the back of this list and construct it using "default-insertion".
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class ARG1 > void bsl::list< VALUE, ALLOCATOR >::emplace_back (const ARG1 & a1) [inherited]
Insert a new element at the back of this list and construct it using "emplace-construction" from the specified argument a1.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class ARG1 , class ARG2 > void bsl::list< VALUE, ALLOCATOR >::emplace_back (const ARG1 & a1, const ARG2 & a2) [inherited]
Insert a new element at the back of this list and construct it using "emplace-construction" from the specified arguments a1 and a2.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class ARG1 , class ARG2 , class ARG3 > void bsl::list< VALUE, ALLOCATOR >::emplace_back (const ARG1 & a1, const ARG2 & a2, const ARG3 & a3) [inherited]
Insert a new element at the back of this list and construct it using "emplace-construction" from the specified arguments a1, a2, and a3.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class ARG1 , class ARG2 , class ARG3 , class ARG4 > void bsl::list< VALUE, ALLOCATOR >::emplace_back (const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4) [inherited]
Insert a new element at the back of this list and construct it using "emplace-construction" from the specified arguments a1, a2, a3, and a4.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class ARG1 , class ARG2 , class ARG3 , class ARG4 , class ARG5 > void bsl::list< VALUE, ALLOCATOR >::emplace_back (const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5) [inherited]
Insert a new element at the back of this list and construct it using "emplace-construction" from the specified arguments a1, a2, a3, a4, and a5.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> void bsl::list< VALUE, ALLOCATOR >::pop_back () [inherited]
Remove and destroy the last element of this list. The behavior is undefined unless this list contains at least one element.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> void bsl::list< VALUE, ALLOCATOR >::push_front (const VALUE & value) [inherited]
Insert a new element at the front of this list using "copy-insertion" from the specified value value.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> void bsl::list< VALUE, ALLOCATOR >::push_back (const VALUE & vaule) [inherited]
Append a new element to the end of this list using "copy-insertion" from the specified value value.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> iterator bsl::list< VALUE, ALLOCATOR >::emplace (const_iterator position) [inherited]
Insert a new element into this list before the element at the specified position using "default-insertion".
Referenced by bsl::list< VALUE, ALLOCATOR >::assign().
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class ARG1 > iterator bsl::list< VALUE, ALLOCATOR >::emplace (const_iterator position, const ARG1 & a1) [inherited]
Insert a new element into this list before the element at the specified position using "emplace-construction" from the specified argument a1.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class ARG1 , class ARG2 > iterator bsl::list< VALUE, ALLOCATOR >::emplace (const_iterator position, const ARG1 & a1, const ARG2 & a2) [inherited]
Insert a new element into this list before the element at the specified position using "emplace-construction" from the specified arguments a1 and a2.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class ARG1 , class ARG2 , class ARG3 > iterator bsl::list< VALUE, ALLOCATOR >::emplace (const_iterator position, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3) [inherited]
Insert a new element into this list before the element at the specified position using "emplace-construction" from the specified arguments a1, a2, and a3.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class ARG1 , class ARG2 , class ARG3 , class ARG4 > iterator bsl::list< VALUE, ALLOCATOR >::emplace (const_iterator position, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4) [inherited]
Insert a new element into this list before the element at the specified position using "emplace-construction" from the specified arguments a1, a2, a3, and a4.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class ARG1 , class ARG2 , class ARG3 , class ARG4 , class ARG5 > iterator bsl::list< VALUE, ALLOCATOR >::emplace (const_iterator position, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5) [inherited]
Insert a new element into this list before the element at the specified position using "emplace-construction" from the specified arguments a1, a2, a3, a4, and a5.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> iterator bsl::list< VALUE, ALLOCATOR >::insert (const_iterator position, const VALUE & value) [inherited]
Insert into this list a copy of the specified value before the element at the specified position of this list. The newly inserted elements in this list is copy-constructed from value.
Referenced by bsl::list< VALUE, ALLOCATOR >::insert(), and bsl::list< VALUE, ALLOCATOR >::list().
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> iterator bsl::list< VALUE, ALLOCATOR >::insert (const_iterator position, size_type n, const VALUE & value) [inherited]
Insert into this list the specified n copies of the specified value before the element at the specified position of this list. Each of the n newly inserted elements in this list is copy-constructed from value.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class InputIter > iterator bsl::list< VALUE, ALLOCATOR >::insert (const_iterator position, InputIter first, InputIter last, typename enable_if< !is_fundamental< InputIter >::value &&!is_enum< InputIter >::value >::type * = 0) [inline, inherited]
References bsl::list< VALUE, ALLOCATOR >::insert().
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> iterator bsl::list< VALUE, ALLOCATOR >::erase (const_iterator position) [inherited]
Remove from this list the element at the specified position, and return an iterator referring to the element immediately following the removed element, or to the position returned by the end method if the removed element was the last in the sequence. The behavior is undefined unless position is an iterator in the range [ begin(), end()).
Referenced by bsl::list< VALUE, ALLOCATOR >::assign().
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> iterator bsl::list< VALUE, ALLOCATOR >::erase (const_iterator position, const_iterator last) [inherited]
Remove from this list the elements starting at the specified first position that are before the specified last position, and return an iterator referring to the element immediately following the last removed element, or the position returned by the method end if the removed elements were last in the sequence. The behavior is undefined unless first is an iterator in the range [ begin(), end() ] and last is an iterator in the range [ first, end() ] (both endpoints included).
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> void bsl::list< VALUE, ALLOCATOR >::swap (list< VALUE, ALLOCATOR > & other) [inherited]
Exchange the value of this list with that of the specified other list, such that each list has, upon return, the value of the other list prior to this call. This method does not throw or invalidate iterators if get_allocator, invoked on this list and other, returns the same value.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> void bsl::list< VALUE, ALLOCATOR >::clear () [inherited]
Remove all the elements from this list.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> void bsl::list< VALUE, ALLOCATOR >::splice (const_iterator position, list< VALUE, ALLOCATOR > & x) [inherited]
Insert elements of the specified list x before the element at the specified position of this list, and remove those elements from x. The behavior is undefined unless x is not this list.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> void bsl::list< VALUE, ALLOCATOR >::splice (const_iterator position, list< VALUE, ALLOCATOR > & x, const_iterator i) [inherited]
Insert the element at the specified i position before the element at the specified position of this list, and remove this element from the specified list x. The behavior is undefined unless i refers to a valid element in x.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> void bsl::list< VALUE, ALLOCATOR >::splice (const_iterator position, list< VALUE, ALLOCATOR > & x, const_iterator first, const_iterator last) [inherited]
Insert the elements starting at the specified first position and before the specified last position into this list, right before the element at the specified position, and remove those elements from the specified list x. The behavior is undefined unless [first, last) represents a range of valid elements in x, and position is not in the range [first, last).
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> void bsl::list< VALUE, ALLOCATOR >::remove (const VALUE & value) [inherited]
Erase all the elements having the specified value from this list.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class Predicate > void bsl::list< VALUE, ALLOCATOR >::remove_if (Predicate pred) [inherited]
Erase from this list all the elements that are not predicted false by the specified predicate pred.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> void bsl::list< VALUE, ALLOCATOR >::unique () [inherited]
Erase from this list all but the first element of every consecutive group of elements that have the same value.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class EqPredicate > void bsl::list< VALUE, ALLOCATOR >::unique (EqPredicate binary_pred) [inherited]
Erase from this list all but the first element of every consecutive group of elements that have the specified binary_pred predicates true for any two consecutive elements in the group.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> void bsl::list< VALUE, ALLOCATOR >::merge (list< VALUE, ALLOCATOR > & other) [inherited]
Merge the specified sorted list other into this sorted list. The method has no effect if other is this list. The behavior is undefined unless both other and this list are sorted in non-decreasing order according to the ordering returned by operator<.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class COMPARE > void bsl::list< VALUE, ALLOCATOR >::merge (list< VALUE, ALLOCATOR > & other, COMPARE comp) [inherited]
Merge the specified sorted list other into this sorted list, using the specified comp, which defines a strict weak ordering, to order elements. The method has no effect if other is this list. The behavior is undefined unless both other and this list are sorted in non-decreasing order according to the ordering returned by comp.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> void bsl::list< VALUE, ALLOCATOR >::sort () [inherited]
Sort this list in non-decreasing order according to the orders returned by operator<.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> template<class COMPARE > void bsl::list< VALUE, ALLOCATOR >::sort (COMPARE comp) [inherited]
Sort this list in non-decreasing order according to the orders returned by the specified comp comparator.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> void bsl::list< VALUE, ALLOCATOR >::reverse () [inherited]
Reverse the order of the elements in this list.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> allocator_type bsl::list< VALUE, ALLOCATOR >::get_allocator () const [inherited]
Return a copy of the allocator used for memory allocation by this list.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> const_iterator bsl::list< VALUE, ALLOCATOR >::begin () const [inherited]
Return a non-mutating iterator referring to the first element in the list, if any, or one past the end of this list if this list is empty.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> const_iterator bsl::list< VALUE, ALLOCATOR >::end () const [inherited]
Return a non-mutating iterator referring to one past the end of this list.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> const_reverse_iterator bsl::list< VALUE, ALLOCATOR >::rbegin () const [inherited]
Return a const reverse iterator referring to the last element of this list (i.e., the first element of the reverse sequence), if any, or one before the start if this list is empty.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> const_reverse_iterator bsl::list< VALUE, ALLOCATOR >::rend () const [inherited]
Return a const reverse iterator referring to one before the start of this list.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> const_iterator bsl::list< VALUE, ALLOCATOR >::cbegin () const [inherited]
Return a non-mutating iterator referring to the first element in the list, if any, or one past the end of this list if this list is empty.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> const_iterator bsl::list< VALUE, ALLOCATOR >::cend () const [inherited]
Return a non-mutating iterator referring to one past the end of the list.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> const_reverse_iterator bsl::list< VALUE, ALLOCATOR >::crbegin () const [inherited]
Return a const reverse iterator referring to the last element of this list (i.e., the first element of the reverse sequence), if any, or one before the start if this list is empty.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> const_reverse_iterator bsl::list< VALUE, ALLOCATOR >::crend () const [inherited]
Return a const reverse iterator referring to one before the start of this list.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> bool bsl::list< VALUE, ALLOCATOR >::empty () const [inherited]
Return true if this list has no elements and false otherwise.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> size_type bsl::list< VALUE, ALLOCATOR >::size () const [inherited]
Return the number of elements in this list.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> size_type bsl::list< VALUE, ALLOCATOR >::max_size () const [inherited]
Return an upper bound on the largest number of elements that this list could possibly hold. Note that return value of this function does not guarantee that this list can successfully grow that large, or even close to that large without running out of resources.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> const_reference bsl::list< VALUE, ALLOCATOR >::front () const [inherited]
Return a reference providing non-modifiable access to the first element of this list. The behavior is undefined unless this list contains at least one element.
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> const_reference bsl::list< VALUE, ALLOCATOR >::back () const [inherited]
Return a reference providing non-modifiable access to the last element of this list. The behavior is undefined unless this list contains at least one element.
template<class VALUE , class ALLOCATOR > bool bsl::operator== (const list< VALUE, ALLOCATOR > & lhs, const list< VALUE, ALLOCATOR > & rhs)
Return true if the specified lhs and rhs lists have the same value, and false otherwise. The lhs and the rhs objects have the same value if they have the same number of elements, and each element of lhs has same value as that of the corresponding element in rhs. This method requires that the (template parameter) VALUE type has operator== defined.
template<class VALUE , class ALLOCATOR > bool bsl::operator!= (const list< VALUE, ALLOCATOR > & lhs, const list< VALUE, ALLOCATOR > & rhs)
Return true if the specified lhs and rhs lists do not have the same value, and false otherwise. The lhs and the rhs objects do have the same value if they do not have the same number of elements, or at least one element of lhs does not have same value as that of the corresponding element in rhs. This method requires that the (template parameter) VALUE type has operator== defined.
template<class VALUE , class ALLOCATOR > bool bsl::operator< (const list< VALUE, ALLOCATOR > & lhs, const list< VALUE, ALLOCATOR > & rhs)
Return true if the specified lhs list is lexicographically smaller than the specified rhs list, and false otherwise. The lhs is lexicographically smaller than the rhs if there exists an element v in lhs such that v is smaller than the corresponding element in rhs, and all elements before v in lhs have the same values as those of the corresponding elements in rhs. This method requires that the (template parameter) VALUE type has operator< defined.
template<class VALUE , class ALLOCATOR > bool bsl::operator> (const list< VALUE, ALLOCATOR > & lhs, const list< VALUE, ALLOCATOR > & rhs)
Return true if the specified lhs list is lexicographically larger than the specified rhs list, and false otherwise. This method requires that the (template parameter) VALUE type has operator< defined.
template<class VALUE , class ALLOCATOR > bool bsl::operator<= (const list< VALUE, ALLOCATOR > & lhs, const list< VALUE, ALLOCATOR > & rhs)
Return true if the specified lhs list is lexicographically smaller than or equal to the specified rhs list, and false otherwise. This method requires that the (template parameter) VALUE type has operator< defined.
template<class VALUE , class ALLOCATOR > bool bsl::operator>= (const list< VALUE, ALLOCATOR > & lhs, const list< VALUE, ALLOCATOR > & rhs)
Return true if the specified lhs list is lexicographically larger than or equal to the specified rhs list, and false otherwise. This method requires that the (template parameter) VALUE type has operator< defined.
template<class VALUE , class ALLOCATOR > void bsl::swap (list< VALUE, ALLOCATOR > & lhs, list< VALUE, ALLOCATOR > & rhs)
Exchange the value of the specified lhs list with that of the specified rhs list, such that each list has upon return the value of the other list prior to this call. Note that this function does not throw if lhs.get_allocator() and rhs.get_allocator() are equal.
Variable Documentation
template<class VALUE > NodePtr bsl::List_Node< VALUE >::d_prev [inherited]
pointer to the previous node in this list
template<class VALUE > NodePtr bsl::List_Node< VALUE >::d_next [inherited]
pointer to the next node in this list
template<class VALUE > VALUE bsl::List_Node< VALUE >::d_value [inherited]
list element
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> size_type bsl::list< VALUE, ALLOCATOR >::AllocAndSizeWrapper::d_size [inherited]
allocated size
Friends
template<class VALUE, class NODEPTR, class DIFFTYPE> friend class List_Iterator< const VALUE, NODEPTR, DIFFTYPE > [friend, inherited]
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> friend struct AllocAndSizeWrapper [friend, inherited]
template<class VALUE , class ALLOCATOR = bsl::allocator<VALUE>> friend class NodeProctor [friend, inherited]
template<class VALUE, class NODEPTR, class DIFFTYPE> template<class T1 , class T2 , class NODEP , class DIFFT > bool operator== (List_Iterator< T1, NODEP, DIFFT > , List_Iterator< T2, NODEP, DIFFT >) [friend, inherited]