BDE 2.16 BETA: bslstl_string Component
Quick Links:
bsl+bslhdrs | bsl+stdhdrs | bslalg | bsldoc | bslim | bslma | bslmf | bsls | bslscm | bslstl | bsltf
Component bslstl_string
[Package bslstl]
Provide a standard-compliant basic_string class template.
Classes
class bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >
class bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >
struct bsl::hash< basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > >
Defines
#define BSLSTL_CHAR_TRAITS CHAR_TRAITS
#define BSLSTL_INSERT_RETURN_TYPE typename basic_string<CHAR_TYPE,CHAR_TRAITS,ALLOCATOR>::iterator
Typedefs
typedef CHAR_TRAITS::char_type bsl::basic_string::value_type
typedef ALLOCATOR bsl::basic_string::allocator_type
typedef ALLOCATOR::size_type bsl::basic_string::size_type
typedef ALLOCATOR::difference_type bsl::basic_string::difference_type
typedef ALLOCATOR::reference bsl::basic_string::reference
typedef ALLOCATOR::const_reference bsl::basic_string::const_reference
typedef ALLOCATOR::pointer bsl::basic_string::pointer
typedef ALLOCATOR::const_pointer bsl::basic_string::const_pointer
typedef CHAR_TYPE * bsl::basic_string::iterator
typedef const CHAR_TYPE * bsl::basic_string::const_iterator
typedef bsl::reverse_iterator
< iterator > bsl::basic_string::reverse_iterator
typedef bsl::reverse_iterator
< const_iterator > bsl::basic_string::const_reverse_iterator
typedef basic_string< char > bsl::string
typedef basic_string< wchar_t > bsl::wstring
Enumerations
enum bsl::String_Imp::ConfigurableParameters { bsl::String_Imp::BASIC_STRING_DEALLOCATE_IN_CLEAR = false, bsl::String_Imp::BASIC_STRING_HONOR_SHRINK_REQUEST = false }
Functions
bsl::String_Imp::BSLMF_ASSERT (SHORT_BUFFER_BYTES >=sizeof(CHAR_TYPE *))
bsl::String_Imp::BSLMF_NESTED_TRAIT_DECLARATION (String_Imp, BloombergLP::bslmf::IsBitwiseMoveable)
static SIZE_TYPE bsl::String_Imp::computeNewCapacity (SIZE_TYPE newLength, SIZE_TYPE oldCapacity, SIZE_TYPE maxSize)
bsl::String_Imp::String_Imp ()
bsl::String_Imp::String_Imp (SIZE_TYPE length, SIZE_TYPE capacity)
bsl::String_Imp::String_Imp (const String_Imp &original)
bsl::String_Imp::~String_Imp ()
String_Imp & bsl::String_Imp::operator= (const String_Imp &rhs)
void bsl::String_Imp::swap (String_Imp &other)
void bsl::String_Imp::resetFields ()
CHAR_TYPE * bsl::String_Imp::dataPtr ()
bool bsl::String_Imp::isShortString () const
const CHAR_TYPE * bsl::String_Imp::dataPtr () const
bsl::basic_string::basic_string (const ALLOCATOR &allocator=ALLOCATOR())
bsl::basic_string::basic_string (const basic_string &original)
bsl::basic_string::basic_string (const basic_string &original, const ALLOCATOR &allocator)
bsl::basic_string::basic_string (const basic_string &original, size_type position, size_type numChars=npos, const ALLOCATOR &allocator=ALLOCATOR())
bsl::basic_string::basic_string (const CHAR_TYPE *characterString, const ALLOCATOR &allocator=ALLOCATOR())
bsl::basic_string::basic_string (const CHAR_TYPE *characterString, size_type numChars, const ALLOCATOR &allocator=ALLOCATOR())
bsl::basic_string::basic_string (size_type numChars, CHAR_TYPE character, const ALLOCATOR &allocator=ALLOCATOR())
template<typename INPUT_ITER >
bsl::basic_string::basic_string (INPUT_ITER first, INPUT_ITER last, const ALLOCATOR &allocator=ALLOCATOR())
template<typename ALLOC2 >
bsl::basic_string::basic_string (const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > &original, const ALLOCATOR &allocator=ALLOCATOR())
bsl::basic_string::basic_string (const BloombergLP::bslstl::StringRefData< CHAR_TYPE > &strRef, const ALLOCATOR &allocator=ALLOCATOR())
bsl::basic_string::~basic_string ()
basic_string & bsl::basic_string::operator= (const basic_string &rhs)
basic_string & bsl::basic_string::operator= (const CHAR_TYPE *rhs)
basic_string & bsl::basic_string::operator= (CHAR_TYPE character)
void bsl::basic_string::resize (size_type newLength, CHAR_TYPE character)
void bsl::basic_string::resize (size_type newLength)
void bsl::basic_string::reserve (size_type newCapacity=0)
void bsl::basic_string::clear ()
iterator bsl::basic_string::begin ()
iterator bsl::basic_string::end ()
reverse_iterator bsl::basic_string::rbegin ()
reverse_iterator bsl::basic_string::rend ()
reference bsl::basic_string::operator[] (size_type position)
reference bsl::basic_string::at (size_type position)
reference bsl::basic_string::front ()
reference bsl::basic_string::back ()
template<typename ALLOC2 >
bsl::basic_string::operator native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > () const
basic_string & bsl::basic_string::operator+= (const basic_string &string)
basic_string & bsl::basic_string::operator+= (const CHAR_TYPE *string)
basic_string & bsl::basic_string::operator+= (CHAR_TYPE character)
basic_string & bsl::basic_string::append (const basic_string &string)
basic_string & bsl::basic_string::append (const basic_string &string, size_type position, size_type numChars)
basic_string & bsl::basic_string::append (const CHAR_TYPE *characterString, size_type numChars)
basic_string & bsl::basic_string::append (const CHAR_TYPE *characterString)
basic_string & bsl::basic_string::append (size_type numChars, CHAR_TYPE character)
template<typename INPUT_ITER >
basic_string & bsl::basic_string::append (INPUT_ITER first, INPUT_ITER last)
void bsl::basic_string::push_back (CHAR_TYPE character)
basic_string & bsl::basic_string::assign (const basic_string &string)
basic_string & bsl::basic_string::assign (const basic_string &string, size_type position, size_type numChars)
basic_string & bsl::basic_string::assign (const CHAR_TYPE *characterString)
basic_string & bsl::basic_string::assign (const CHAR_TYPE *characterString, size_type numChars)
basic_string & bsl::basic_string::assign (size_type numChars, CHAR_TYPE character)
template<typename INPUT_ITER >
basic_string & bsl::basic_string::assign (INPUT_ITER first, INPUT_ITER last)
basic_string & bsl::basic_string::insert (size_type position, const basic_string &string)
basic_string & bsl::basic_string::insert (size_type outPosition, const basic_string &string, size_type position, size_type numChars)
basic_string & bsl::basic_string::insert (size_type position, const CHAR_TYPE *characterString, size_type numChars)
basic_string & bsl::basic_string::insert (size_type position, const CHAR_TYPE *characterString)
basic_string & bsl::basic_string::insert (size_type position, size_type numChars, CHAR_TYPE character)
iterator bsl::basic_string::insert (const_iterator position, CHAR_TYPE character)
iterator bsl::basic_string::insert (const_iterator position, size_type numChars, CHAR_TYPE character)
template<typename INPUT_ITER >
iterator bsl::basic_string::insert (const_iterator position, INPUT_ITER first, INPUT_ITER last)
basic_string & bsl::basic_string::erase (size_type position=0, size_type numChars=npos)
iterator bsl::basic_string::erase (const_iterator position)
iterator bsl::basic_string::erase (const_iterator first, const_iterator last)
void bsl::basic_string::pop_back ()
basic_string & bsl::basic_string::replace (size_type outPosition, size_type outNumChars, const basic_string &string)
basic_string & bsl::basic_string::replace (size_type outPosition, size_type outNumChars, const basic_string &string, size_type position, size_type numChars)
basic_string & bsl::basic_string::replace (size_type outPosition, size_type outNumChars, const CHAR_TYPE *characterString, size_type numChars)
basic_string & bsl::basic_string::replace (size_type outPosition, size_type outNumChars, const CHAR_TYPE *characterString)
basic_string & bsl::basic_string::replace (size_type outPosition, size_type outNumChars, size_type numChars, CHAR_TYPE character)
basic_string & bsl::basic_string::replace (const_iterator first, const_iterator last, const basic_string &string)
basic_string & bsl::basic_string::replace (const_iterator first, const_iterator last, const CHAR_TYPE *characterString, size_type numChars)
basic_string & bsl::basic_string::replace (const_iterator first, const_iterator last, const CHAR_TYPE *characterString)
basic_string & bsl::basic_string::replace (const_iterator first, const_iterator last, size_type numChars, CHAR_TYPE character)
template<typename INPUT_ITER >
basic_string & bsl::basic_string::replace (const_iterator first, const_iterator last, INPUT_ITER stringFirst, INPUT_ITER stringLast)
void bsl::basic_string::swap (basic_string &other)
const_iterator bsl::basic_string::begin () const
const_iterator bsl::basic_string::cbegin () const
const_iterator bsl::basic_string::end () const
const_iterator bsl::basic_string::cend () const
const_reverse_iterator bsl::basic_string::rbegin () const
const_reverse_iterator bsl::basic_string::crbegin () const
const_reverse_iterator bsl::basic_string::rend () const
const_reverse_iterator bsl::basic_string::crend () const
size_type bsl::basic_string::length () const
size_type bsl::basic_string::size () const
size_type bsl::basic_string::max_size () const
size_type bsl::basic_string::capacity () const
bool bsl::basic_string::empty () const
const_reference bsl::basic_string::operator[] (size_type position) const
const_reference bsl::basic_string::at (size_type position) const
const_reference bsl::basic_string::front () const
const_reference bsl::basic_string::back () const
size_type bsl::basic_string::copy (CHAR_TYPE *characterString, size_type numChars, size_type position=0) const
const_pointer bsl::basic_string::c_str () const
const_pointer bsl::basic_string::data () const
allocator_type bsl::basic_string::get_allocator () const
size_type bsl::basic_string::find (const basic_string &string, size_type position=0) const
size_type bsl::basic_string::find (const CHAR_TYPE *string, size_type position, size_type numChars) const
size_type bsl::basic_string::find (const CHAR_TYPE *string, size_type position=0) const
size_type bsl::basic_string::find (CHAR_TYPE character, size_type position=0) const
size_type bsl::basic_string::rfind (const basic_string &string, size_type position=npos) const
size_type bsl::basic_string::rfind (const CHAR_TYPE *characterString, size_type position, size_type numChars) const
size_type bsl::basic_string::rfind (const CHAR_TYPE *characterString, size_type position=npos) const
size_type bsl::basic_string::rfind (CHAR_TYPE character, size_type position=npos) const
size_type bsl::basic_string::find_first_of (const basic_string &string, size_type position=0) const
size_type bsl::basic_string::find_first_of (const CHAR_TYPE *characterString, size_type position, size_type numChars) const
size_type bsl::basic_string::find_first_of (const CHAR_TYPE *characterString, size_type position=0) const
size_type bsl::basic_string::find_first_of (CHAR_TYPE character, size_type position=0) const
size_type bsl::basic_string::find_last_of (const basic_string &string, size_type position=npos) const
size_type bsl::basic_string::find_last_of (const CHAR_TYPE *characterString, size_type position, size_type numChars) const
size_type bsl::basic_string::find_last_of (const CHAR_TYPE *characterString, size_type position=npos) const
size_type bsl::basic_string::find_last_of (CHAR_TYPE character, size_type position=npos) const
size_type bsl::basic_string::find_first_not_of (const basic_string &string, size_type position=0) const
size_type bsl::basic_string::find_first_not_of (const CHAR_TYPE *characterString, size_type position, size_type numChars) const
size_type bsl::basic_string::find_first_not_of (const CHAR_TYPE *characterString, size_type position=0) const
size_type bsl::basic_string::find_first_not_of (CHAR_TYPE character, size_type position=0) const
size_type bsl::basic_string::find_last_not_of (const basic_string &string, size_type position=npos) const
size_type bsl::basic_string::find_last_not_of (const CHAR_TYPE *characterString, size_type position, size_type numChars) const
size_type bsl::basic_string::find_last_not_of (const CHAR_TYPE *characterString, size_type position=npos) const
size_type bsl::basic_string::find_last_not_of (CHAR_TYPE character, size_type position=npos) const
basic_string bsl::basic_string::substr (size_type position=0, size_type numChars=npos) const
int bsl::basic_string::compare (const basic_string &other) const
int bsl::basic_string::compare (size_type position, size_type numChars, const basic_string &other) const
int bsl::basic_string::compare (size_type lhsPosition, size_type lhsNumChars, const basic_string &other, size_type otherPosition, size_type otherNumChars) const
int bsl::basic_string::compare (const CHAR_TYPE *other) const
int bsl::basic_string::compare (size_type lhsPosition, size_type lhsNumChars, const CHAR_TYPE *other, size_type otherNumChars) const
int bsl::basic_string::compare (size_type lhsPosition, size_type lhsNumChars, const CHAR_TYPE *other) const
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC >
bool bsl::operator== (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 >
bool bsl::operator== (const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > &lhs, const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 >
bool bsl::operator== (const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > &lhs, const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC >
bool bsl::operator== (const CHAR_TYPE *lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC >
bool bsl::operator== (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &lhs, const CHAR_TYPE *rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC >
bool bsl::operator!= (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 >
bool bsl::operator!= (const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > &lhs, const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 >
bool bsl::operator!= (const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > &lhs, const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC >
bool bsl::operator!= (const CHAR_TYPE *lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC >
bool bsl::operator!= (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &lhs, const CHAR_TYPE *rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC >
bool bsl::operator< (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 >
bool bsl::operator< (const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > &lhs, const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 >
bool bsl::operator< (const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > &lhs, const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC >
bool bsl::operator< (const CHAR_TYPE *lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC >
bool bsl::operator< (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &lhs, const CHAR_TYPE *rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC >
bool bsl::operator> (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 >
bool bsl::operator> (const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > &lhs, const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 >
bool bsl::operator> (const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > &lhs, const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC >
bool bsl::operator> (const CHAR_TYPE *lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC >
bool bsl::operator> (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &lhs, const CHAR_TYPE *rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC >
bool bsl::operator<= (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 >
bool bsl::operator<= (const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > &lhs, const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 >
bool bsl::operator<= (const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > &lhs, const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC >
bool bsl::operator<= (const CHAR_TYPE *lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC >
bool bsl::operator<= (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &lhs, const CHAR_TYPE *rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC >
bool bsl::operator>= (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 >
bool bsl::operator>= (const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > &lhs, const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 >
bool bsl::operator>= (const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > &lhs, const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC >
bool bsl::operator>= (const CHAR_TYPE *lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC >
bool bsl::operator>= (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > &lhs, const CHAR_TYPE *rhs)
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR >
basic_string< CHAR_TYPE,
CHAR_TRAITS, ALLOCATOR > bsl::operator+ (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > &lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 >
basic_string< CHAR_TYPE,
CHAR_TRAITS, ALLOC2 > bsl::operator+ (const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > &lhs, const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 >
basic_string< CHAR_TYPE,
CHAR_TRAITS, ALLOC1 > bsl::operator+ (const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > &lhs, const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > &rhs)
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR >
basic_string< CHAR_TYPE,
CHAR_TRAITS, ALLOCATOR > bsl::operator+ (const CHAR_TYPE *lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > &rhs)
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR >
basic_string< CHAR_TYPE,
CHAR_TRAITS, ALLOCATOR > bsl::operator+ (CHAR_TYPE lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > &rhs)
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR >
basic_string< CHAR_TYPE,
CHAR_TRAITS, ALLOCATOR > bsl::operator+ (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > &lhs, const CHAR_TYPE *rhs)
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR >
basic_string< CHAR_TYPE,
CHAR_TRAITS, ALLOCATOR > bsl::operator+ (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > &lhs, CHAR_TYPE rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR >
std::basic_ostream< CHAR_TYPE,
CHAR_TRAITS > & bsl::operator<< (std::basic_ostream< CHAR_TYPE, CHAR_TRAITS > &os, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > &str)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR >
std::basic_istream< CHAR_TYPE,
CHAR_TRAITS > & bsl::operator>> (std::basic_istream< CHAR_TYPE, CHAR_TRAITS > &is, basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > &str)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR >
void bsl::swap (basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > &lhs, basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > &rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR >
std::basic_istream< CHAR_TYPE,
CHAR_TRAITS > & bsl::getline (std::basic_istream< CHAR_TYPE, CHAR_TRAITS > &is, basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > &str, CHAR_TYPE delim)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR >
std::basic_istream< CHAR_TYPE,
CHAR_TRAITS > & bsl::getline (std::basic_istream< CHAR_TYPE, CHAR_TRAITS > &is, basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > &str)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR >
std::size_t bsl::hashBasicString (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > &str)
std::size_t bsl::hashBasicString (const string &str)
std::size_t bsl::hash< basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > >::operator() (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > &str) const
template<class CHAR_TYPE , class CHAR_TRAITS >
bool bsl::bslstl_string_fill (std::basic_ostream< CHAR_TYPE, CHAR_TRAITS > &os, std::basic_streambuf< CHAR_TYPE, CHAR_TRAITS > *buf, size_t n)
Variables
CHAR_TYPE * bsl::String_Imp::d_start_p
union {
BloombergLP::bsls::AlignedBuffer
< SHORT_BUFFER_BYTES,
BloombergLP::bsls::AlignmentFromType
< CHAR_TYPE >::VALUE > d_short
CHAR_TYPE * bsl::String_Imp::d_start_p
};
SIZE_TYPE bsl::String_Imp::d_length
SIZE_TYPE bsl::String_Imp::d_capacity
static const size_type bsl::basic_string::npos = ~size_type(0)
Detailed Description
Outline
Purpose
Classes
Description
Memory Allocation
bslma-Style Allocators
Lexicographical Comparisons
Operations
Usage
Example 1: Basic Syntax
Example 2: string as a data member
Example 3: A stream text replacement filter
Purpose:
Provide a standard-compliant basic_string class template.
Classes:
bsl::basic_string C++ standard compliant basic_string implementation
bsl::string typedef for bsl::basic_string<char>
bsl::wstring typedef for bsl::basic_string<wchar>
See also:
ISO C++ Standard, Section 21 [strings]
Description:
This component defines a single class template basic_string, implementing standard containers, std::string and std::wstring, that hold a sequence of characters.
An instantiation of basic_string is an allocator-aware, value-semantic type whose salient attributes are its size (number of characters) and the sequence of characters that the string contains. The basic_string class is parameterized by the character type, CHAR_TYPE, that character type's traits, CHAR_TRAITS, and an allocator, ALLOCATOR. The traits for each character type provide functions that assign, compare, and copy a sequence of those characters.
A basic_string meets the requirements of a sequential container with random access iterators as specified in the [basic.string] section of the C++ standard [21.4]. The basic_string implemented here adheres to the C++11 standard, except that it does not have interfaces that take rvalue references or initializer_lists, the shrink_to_fit method, functions that support numeric conversions, such as stoi, to_string, and to_wstring, and template specializations std::u16string and std::u32string. Note that excluded C++11 features are those that require (or are greatly simplified by) C++11 compiler support.
Memory Allocation:
The type supplied as a basic_strings ALLOCATOR template parameter determines how that basic_string will allocate memory. The basic_string template supports allocators meeting the requirements of the C++11 standard, in addition it supports scoped-allocators derived from the bslma::Allocator memory allocation protocol. Clients intending to use bslma style allocators should use the template's default ALLOCATOR type: The default type for the ALLOCATOR template parameter, bsl::allocator, provides a C++11 standard-compatible adapter for a bslma::Allocator object.
bslma-Style Allocators:
If the (template parameter) type ALLOCATOR of an basic_string instantiation is bsl::allocator, then objects of that basic_string type will conform to the standard behavior of a bslma-allocator-enabled type. Such a basic_string accepts an optional bslma::Allocator argument at construction. If the address of a bslma::Allocator object is explicitly supplied at construction, it will be used to supply memory for the basic_string throughout its lifetime; otherwise, the basic_string will use the default allocator installed at the time of the basic_string's construction (see bslma_default).
Lexicographical Comparisons:
Two basic_strings lhs and rhs are lexicographically compared by first determining N, the smaller of the lengths of lhs and rhs, and comparing characters at each position between 0 and N - 1, using CHAR_TRAITS::lt in lexicographical fashion. If CHAR_TRAITS::lt determines that strings are non-equal (smaller or larger), then this is the result. Otherwise, the lengths of the strings are compared and the shorter string is declared the smaller. Lexicographical comparison returns equality only when both strings have the same length and the same character value in each respective position.
Operations:
This section describes the run-time complexity of operations on instances of basic_string:
  Legend
  ------
  'V'              - the 'CHAR_TYPE' template parameter type of the
                     'basic_string'
  'a', 'b'         - two distinct objects of type 'basic_string<V>'
  'k'              - an integral number
  'al'             - an STL-style memory allocator
  'i1', 'i2'       - two iterators defining a sequence of 'CHAR_TYPE'
                     characters
  'v'              - an object of type 'V'
  'p1', 'p2'       - two iterators belonging to 'a'
  distance(i1,i2)  - the number of values in the range [i1, i2)
  +-----------------------------------------+-------------------------------+
  | Operation                               | Complexity                    |
  |=========================================+===============================|
  | basic_string<V> a (default construction)| O[1]                          |
  | basic_string<V> a(al)                   |                               |
  |-----------------------------------------+-------------------------------|
  | basic_string<V> a(b) (copy construction)| O[n]                          |
  | basic_string<V> a(b, al)                |                               |
  |-----------------------------------------+-------------------------------|
  | basic_string<V> a(k)                    | O[n]                          |
  | basic_string<V> a(k, al)                |                               |
  |-----------------------------------------+-------------------------------|
  | basic_string<V> a(i1, i2)               | O[distance(i1,i2)]            |
  | basic_string<V> a(i1, i2, al)           |                               |
  |-----------------------------------------+-------------------------------|
  | a.~basic_string<V>()  (destruction)     | O[1]                          |
  |-----------------------------------------+-------------------------------|
  | a.assign(k, v)                          | O[k]                          |
  |-----------------------------------------+-------------------------------|
  | a.assign(i1, i2)                        | O[distance(i1,i2)]            |
  |-----------------------------------------+-------------------------------|
  | get_allocator()                         | O[1]                          |
  |-----------------------------------------+-------------------------------|
  | a.begin(), a.end(),                     | O[1]                          |
  | a.cbegin(), a.cend(),                   |                               |
  | a.rbegin(), a.rend(),                   |                               |
  | a.crbegin(), a.crend()                  |                               |
  |-----------------------------------------+-------------------------------|
  | a.size()                                | O[1]                          |
  |-----------------------------------------+-------------------------------|
  | a.max_size()                            | O[1]                          |
  |-----------------------------------------+-------------------------------|
  | a.resize(k)                             | O[k]                          |
  | a.resize(k, v)                          |                               |
  |-----------------------------------------+-------------------------------|
  | a.empty()                               | O[1]                          |
  |-----------------------------------------+-------------------------------|
  | a.reserve(k)                            | O[1]                          |
  |-----------------------------------------+-------------------------------|
  | a[k]                                    | O[1]                          |
  |-----------------------------------------+-------------------------------|
  | a.at(k)                                 | O[1]                          |
  |-----------------------------------------+-------------------------------|
  | a.front()                               | O[1]                          |
  |-----------------------------------------+-------------------------------|
  | a.back()                                | O[1]                          |
  |-----------------------------------------+-------------------------------|
  | a.push_back()                           | O[1]                          |
  |-----------------------------------------+-------------------------------|
  | a.pop_back()                            | O[1]                          |
  |-----------------------------------------+-------------------------------|
  | a.insert(p1, v)                         | O[1 + distance(p1, a.end())]  |
  |-----------------------------------------+-------------------------------|
  | a.insert(p1, k, v)                      | O[k + distance(p1, a.end())]  |
  |-----------------------------------------+-------------------------------|
  | a.insert(p1, i1, i2)                    | O[distance(i1, i2)            |
  |                                         |      + distance(p1, a.end())] |
  |-----------------------------------------+-------------------------------|
  | a.erase(p1)                             | O[1 + distance(p1, a.end())]  |
  |-----------------------------------------+-------------------------------|
  | a.erase(p1, p2)                         | O[1 + distance(p1, a.end())]  |
  |-----------------------------------------+-------------------------------|
  | a.swap(b), swap(a,b)                    | O[1] if 'a' and 'b' use the   |
  |                                         | same allocator, O[n + m]      |
  |                                         | otherwise                     |
  |-----------------------------------------+-------------------------------|
  | a.clear()                               | O[1]                          |
  |-----------------------------------------+-------------------------------|
  | a = b;           (assignment)           | O[n]                          |
  |-----------------------------------------+-------------------------------|
  | a == b, a != b                          | O[n]                          |
  |-----------------------------------------+-------------------------------|
  | a < b, a <= b, a > b, a >= b            | O[n]                          |
  +-----------------------------------------+-------------------------------+
Usage:
In this section we show intended use of this component.
Example 1: Basic Syntax:
In this example, we will show how to create and use the string typedef.
First, we will default-construct a string object:
  bsl::string s;
  assert(s.empty());
  assert(0  == s.size());
  assert("" == s);
Then, we will construct a string object from a string literal:
  bsl::string t = "Hello World";
  assert(!t.empty());
  assert(11 == t.size());
  assert("Hello World" == t);
Next, we will clear the contents of t and assign it a couple of values: first from a string literal; and second from another string object:
  t.clear();
  assert(t.empty());
  assert("" == t);
  t = "Good Morning";
  assert(!t.empty());
  assert("Good Morning" == t);
  t = s;
  assert(t.empty());
  assert("" == t);
  assert(t == s);
Then, we will create three string objects: the first representing a street name, the second a state, and the third a zipcode. We will then concatenate them into a single address string and print the contents of that string on standard output:
  const bsl::string street  = "731 Lexington Avenue";
  const bsl::string state   = "NY";
  const bsl::string zipcode = "10022";
  const bsl::string fullAddress = street + " " + state + " " + zipcode;
  bsl::cout << fullAddress << bsl::endl;
The above print statement should produce a single line of output:
  731 Lexington Avenue NY 10022
Then, we search the contents of address (using the find function) to determine if it lies on a specified street:
  const bsl::string streetName = "Lexington";
  if (bsl::string::npos != fullAddress.find(streetName, 0)) {
      bsl::cout << "The address " << fullAddress << " is located on "
                << streetName << "." << bsl::endl;
  }
Next, we show how to get a reference providing modifiable access to the null-terminated string literal stored by a string object using the c_str function. Note that the returned string literal can be passed to various standard functions expecting a null-terminated string:
  const bsl::string  v = "Another string";
  const char        *cs = v.c_str();
  assert(bsl::strlen(cs) == v.size());
Then, we construct two string objects, x and y, using a user-specified allocator:
  bslma::TestAllocator allocator1, allocator2;
  const char *SHORT_STRING = "A small string";
  const char *LONG_STRING  = "This long string would definitely cause "
                             "memory to be allocated on creation";
  const bsl::string x(SHORT_STRING, &allocator1);
  const bsl::string y(LONG_STRING,  &allocator2);
  assert(SHORT_STRING == x);
  assert(LONG_STRING  == y);
Notice that, no memory was allocated from the allocator for object x because of the short-string optimization used in the string type.
Finally, we can track memory usage of x and y using allocator1 and allocator2 and check that memory was allocated only by allocator2:
  assert(0 == allocator1.numBlocksInUse());
  assert(1 == allocator2.numBlocksInUse());
Example 2: string as a data member:
The most common use of string objects are as data members in user-defined classes. In this example, we will show how string objects can be used as data members.
First, we begin to define a class, Employee, that represents the data corresponding to an employee of a company:
  class Employee {
      // This simply constrained (value-semantic) attribute class represents
      // the information about an employee.  An employee's first and last
      // name are represented as 'string' objects and their employee
      // identification number is represented by an 'int'.  Note that the
      // class invariants are identically the constraints on the individual
      // attributes.
      //
      // This class:
      //: o supports a complete set of *value-semantic* operations
      //:   o except for 'bslx' serialization
      //: o is *exception-neutral* (agnostic)
      //: o is *alias-safe*
      //: o is 'const' *thread-safe*
      // DATA
      bsl::string d_firstName;       // first name
      bsl::string d_lastName;        // last name
      int         d_id;              // identification number
Next, we define the creators for this class:
    public:
      // CREATORS
      Employee(bslma::Allocator *basicAllocator = 0);
          // Create a 'Employee' object having the (default) attribute
          // values:
          //..
          //  firstName() == ""
          //  lastName()  == ""
          //  id()        == 0
          //..
          // Optionally specify a 'basicAllocator' used to supply memory.  If
          // 'basicAllocator' is 0, the currently installed default
          // allocator is used.
      Employee(const bslstl::StringRef&  firstName,
               const bslstl::StringRef&  lastName,
               int                       id,
               bslma::Allocator         *basicAllocator = 0);
          // Create a 'Employee' object having the specified 'firstName',
          // 'lastName', and 'id'' attribute values.  Optionally specify a
          // 'basicAllocator' used to supply memory.  If 'basicAllocator' is
          // 0, the currently installed default allocator is used.
      Employee(const Employee&   original,
               bslma::Allocator *basicAllocator = 0);
          // Create a 'Employee' object having the same value as the
          // specified 'original' object.  Optionally specify a
          // 'basicAllocator' used to supply memory.  If 'basicAllocator' is
          // 0, the currently installed default allocator is used.
          // Destroy this object.
Notice that all constructors of the Employee class are optionally provided an allocator that is then passed through to the string data members of Employee. This allows the user to control how memory is allocated by Employee objects. Also note that the type of the firstName and lastName arguments of the value constructor is bslstl::StringRef. The bslstl::StringRef allows specifying a string or a const char * to represent a string value. For the sake of brevity its implementation is not explored here.
Then, declare the remaining methods of the class:
      // MANIPULATORS
      Employee& operator=(const Employee& rhs);
          // Assign to this object the value of the specified 'rhs' object,
          // and return a reference providing modifiable access to this
          // object.
      void setFirstName(const bslstl::StringRef& value);
          // Set the 'firstName' attribute of this object to the specified
          // 'value'.
      void setLastName(const bslstl::StringRef& value);
          // Set the 'lastName' attribute of this object to the specified
          // 'value'.
      void setId(int value);
          // Set the 'id' attribute of this object to the specified 'value'.
      // ACCESSORS
      const bsl::string& firstName() const;
          // Return a reference providing non-modifiable access to the
          // 'firstName' attribute of this object.
      const bsl::string& lastName() const;
          // Return a reference providing non-modifiable access to the
          // 'lastName' attribute of this object.
      int id() const;
          // Return the value of the 'id' attribute of this object.
  };
Next, we declare the free operators for Employee:
  inline
  bool operator==(const Employee& lhs, const Employee& rhs);
      // Return 'true' if the specified 'lhs' and 'rhs' objects have the same
      // value, and 'false' otherwise.  Two 'Employee' objects have the
      // same value if all of their corresponding values of their
      // 'firstName', 'lastName', and 'id' attributes are the same.
  inline
  bool operator!=(const Employee& lhs, const Employee& rhs);
      // Return 'true' if the specified 'lhs' and 'rhs' objects do not have
      // the same value, and 'false' otherwise.  Two 'Employee' objects do
      // not have the same value if any of the corresponding values of their
      // 'firstName', 'lastName', or 'id' attributes are not the same.
Then, we implement the various methods of the Employee class:
  // CREATORS
  inline
  Employee::Employee(bslma::Allocator *basicAllocator)
  : d_firstName(basicAllocator)
  , d_lastName(basicAllocator)
  , d_id(0)
  {
  }
  inline
  Employee::Employee(const bslstl::StringRef&  firstName,
                     const bslstl::StringRef&  lastName,
                     int                       id,
                     bslma::Allocator         *basicAllocator)
  : d_firstName(firstName.begin(), firstName.end(), basicAllocator)
  , d_lastName(lastName.begin(), lastName.end(), basicAllocator)
  , d_id(id)
  {
      BSLS_ASSERT_SAFE(!firstName.isEmpty());
      BSLS_ASSERT_SAFE(!lastName.isEmpty());
  }
  inline
  Employee::Employee(const Employee&   original,
                     bslma::Allocator *basicAllocator)
  : d_firstName(original.d_firstName, basicAllocator)
  , d_lastName(original.d_lastName, basicAllocator)
  , d_id(original.d_id)
  {
  }
Notice that the basicAllocator parameter can simply be passed as an argument to the constructor of bsl::string.
Now, we implement the remaining manipulators of the Employee class:
  // MANIPULATORS
  inline
  Employee& Employee::operator=(const Employee& rhs)
  {
      d_firstName = rhs.d_firstName;
      d_lastName  = rhs.d_lastName;
      d_id        = rhs.d_id;
      return *this;
  }
  inline
  void Employee::setFirstName(const bslstl::StringRef& value)
  {
      BSLS_ASSERT_SAFE(!value.isEmpty());
      d_firstName.assign(value.begin(), value.end());
  }
  inline
  void Employee::setLastName(const bslstl::StringRef& value)
  {
      BSLS_ASSERT_SAFE(!value.isEmpty());
      d_lastName.assign(value.begin(), value.end());
  }
  inline
  void Employee::setId(int value)
  {
      d_id = value;
  }
  // ACCESSORS
  inline
  const bsl::string& Employee::firstName() const
  {
      return d_firstName;
  }
  inline
  const bsl::string& Employee::lastName() const
  {
      return d_lastName;
  }
  inline
  int Employee::id() const
  {
      return d_id;
  }
Finally, we implement the free operators for Employee class:
  inline
  bool operator==(const Employee& lhs, const Employee& rhs)
  {
      return lhs.firstName() == rhs.firstName()
          && lhs.lastName()  == rhs.lastName()
          && lhs.id()        == rhs.id();
  }
  inline
  bool operator!=(const Employee& lhs, const Employee& rhs)
  {
      return lhs.firstName() != rhs.firstName()
          || lhs.lastName()  != rhs.lastName()
          || lhs.id()        != rhs.id();
  }
Example 3: A stream text replacement filter:
In this example, we will utilize the string type and its associated utility functions to define a function that reads data from an input stream, replaces all occurrences of a specified text fragment with another text fragment, and writes the resulting text to an output stream.
First, we define the signature of the function, replace:
  void replace(bsl::ostream&      outputStream,
               bsl::istream&      inputStream,
               const bsl::string& oldString,
               const bsl::string& newString)
      // Read data from the specified 'inputStream' and replace all
      // occurrences of the text contained in the specified 'oldString' in
      // the stream with the text contained in the specified 'newString'.
      // Write the modified data to the specified 'outputStream'.
Then, we provide the implementation for replace:
  {
      const int   oldStringSize = oldString.size();
      const int   newStringSize = newString.size();
      bsl::string line;
      bsl::getline(inputStream, line);
Notice that we can use the getline free function defined in this component to read a single line of data from an input stream into a bsl::string.
      if (!inputStream) {
          return;                                                   // RETURN
      }
      do {
Next, we use the find function to search the contents of line for characters matching the contents of oldString:
          int pos = line.find(oldString);
          while (bsl::string::npos != pos) {
Now, we use the replace method to modify the contents of line matching oldString to newString:
              line.replace(pos, oldStringSize, newString);
              pos = line.find(oldString, pos + newStringSize);
Notice that we provide find with the starting position from which to start searching.
          }
Finally, we write the updated contents of line to the output stream:
          outputStream << line;
          bsl::getline(inputStream, line);
      } while (inputStream);
  }
Define Documentation
#define BSLSTL_CHAR_TRAITS CHAR_TRAITS
#define BSLSTL_INSERT_RETURN_TYPE typename basic_string<CHAR_TYPE,CHAR_TRAITS,ALLOCATOR>::iterator
Typedef Documentation
template<typename CHAR_TYPE, typename CHAR_TRAITS = char_traits<CHAR_TYPE>, typename ALLOCATOR = allocator<CHAR_TYPE>> typedef CHAR_TRAITS::char_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::value_type [inherited]
template<typename CHAR_TYPE, typename CHAR_TRAITS = char_traits<CHAR_TYPE>, typename ALLOCATOR = allocator<CHAR_TYPE>> typedef ALLOCATOR bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::allocator_type [inherited]
template<typename CHAR_TYPE, typename CHAR_TRAITS = char_traits<CHAR_TYPE>, typename ALLOCATOR = allocator<CHAR_TYPE>> typedef ALLOCATOR::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type [inherited]
template<typename CHAR_TYPE, typename CHAR_TRAITS = char_traits<CHAR_TYPE>, typename ALLOCATOR = allocator<CHAR_TYPE>> typedef ALLOCATOR::difference_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::difference_type [inherited]
template<typename CHAR_TYPE, typename CHAR_TRAITS = char_traits<CHAR_TYPE>, typename ALLOCATOR = allocator<CHAR_TYPE>> typedef ALLOCATOR::reference bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::reference [inherited]
template<typename CHAR_TYPE, typename CHAR_TRAITS = char_traits<CHAR_TYPE>, typename ALLOCATOR = allocator<CHAR_TYPE>> typedef ALLOCATOR::const_reference bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::const_reference [inherited]
template<typename CHAR_TYPE, typename CHAR_TRAITS = char_traits<CHAR_TYPE>, typename ALLOCATOR = allocator<CHAR_TYPE>> typedef ALLOCATOR::pointer bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::pointer [inherited]
template<typename CHAR_TYPE, typename CHAR_TRAITS = char_traits<CHAR_TYPE>, typename ALLOCATOR = allocator<CHAR_TYPE>> typedef ALLOCATOR::const_pointer bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::const_pointer [inherited]
template<typename CHAR_TYPE, typename CHAR_TRAITS = char_traits<CHAR_TYPE>, typename ALLOCATOR = allocator<CHAR_TYPE>> typedef CHAR_TYPE* bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::iterator [inherited]
template<typename CHAR_TYPE, typename CHAR_TRAITS = char_traits<CHAR_TYPE>, typename ALLOCATOR = allocator<CHAR_TYPE>> typedef const CHAR_TYPE* bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::const_iterator [inherited]
template<typename CHAR_TYPE, typename CHAR_TRAITS = char_traits<CHAR_TYPE>, typename ALLOCATOR = allocator<CHAR_TYPE>> typedef bsl::reverse_iterator<iterator> bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::reverse_iterator [inherited]
template<typename CHAR_TYPE, typename CHAR_TRAITS = char_traits<CHAR_TYPE>, typename ALLOCATOR = allocator<CHAR_TYPE>> typedef bsl::reverse_iterator<const_iterator> bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::const_reverse_iterator [inherited]
typedef basic_string<char> bsl::string
typedef basic_string<wchar_t> bsl::wstring
Enumeration Type Documentation
template<typename CHAR_TYPE, typename SIZE_TYPE> enum bsl::String_Imp::ConfigurableParameters [inherited]
These configurable parameters define various aspects of the string behavior when it's not strictly defined by the Standard.
Enumerator:
BASIC_STRING_DEALLOCATE_IN_CLEAR
BASIC_STRING_HONOR_SHRINK_REQUEST
Function Documentation
template<typename CHAR_TYPE, typename SIZE_TYPE> bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::BSLMF_ASSERT (SHORT_BUFFER_BYTES >= sizeofCHAR_TYPE *) [inherited]
template<typename CHAR_TYPE, typename SIZE_TYPE> bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::BSLMF_NESTED_TRAIT_DECLARATION (String_Imp< CHAR_TYPE, SIZE_TYPE > , BloombergLP::bslmf::IsBitwiseMoveable) [inherited]
CHAR_TYPE is required to be a POD as per the Standard, which makes CHAR_TYPE bitwise-moveable, so String_Imp is also bitwise-moveable.
template<typename CHAR_TYPE , typename SIZE_TYPE> SIZE_TYPE bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::computeNewCapacity (SIZE_TYPE newLength, SIZE_TYPE oldCapacity, SIZE_TYPE maxSize) [static, inherited]
Compute and return the capacity required for a string having the specified newLength and using the specified oldCapacity to exercise an exponential capacity growth necessary to ensure the amortized linear complexity of push_back and other operations and ensuring that the new capacity does not exceed the specified maxSize. Note that the behavior is undefined unless newLength > oldCapacity, newLength < maxSize, and oldCapacity < maxSize.
References BSLS_ASSERT_SAFE.
template<typename CHAR_TYPE , typename SIZE_TYPE > bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::String_Imp () [inherited]
Create a String_Imp object having (default) attribute values except that the d_capacity attribute is initialized with SHORT_BUFFER_CAPACITY.
template<typename CHAR_TYPE , typename SIZE_TYPE> bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::String_Imp (SIZE_TYPE length, SIZE_TYPE capacity) [inherited]
Create a String_Imp object and initialize the d_length and d_capacity attributes with the specified length and specified capacity, respectively. If capacity is less then SHORT_BUFFER_CAPACITY then d_capacity is set to SHORT_BUFFER_CAPACITY. The value of the d_short and d_start_p fields are left uninitialized. basic_string is required to assign either d_short or d_start_p to a proper value before using any methods of this class.
template<typename CHAR_TYPE, typename SIZE_TYPE> bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::String_Imp (const String_Imp< CHAR_TYPE, SIZE_TYPE > & original) [inherited]
Create a String_Imp object having the same value as the specified original object. Note that this copy constructor is generated by the compiler.
template<typename CHAR_TYPE, typename SIZE_TYPE> bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::~String_Imp () [inherited]
Destroy this object. Note that this destructor is generated by the compiler.
template<typename CHAR_TYPE, typename SIZE_TYPE> String_Imp& bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::operator= (const String_Imp< CHAR_TYPE, SIZE_TYPE > & rhs) [inherited]
Assign to this object the value of the specified rhs object, and return a reference providing modifiable access to this object. Note that this assignment operator is generated by the compiler.
template<typename CHAR_TYPE , typename SIZE_TYPE > void bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::swap (String_Imp< CHAR_TYPE, SIZE_TYPE > & other) [inherited]
Efficiently exchange the value of this object with the value of the specified other object. This method provides the no-throw exception-safety guarantee.
References bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::d_capacity, bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::d_length, bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::d_start_p, and bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::isShortString().
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::swap().
template<typename CHAR_TYPE , typename SIZE_TYPE > void bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::resetFields () [inline, inherited]
Reset all fields of this object to their default-constructed state.
References bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::d_capacity, bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::d_length, and bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::d_start_p.
template<typename CHAR_TYPE , typename SIZE_TYPE > CHAR_TYPE * bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::dataPtr () [inline, inherited]
Return an address providing modifiable access to the NULL-terminated C-string stored by this string object. Note that the returned address can point to either the internal short string buffer or the externally allocated memory depending on the type of the string defined by the return value of isShortString.
References bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::d_short, bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::d_start_p, and bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::isShortString().
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::compare().
template<typename CHAR_TYPE , typename SIZE_TYPE > bool bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::isShortString () const [inline, inherited]
Return true if this object contains a short string and the string data is stored in the short string buffer, and false if the object contains a long string (and the short string buffer contains a pointer to the string data allocated externally).
References bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::d_capacity.
Referenced by bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::dataPtr(), and bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::swap().
template<typename CHAR_TYPE , typename SIZE_TYPE > const CHAR_TYPE * bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::dataPtr () const [inline, inherited]
Return an address providing non-modifiable access to the NULL-terminated C-string stored by this string object. Note that the returned address can point to either the internal short string buffer or the externally allocated memory depending on the type of the string defined by the return value of isShortString.
References bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::d_short, bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::d_start_p, and bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::isShortString().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::basic_string (const ALLOCATOR & allocator = ALLOCATOR()) [inline, explicit, inherited]
Create an empty string. Optionally specify an allocator used to supply memory. If allocator is not specified, a default-constructed allocator is used.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::basic_string (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & original) [inherited]
References bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::isShortString().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::basic_string (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & original, const ALLOCATOR & allocator) [inherited]
Create a string that has the same value as the specified original string. Optionally specify an allocator used to supply memory. If allocator is not specified, then a default-constructed allocator is used. Note that it is important to have two copy constructors instead of a single:
          basic_string(const basic_string& original,
                       const ALLCOATOR&    allocator = ALLOCATOR());
When the copy constructor with the default allocator is used, xlC10 get confused and refuses to use the return value optimization, which then causes extra allocations when returning by value in operator+.
References bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::isShortString().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::basic_string (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & original, size_type position, size_type numChars = npos, const ALLOCATOR & allocator = ALLOCATOR()) [inherited]
Create a string that has the same value as the substring of the optionally specified numChars length starting at the specified position in the specified original string. If numChars equals npos, then the remaining length of the string is used (i.e., numChars is set to original.length() - position). Optionally specify an allocator used to supply memory. If allocator is not specified, a default-constructed allocator is used. Throw out_of_range if position > original.length() or numChars != npos and position + numChars < original.length().
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::basic_string (const CHAR_TYPE * characterString, const ALLOCATOR & allocator = ALLOCATOR()) [inherited]
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign(), and BSLS_ASSERT_SAFE.
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::basic_string (const CHAR_TYPE * characterString, size_type numChars, const ALLOCATOR & allocator = ALLOCATOR()) [inherited]
Create a string that has the same value as the substring of the optionally specified numChars length starting at the specified position in the specified characterString. If numChars is not specified, CHAR_TRAITS::length(characterString) is used. Optionally specify an allocator used to supply memory. If allocator is not specified, a default-constructed allocator is used. Throw out_of_range if numChars >= npos.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign(), and BSLS_ASSERT_SAFE.
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::basic_string (size_type numChars, CHAR_TYPE character, const ALLOCATOR & allocator = ALLOCATOR()) [inherited]
Create a string of the specified numChars length whose every position contains the specified character. Optionally specify an allocator used to supply memory. If allocator is not specified, a default-constructed allocator is used.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > template<typename INPUT_ITER > bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::basic_string (INPUT_ITER first, INPUT_ITER last, const ALLOCATOR & allocator = ALLOCATOR()) [inline, inherited]
Create a string from the characters in the range starting at the specified first and ending at the specified last iterators of the parameterized INPUT_ITER type. Optionally specify an allocator used to supply memory. If allocator is not specified, a default-constructed allocator is used. The behavior is undefined unless [first, last) is a valid iterator range.
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > template<typename ALLOC2 > bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::basic_string (const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > & original, const ALLOCATOR & allocator = ALLOCATOR()) [inherited]
Create a string that has the same value as the specified original string, where the type original is the string type native to the compiler's library, instantiated with the same character type and traits type, but not necessarily the same allocator type. The resulting string will contain the same sequence of characters as original. Optionally specify an allocator used to supply memory. If allocator is not specified, then a default-constructed allocator is used.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::basic_string (const BloombergLP::bslstl::StringRefData< CHAR_TYPE > & strRef, const ALLOCATOR & allocator = ALLOCATOR()) [inline, inherited]
Create a string that has the same value as the specified strRef string. The resulting string will contain the same sequence of characters as strRef. Optionally specify an allocator used to supply memory. If allocator is not specified, then a default-constructed allocator is used.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::~basic_string () [inherited]
Destroy this string object.
References bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::d_length, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::npos.
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::operator= (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & rhs) [inherited]
Assign to this string the value of the specified rhs string, and return a reference providing modifiable access to this object.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::npos.
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::operator= (const CHAR_TYPE * rhs) [inherited]
Assign to this string the value of the specified rhs string, and return a reference providing modifiable access to this object.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign(), and BSLS_ASSERT_SAFE.
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::operator= (CHAR_TYPE character) [inherited]
Assign to this string the value of the string of length one consisting of the specified character, and return a reference providing modifiable access to this object.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > void bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::resize (size_type newLength, CHAR_TYPE character) [inherited]
Change the length of this string to the specified newLength, erasing characters at the end if newLength < length() or appending the appropriate number of copies of the specified character at the end if length() < newLength.
References BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > void bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::resize (size_type newLength) [inherited]
Change the length of this string to the specified newLength, erasing characters at the end if newLength < length() or appending the appropriate number of copies of the specified character at the end if length() < newLength.
References BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > void bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::reserve (size_type newCapacity = 0) [inherited]
Change the capacity of this string to the specified newCapacity. Note that the capacity of a string is the maximum length it can accommodate without reallocation. The actual storage allocated may be higher.
References BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size().
Referenced by bsl::operator+(), and bsl::operator>>().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > void bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::clear () [inherited]
Reset this string to an empty value. Note that the capacity may change (or not if BASIC_STRING_DEALLOCATE_IN_CLEAR is false). Note that the Standard doesn't allow to reduce capacity on clear.
References bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::BASIC_STRING_DEALLOCATE_IN_CLEAR.
Referenced by bsl::getline(), and bsl::operator>>().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::iterator bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin () [inline, inherited]
Return an iterator referring to the first character in this modifiable string (or the past-the-end iterator if this string is empty).
References bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::dataPtr().
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::at(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::back(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::basic_string(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cbegin(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::crend(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::end(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::erase(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::front(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::insert(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::operator[](), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::pop_back(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::push_back(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rend(), and bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::str().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::iterator bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::end () [inline, inherited]
Return the past-the-end iterator for this modifiable string.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin(), and bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::d_length.
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::back(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cend(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::crbegin(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rbegin().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::reverse_iterator bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rbegin () [inline, inherited]
Return a reverse iterator referring to the last character in this modifiable string (or the past-the-end reverse iterator if this string is empty).
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::end().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::reverse_iterator bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rend () [inline, inherited]
Return the past-the-end reverse iterator for this modifiable string.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::reference bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::operator[] (size_type position) [inline, inherited]
Return a reference providing modifiable access to the character at the specified position in this string if position < length(), or a reference providing non-modifiable access to the null-terminating character if position == length(). The behavior is undefined unless position <= length(), and, in the case of position == length(), the null-terminating character is not modified through the returned reference.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin(), BSLS_ASSERT_SAFE, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::reference bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::at (size_type position) [inherited]
Return a reference providing modifiable access to the character at the specified position in this string. Throw out_of_range if position >= length().
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin(), BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::reference bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::front () [inline, inherited]
Return a reference providing modifiable access to the character at the first position in this string. The behavior is undefined if this string is empty.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin(), BSLS_ASSERT_SAFE, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::empty().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::reference bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::back () [inline, inherited]
Return a reference providing modifiable access to the character at the last position in this string. The behavior is undefined if this string is empty. Note that the last position is length() - 1.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin(), BSLS_ASSERT_SAFE, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::empty(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > template<typename ALLOC2 > bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::operator native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > () const [inline, inherited]
Convert this object to a string type native to the compiler's library, instantiated with the same character type and traits type, but not necessarily the same allocator type. The return string will contain the same sequence of characters as orig and will have a default-constructed allocator. Note that this conversion operator can be invoked implicitly (e.g., during argument passing).
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::operator+= (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & string) [inherited]
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::append().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::operator+= (const CHAR_TYPE * string) [inherited]
Append the specified string at the end of this string, and return a reference providing modifiable access to this string.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::append(), and BSLS_ASSERT_SAFE.
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::operator+= (CHAR_TYPE character) [inherited]
Append the specified character at the end of this string, and return a reference providing modifiable access to this string.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::push_back().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::append (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & string) [inherited]
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::npos.
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::append(), bsl::operator+(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::operator+=(), and bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::xsputn().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::append (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & string, size_type position, size_type numChars) [inherited]
Append at the end of this string the first specified numChars characters starting at the specified position in the specified string, or the suffix of string starting at position if position + numChars is larger than the length of string. Return a reference providing modifiable access to this string. Throw out_of_range if position > string.length().
References BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::append (const CHAR_TYPE * characterString, size_type numChars) [inherited]
Append at the end of this string the specified numChars characters from the array starting at the specified characterString address, and return a reference to this modifiable string.
References BSLS_ASSERT_SAFE, BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::append (const CHAR_TYPE * characterString) [inherited]
Append the specified characterString (of length CHAR_TRAITS::length(characterString)) at the end of this string, and return a reference providing modifiable access to this string.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::append(), and BSLS_ASSERT_SAFE.
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::append (size_type numChars, CHAR_TYPE character) [inherited]
Append a number equal to the specified numChars of copies of the specified character at the end of this string, and return a reference providing modifiable access to this string.
References BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::d_length, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > template<typename INPUT_ITER > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::append (INPUT_ITER first, INPUT_ITER last) [inline, inherited]
Append to the end of this string a string built from the characters in the range starting at the specified first and ending before the specified last iterators of the iterator, const_iterator or parameterized INPUT_ITER type, respectively. Return a reference providing modifiable access to this string. The behavior is undefined unless [first, last) is a valid iterator range.
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > void bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::push_back (CHAR_TYPE character) [inherited]
Append the specified character at the end of this string.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin(), BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::capacity(), bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::d_length, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size().
Referenced by bsl::getline(), bsl::operator+(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::operator+=(), bsl::operator>>(), and bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::overflow().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & string) [inherited]
Assign to this string the value of the specified string, and return a reference providing modifiable access to this string.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::npos.
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::basic_string(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::erase(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::operator=(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::pop_back(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::push_back().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & string, size_type position, size_type numChars) [inherited]
Assign to this string the value of the substring of the specified numChars length or string.length() - position, whichever is smaller, starting at the specified position in the specified string, and return a reference providing modifiable access to this string. Throw out_of_range if position > string.length().
References BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::d_length, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign (const CHAR_TYPE * characterString) [inherited]
Assign to this string the value of the specified null-terminated characterString, and return a reference providing modifiable access to this string.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign(), and BSLS_ASSERT_SAFE.
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign (const CHAR_TYPE * characterString, size_type numChars) [inherited]
Assign to this string the value of the string constructed from the specified numChars characters in the array starting at the specified characterString address, and return a reference providing modifiable access to this string.
References BSLS_ASSERT_SAFE, BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::d_length, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign (size_type numChars, CHAR_TYPE character) [inherited]
Assign to this string the value of a string of the specified numChars length whose every characters equal the specified character, and return a reference providing modifiable access to this string.
References BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::d_length, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > template<typename INPUT_ITER > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign (INPUT_ITER first, INPUT_ITER last) [inline, inherited]
Assign to this string the value of a string built from the characters in the range starting at the specified first and ending before the specified last iterators of the iterator, const_iterator or parameterized INPUT_ITER type, respectively. Return a reference providing modifiable access to this string. The behavior is undefined unless [first, last) is a valid iterator range.
References bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::d_length.
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::insert (size_type position, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & string) [inherited]
Insert at the specified position in this string a copy of the specified string, and return a reference providing modifiable access to this string. Throw out_of_range if position > length().
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::npos.
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::insert().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::insert (size_type outPosition, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & string, size_type position, size_type numChars) [inherited]
Insert at the specified outPosition in this string a copy of the substring of the specified numChars length or string.length() - position, whichever is smaller, starting at the specified position in the specified string, and return a reference providing modifiable access to this string. Throw out_of_range if position > length().
References BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::insert (size_type position, const CHAR_TYPE * characterString, size_type numChars) [inherited]
Insert at the specified position in this string a copy of the string constructed from the specified numChars characters in the array starting at the specified characterString address, and return a reference providing modifiable access to this string. Throw out_of_range if position > length().
References BSLS_ASSERT_SAFE, BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::insert (size_type position, const CHAR_TYPE * characterString) [inherited]
Insert at the specified position in this string a copy of the string constructed from the specified characterString (of length CHAR_TRAITS::length(characterString)), and return a reference providing modifiable access to this string. Throw out_of_range if position > length().
References BSLS_ASSERT_SAFE, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::insert().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::insert (size_type position, size_type numChars, CHAR_TYPE character) [inherited]
Insert at the specified position in this string a number equal to the specified numChars of copies of the specified character, and return a reference providing modifiable access to this string. Throw out_of_range if position > length().
References BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::iterator bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::insert (const_iterator position, CHAR_TYPE character) [inherited]
Insert at the specified position in this string a copy of the specified character, and return an iterator providing modifiable access to the inserted character. The behavior is undefined unless position is a valid iterator on this string.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin(), BSLS_ASSERT_SAFE, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cbegin(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cend(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::insert().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::iterator bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::insert (const_iterator position, size_type numChars, CHAR_TYPE character) [inline, inherited]
Insert at the specified position in this string a specified numChars number of copies of the specified character, and return an iterator providing modifiable access to the first inserted character, or a non-const copy of the position iterator, if numChars == 0. The behavior is undefined unless position is a valid iterator on this string.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin(), BSLS_ASSERT_SAFE, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cbegin(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cend(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::insert().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > template<typename INPUT_ITER > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::iterator bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::insert (const_iterator position, INPUT_ITER first, INPUT_ITER last) [inline, inherited]
Insert at the specified position in this string a string built from the characters in the range starting at the specified first and ending before the specified last iterators, and return an iterator providing modifiable access to the first inserted character, or a non-const copy of the position iterator, if first == last. The behavior is undefined unless position is a valid iterator on this string and [first, last) is a valid iterator range.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin(), BSLS_ASSERT_SAFE, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cbegin(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cend().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::erase (size_type position = 0, size_type numChars = npos) [inherited]
Erase from this string the substring of length the optionally specified numChars or original.length() - position, whichever is smaller, starting at the optionally specified position. If position is not specified, the first position is used (i.e., position is set to 0). Return a reference providing modifiable access to this string. Note that if numChars equals npos, then the remaining length of the string is erased (i.e., numChars is set to length() - position). Throw out_of_range if position > length().
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin(), BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::d_length, bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::dataPtr(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::iterator bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::erase (const_iterator position) [inherited]
Erase a character at the specified position from this string, and return an iterator providing modifiable access to the character at position prior to erasing. If no such character exists, return end(). The behavior is undefined unless position belongs to the half-open range [cbegin(), cend()).
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin(), BSLS_ASSERT_SAFE, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cbegin(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cend(), bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::d_length, bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::dataPtr(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::iterator bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::erase (const_iterator first, const_iterator last) [inherited]
Erase from this string a substring defined by the pair of first and last iterators within this string. Return an iterator providing modifiable access to the the character at the last position prior to erasing. If no such character exists, return end(). The behavior is undefined unless first and last both belong to [cbegin(), cend()] and first <= last. Note that this call invalidates existing iterators pointing to first or a subsequent position.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin(), BSLS_ASSERT_SAFE, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cbegin(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cend(), bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::d_length, bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::dataPtr(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > void bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::pop_back () [inline, inherited]
Erase the last character from this string. The behavior is undefined if this string is empty.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin(), BSLS_ASSERT_SAFE, bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::d_length, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::empty(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::replace (size_type outPosition, size_type outNumChars, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & string) [inherited]
Replace the substring of this string starting at the specified outPosition of length outNumChars or length() - outPosition, whichever is smaller, by the specified string, and return a reference providing modifiable access to this string. Throw out_of_range if outPosition > length().
References BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size().
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::replace().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::replace (size_type outPosition, size_type outNumChars, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & string, size_type position, size_type numChars) [inherited]
Replace the substring of this string starting at the specified outPosition of length outNumChars or length() - outPosition, whichever is smaller, by the substring of the specified numChars length or string.length() - position, whichever is smaller, starting at the specified position in the specified string. Return a reference providing modifiable access to this string. Throw out_of_range if outPosition > length() or position > string.length().
References BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::replace (size_type outPosition, size_type outNumChars, const CHAR_TYPE * characterString, size_type numChars) [inherited]
Replace the substring of this string starting at the specified outPosition of length outNumChars or length() - outPosition, whichever is smaller, by a copy of the string constructed from the specified numChars characters in the array starting at the specified characterString address. Return a reference providing modifiable access to this string. Throw out_of_range if outPosition > length().
References BSLS_ASSERT_SAFE, BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::replace (size_type outPosition, size_type outNumChars, const CHAR_TYPE * characterString) [inherited]
Replace the substring of this string starting at the specified outPosition of length outNumChars or length() - outPosition, whichever is smaller, by the null-terminated specified characterString (of length CHAR_TRAITS::length(characterString)). Return a reference providing modifiable access to this string. Throw out_of_range if outPosition > length().
References BSLS_ASSERT_SAFE, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::replace().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::replace (size_type outPosition, size_type outNumChars, size_type numChars, CHAR_TYPE character) [inherited]
Replace the substring of this string starting at the specified outPosition of length outNumChars or length() - outPosition, whichever is smaller, by a number equal to the specified numChars of copies of the specified character. Return a reference providing modifiable access to this string. Throw out_of_range if outPosition > length().
References BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::replace (const_iterator first, const_iterator last, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & string) [inherited]
Replace the substring in the range starting at the specified first position and ending right before the specified last position, by the specified string. Return a reference providing modifiable access to this string. The behavior is undefined unless first and last both belong to [cbegin(), cend()] and first <= last.
References BSLS_ASSERT_SAFE, BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cbegin(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cend(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::replace (const_iterator first, const_iterator last, const CHAR_TYPE * characterString, size_type numChars) [inherited]
Replace the substring in the range starting at the specified first position and ending right before the specified last position, by a copy of the string constructed from the specified numChars characters in the array starting at the specified characterString address. Return a reference providing modifiable access to this string. The behavior is undefined unless first and last both belong to [cbegin(), cend()] and first <= last.
References BSLS_ASSERT_SAFE, BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cbegin(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cend(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::replace (const_iterator first, const_iterator last, const CHAR_TYPE * characterString) [inherited]
Replace the substring in the range starting at the specified first position and ending right before the specified last position, by the null-terminated specified characterString. Return a reference providing modifiable access to this string. The behavior is undefined unless first and last both belong to the range [cbegin(), cend()] and first <= last.
References BSLS_ASSERT_SAFE, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cbegin(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cend(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::replace().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::replace (const_iterator first, const_iterator last, size_type numChars, CHAR_TYPE character) [inherited]
Replace the substring in the range starting at the specified first position and ending right before the specified last position, by a number equal to the specified numChars of copies of the specified character. Return a reference providing modifiable access to this string. The behavior is undefined unless first and last both belong to the range [cbegin(), cend()] and first <= last.
References BSLS_ASSERT_SAFE, BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cbegin(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cend(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > template<typename INPUT_ITER > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::replace (const_iterator first, const_iterator last, INPUT_ITER stringFirst, INPUT_ITER stringLast) [inline, inherited]
Replace the substring in the range starting at the specified first position and ending right before the specified last position, by a string built from the characters in the range starting at the specified stringFirst and ending before the specified stringLast iterators of the iterator, const_iterator, or parameterized INPUT_ITER type, respectively. Return a reference providing modifiable access to this string. The behavior is undefined unless first and last both belong to the range [cbegin(), cend()], first <= last and [stringFirst, stringLast) is a valid iterator range.
References BSLS_ASSERT_SAFE, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cbegin(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cend().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > void bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::swap (basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & other) [inherited]
Exchange the value of this string with that of the specified string, so that the value of this string upon return equals that of other prior to this call, and vice-versa.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::get_allocator(), and bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::swap().
Referenced by bsl::swap().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::const_iterator bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin () const [inline, inherited]
References bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::dataPtr().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::const_iterator bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cbegin () const [inline, inherited]
Return an iterator providing non-modifiable access to the first character of this string (or the past-the-end iterator if this string is empty).
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin().
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::erase(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::insert(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::replace().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::const_iterator bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::end () const [inline, inherited]
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin(), and bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::d_length.
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::const_iterator bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::cend () const [inline, inherited]
Return the past-the-end iterator for this string.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::end().
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::erase(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::insert(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::replace().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::const_reverse_iterator bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rbegin () const [inline, inherited]
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::end().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::const_reverse_iterator bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::crbegin () const [inline, inherited]
Return a reverse iterator providing non-modifiable access to the last character of this string (or the past-the-end reverse iterator if this string is empty).
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::end().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::const_reverse_iterator bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rend () const [inherited]
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::const_reverse_iterator bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::crend () const [inherited]
Return the past-the-end reverse iterator for this string.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length () const [inline, inherited]
Return the length of this string. Note that this number may differ from CHAR_TRAITS::length(c_str()) in case the string contains null characters. Also note that a null-terminating character added by the c_str method is not counted in this length.
References bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::d_length.
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::append(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::at(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::back(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::compare(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::copy(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::erase(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_first_not_of(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_first_of(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_last_not_of(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_last_of(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::insert(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::operator native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 >(), bsl::operator+(), bsl::operator<(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::operator[](), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::pop_back(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::push_back(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::replace(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rfind().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size () const [inline, inherited]
Return the length of this string. Note that this number may differ from CHAR_TRAITS::length(c_str()) in case the string contains null characters. Also note that a null-terminating character added by the c_str method is not counted in this length.
References bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::d_length.
Referenced by bsl::hashBasicString(), bsl::operator==(), bsl::operator>>(), bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::overflow(), bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::str(), bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::xsputn(), and bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::~basic_stringbuf().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size () const [inline, inherited]
Return the maximal possible length of this string. Note that requests to create a string longer than this number of characters is guaranteed to raise a length_error exception.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::get_allocator().
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::append(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign(), bsl::getline(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::insert(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::push_back(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::replace(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::reserve(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::resize().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::capacity () const [inline, inherited]
Return the capacity of this string, i.e., the maximum length for which resizing is guaranteed not to trigger a reallocation.
References bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::d_capacity.
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::push_back().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > bool bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::empty () const [inline, inherited]
Return true if this string has length 0, and false otherwise.
References bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::d_length.
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::back(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::front(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::pop_back().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::const_reference bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::operator[] (size_type position) const [inline, inherited]
Return a reference providing non-modifiable access to the character at the specified position in this string. The behavior is undefined unless position <= length(). Note that if position == length(), a reference to the null-terminating character is returned.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin(), BSLS_ASSERT_SAFE, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::const_reference bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::at (size_type position) const [inherited]
Return a reference providing non-modifiable access to the character at the specified position in this string. Throw out_of_range if position >= length().
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin(), BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::const_reference bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::front () const [inline, inherited]
Return a reference providing non-modifiable access to the character at the first position in this string. The behavior is undefined if this string is empty.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::begin(), BSLS_ASSERT_SAFE, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::empty().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::const_reference bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::back () const [inline, inherited]
Return a reference providing non-modifiable access to the character at the last position in this string. The behavior is undefined if this string is empty. Note that the last position is length() - 1.
References BSLS_ASSERT_SAFE, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::empty(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::end().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::copy (CHAR_TYPE * characterString, size_type numChars, size_type position = 0) const [inherited]
Copy the specified numChars or length() - position, whichever is smaller, characters from this string into the specified characterString buffer, and return the number of characters copied. Throw out_of_range if position > length(). Note that the output characterString is not null-terminated.
References BSLS_ASSERT_SAFE, BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::dataPtr(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::const_pointer bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::c_str () const [inline, inherited]
Return an address providing non-modifiable access to the null-terminated buffer of length() + 1 characters whose contents are identical to the value of this string. Note that any call to the string destructor or any of its manipulators invalidates the returned pointer.
References bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::dataPtr().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::const_pointer bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data () const [inline, inherited]
Return an address providing non-modifiable access to the null-terminated buffer of length() characters whose contents are identical to the value of this string. Note that any call to the string destructor or any of its manipulators invalidates the returned pointer.
References bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::dataPtr().
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::append(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::compare(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_first_not_of(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_first_of(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_last_not_of(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_last_of(), bsl::hashBasicString(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::insert(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::operator native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 >(), bsl::operator<(), bsl::operator==(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::replace(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rfind(), bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::xsputn(), and bsl::basic_stringbuf< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::~basic_stringbuf().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::allocator_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::get_allocator () const [inline, inherited]
Return the allocator used by this string to supply memory.
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size(), bsl::swap(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::swap().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & string, size_type position = 0) const [inherited]
Return the starting position of the first occurrence of a substring whose value equals that of the specified string, if such a substring can be found in this string (on or after the optionally specified position if such a position is specified), and return npos otherwise.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find (const CHAR_TYPE * string, size_type position, size_type numChars) const [inherited]
References BSLS_ASSERT_SAFE, bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::dataPtr(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::npos.
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find (const CHAR_TYPE * string, size_type position = 0) const [inherited]
Return the starting position of the first occurrence of a substring whose value equals that of the specified characterString of the optionally specified numChars length, if such a substring can be found in this string (on or after the optionally specified position if such a position is specified), and return npos otherwise. If numChars is not specified, CHAR_TRAITS::length(characterString) is used.
References BSLS_ASSERT_SAFE, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find (CHAR_TYPE character, size_type position = 0) const [inherited]
Return the position of the first occurrence of the specified character, if such an occurrence can be found in this string (on or after the optionally specified position if such a position is specified), and return npos otherwise.
References bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::dataPtr(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::npos.
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rfind (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & string, size_type position = npos) const [inherited]
Return the starting position of the last occurrence of a substring whose value equals that of the specified string, if such a substring can be found in this string (on or before the optionally specified position if such a position is specified), and return npos otherwise.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rfind().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rfind (const CHAR_TYPE * characterString, size_type position, size_type numChars) const [inherited]
References BSLS_ASSERT_SAFE, bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::dataPtr(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::npos.
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rfind (const CHAR_TYPE * characterString, size_type position = npos) const [inherited]
Return the starting position of the last occurrence of a substring whose value equals that of the specified characterString of the optionally specified numChars length, if such a substring can be found in this string (on or before the optionally specified position if such a position is specified), and return npos otherwise. If numChars is not specified, CHAR_TRAITS::length(characterString) is used.
References BSLS_ASSERT_SAFE, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rfind().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rfind (CHAR_TYPE character, size_type position = npos) const [inherited]
Return the position of the last occurrence of the specified character, if such an occurrence can be found in this string (on or before the optionally specified position if such a position is specified), and return npos otherwise.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rfind().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_first_of (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & string, size_type position = 0) const [inherited]
Return the position of the first occurrence of a character belonging to the specified string, if such an occurrence can be found in this string (on or after the optionally specified position if such a position is specified), and return npos otherwise.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_first_of().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_first_of (const CHAR_TYPE * characterString, size_type position, size_type numChars) const [inherited]
References BSLS_ASSERT_SAFE, bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::dataPtr(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::npos.
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_first_of (const CHAR_TYPE * characterString, size_type position = 0) const [inherited]
Return the position of the first occurrence of a character belonging to the specified characterString of the optionally specified numChars length, if such an occurrence can be found in this string (on or after the optionally specified position if such a position is specified), and return npos otherwise. If numChars is not specified, CHAR_TRAITS::length(characterString) is used.
References BSLS_ASSERT_SAFE, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_first_of().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_first_of (CHAR_TYPE character, size_type position = 0) const [inherited]
Return the position of the first occurrence of the specified character, if such an occurrence can be found in this string (on or after the optionally specified position if such a position is specified), and return npos otherwise.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_first_of().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_last_of (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & string, size_type position = npos) const [inherited]
Return the position of the last occurrence of a character belonging to the specified string, if such an occurrence can be found in this string (on or before the optionally specified position if such a position is specified), and return npos otherwise.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_last_of().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_last_of (const CHAR_TYPE * characterString, size_type position, size_type numChars) const [inherited]
References BSLS_ASSERT_SAFE, bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::dataPtr(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::npos.
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_last_of (const CHAR_TYPE * characterString, size_type position = npos) const [inherited]
Return the position of the last occurrence of a character belonging to the specified characterString of the optionally specified numChars length, if such an occurrence can be found in this string (on or before the optionally specified position if such a position is specified), and return npos otherwise. If numChars is not specified, CHAR_TRAITS::length(characterString) is used.
References BSLS_ASSERT_SAFE, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_last_of().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_last_of (CHAR_TYPE character, size_type position = npos) const [inherited]
Return the position of the last occurrence of the specified character, if such an occurrence can be found in this string (on or before the optionally specified position if such a position is specified), and return npos otherwise.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_last_of().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_first_not_of (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & string, size_type position = 0) const [inherited]
Return the position of the first occurrence of a character not belonging to the specified string, if such an occurrence can be found in this string (on or after the optionally specified position if such a position is specified), and return npos otherwise.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_first_not_of().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_first_not_of (const CHAR_TYPE * characterString, size_type position, size_type numChars) const [inherited]
References BSLS_ASSERT_SAFE, bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::dataPtr(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::npos.
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_first_not_of (const CHAR_TYPE * characterString, size_type position = 0) const [inherited]
Return the position of the first occurrence of a character not belonging to the specified characterString of the optionally specified numChars length, if such an occurrence can be found in this string (on or after the optionally specified position if such a position is specified), and return npos otherwise. If numChars is not specified, CHAR_TRAITS::length(characterString) is used.
References BSLS_ASSERT_SAFE, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_first_not_of().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_first_not_of (CHAR_TYPE character, size_type position = 0) const [inherited]
Return the position of the first occurrence of a character different from the specified character, if such an occurrence can be found in this string (on or after the optionally specified position if such a position is specified), and return npos otherwise.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_first_not_of().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_last_not_of (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & string, size_type position = npos) const [inherited]
Return the position of the last occurrence of a character not belonging to the specified string, if such an occurrence can be found in this string (on or before the optionally specified position if such a position is specified), and return npos otherwise.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_last_not_of().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_last_not_of (const CHAR_TYPE * characterString, size_type position, size_type numChars) const [inherited]
References BSLS_ASSERT_SAFE, bsl::String_Imp< CHAR_TYPE, ALLOCATOR::size_type >::dataPtr(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::npos.
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_last_not_of (const CHAR_TYPE * characterString, size_type position = npos) const [inherited]
Return the position of the last occurrence of a character not belonging to the specified characterString of the optionally specified numChars length, if such an occurrence can be found in this string (on or before the optionally specified position if such a position is specified), and return npos otherwise. If numChars is not specified, CHAR_TRAITS::length(characterString) is used.
References BSLS_ASSERT_SAFE, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_last_not_of().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_last_not_of (CHAR_TYPE character, size_type position = npos) const [inherited]
Return the position of the last occurrence of a character different from the specified character, if such an occurrence can be found in this string (on or before the optionally specified position if such a position is specified), and return npos otherwise.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_last_not_of().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::substr (size_type position = 0, size_type numChars = npos) const [inherited]
Return a string whose value is the substring of length the optionally specified numChars or length() - position, whichever is smaller, starting at the optionally specified position in this string. If position is not specified, 0 is used (i.e., the substring is from the beginning of this string). If numChars is not specified, npos is used (i.e., the entire suffix from position to the end of the string is returned).
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > int bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::compare (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & other) const [inherited]
Lexicographically compare this string with the specified other string (using CHAR_TRAITS::lt to compare characters), and return a negative value if this string is less than other, a positive value if it is more than other, and 0 in case of equality. See "Lexicographical Comparisons" for definitions.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::compare().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > int bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::compare (size_type position, size_type numChars, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & other) const [inherited]
Lexicographically compare the substring of this string starting at the specified lhsPosition of length lhsNumChars or length() - lhsPosition, whichever is smaller, with the specified other string (using CHAR_TRAITS::lt to compare characters), and return a negative value if this string is less than other, a positive value if it is more than other, and 0 in case of equality. See "Lexicographical Comparisons" for definitions.
References BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > int bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::compare (size_type lhsPosition, size_type lhsNumChars, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & other, size_type otherPosition, size_type otherNumChars) const [inherited]
Lexicographically compare the substring of this string starting at the specified lhsPosition of length lhsNumChars or length() - lhsPosition, whichever is smaller, with the substring of the specified other string starting at the specified otherPosition of length otherNumChars or length() - otherPosition, whichever is smaller, (using CHAR_TRAITS::lt to compare characters), and return a negative value if this string is less than other, a positive value if it is more than other, and 0 in case of equality. Throw out_of_range if lhsPosition > length() or otherPosition > other.length(). See "Lexicographical Comparisons" for definitions.
References BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::dataPtr(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > int bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::compare (const CHAR_TYPE * other) const [inherited]
Lexicographically compare this string with the null-terminated specified other string (of length CHAR_TRAITS::length(other), using CHAR_TRAITS::lt to compare characters), and return a negative value if this string is less than other, a positive value if it is more than other, and 0 in case of equality. See "Lexicographical Comparisons" for definitions.
References BSLS_ASSERT_SAFE, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > int bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::compare (size_type lhsPosition, size_type lhsNumChars, const CHAR_TYPE * other, size_type otherNumChars) const [inherited]
Lexicographically compare the substring of this string starting at the specified lhsPosition of length lhsNumChars or length() - lhsPosition, whichever is smaller, with the string constructed from the specified numChars characters in the array starting at the specified characterString address, and return a negative value if this string is less than other, a positive value if it is more than other, and 0 in case of equality. Throw out_of_range if lhsPosition > length(). See "Lexicographical Comparisons" for definitions.
References BSLS_ASSERT_SAFE, BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > int bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::compare (size_type lhsPosition, size_type lhsNumChars, const CHAR_TYPE * other) const [inherited]
Lexicographically compare the substring of this string starting at the specified lhsPosition of length lhsNumChars or length() - lhsPosition, whichever is smaller, with the null-terminated specified other string (of length CHAR_TRAITS::length(other), using CHAR_TRAITS::lt to compare characters), and return a negative value if this string is less than other, a positive value if it is more than other, and 0 in case of equality. Throw out_of_range if lhsPosition > length(). See "Lexicographical Comparisons" for definitions.
References BSLS_ASSERT_SAFE, and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::compare().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC > bool bsl::operator== (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & rhs) [inline]
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 > bool bsl::operator== (const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > & lhs, const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > & rhs) [inline]
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 > bool bsl::operator== (const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > & lhs, const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > & rhs) [inline]
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC > bool bsl::operator== (const CHAR_TYPE * lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & rhs) [inline]
References BSLS_ASSERT_SAFE, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC > bool bsl::operator== (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & lhs, const CHAR_TYPE * rhs) [inline]
Return true if the specified lhs string has the same value as the specified rhs string, and false otherwise. Two strings have the same value if they have the same length, and the characters at each respective position have the same value according to CHAR_TRAITS::eq.
References BSLS_ASSERT_SAFE, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC > bool bsl::operator!= (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & rhs) [inline]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 > bool bsl::operator!= (const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > & lhs, const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > & rhs) [inline]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 > bool bsl::operator!= (const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > & lhs, const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > & rhs) [inline]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC > bool bsl::operator!= (const CHAR_TYPE * lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & rhs) [inline]
References BSLS_ASSERT_SAFE.
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC > bool bsl::operator!= (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & lhs, const CHAR_TYPE * rhs) [inline]
Return true if the specified lhs string has a different value from the specified rhs string, and false otherwise. Two strings have the same value if they have the same length, and the characters at each respective position have the same value according to CHAR_TRAITS::eq.
References BSLS_ASSERT_SAFE.
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC > bool bsl::operator< (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 > bool bsl::operator< (const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > & lhs, const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > & rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 > bool bsl::operator< (const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > & lhs, const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > & rhs)
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC > bool bsl::operator< (const CHAR_TYPE * lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & rhs)
References BSLS_ASSERT_SAFE, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC > bool bsl::operator< (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & lhs, const CHAR_TYPE * rhs)
Return true if the specified lhs string has a lexicographically smaller value than the specified rhs string, and false otherwise. See "Lexicographical Comparisons" for definitions.
References BSLS_ASSERT_SAFE.
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC > bool bsl::operator> (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & rhs) [inline]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 > bool bsl::operator> (const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > & lhs, const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > & rhs) [inline]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 > bool bsl::operator> (const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > & lhs, const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > & rhs) [inline]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC > bool bsl::operator> (const CHAR_TYPE * lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & rhs) [inline]
References BSLS_ASSERT_SAFE.
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC > bool bsl::operator> (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & lhs, const CHAR_TYPE * rhs) [inline]
Return true if the specified lhs string has a lexicographically larger value than the specified rhs string, and false otherwise. See "Lexicographical Comparisons" for definitions.
References BSLS_ASSERT_SAFE.
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC > bool bsl::operator<= (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & rhs) [inline]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 > bool bsl::operator<= (const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > & lhs, const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > & rhs) [inline]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 > bool bsl::operator<= (const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > & lhs, const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > & rhs) [inline]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC > bool bsl::operator<= (const CHAR_TYPE * lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & rhs) [inline]
References BSLS_ASSERT_SAFE.
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC > bool bsl::operator<= (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & lhs, const CHAR_TYPE * rhs) [inline]
Return true if the specified lhs string has a value lexicographically smaller than or or equal to the specified rhs string, and false otherwise. See "Lexicographical Comparisons" for definitions.
References BSLS_ASSERT_SAFE.
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC > bool bsl::operator>= (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & rhs) [inline]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 > bool bsl::operator>= (const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > & lhs, const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > & rhs) [inline]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 > bool bsl::operator>= (const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > & lhs, const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > & rhs) [inline]
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC > bool bsl::operator>= (const CHAR_TYPE * lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & rhs) [inline]
References BSLS_ASSERT_SAFE.
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC > bool bsl::operator>= (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC > & lhs, const CHAR_TYPE * rhs) [inline]
Return true if the specified lhs string has a value lexicographically larger than or equal to the specified rhs string, and false otherwise. See "Lexicographical Comparisons" for definitions.
References BSLS_ASSERT_SAFE.
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > bsl::operator+ (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & rhs)
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::reserve().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 > bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > bsl::operator+ (const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > & lhs, const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > & rhs)
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::append(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::reserve().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOC1 , class ALLOC2 > bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > bsl::operator+ (const bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC1 > & lhs, const native_std::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOC2 > & rhs)
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::append(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::reserve().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > bsl::operator+ (const CHAR_TYPE * lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & rhs)
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::append(), BSLS_ASSERT_SAFE, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::reserve().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > bsl::operator+ (CHAR_TYPE lhs, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & rhs)
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::push_back(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::reserve().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > bsl::operator+ (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & lhs, const CHAR_TYPE * rhs)
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::append(), BSLS_ASSERT_SAFE, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::reserve().
template<typename CHAR_TYPE , typename CHAR_TRAITS , typename ALLOCATOR > basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > bsl::operator+ (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & lhs, CHAR_TYPE rhs)
Return the concatenation of strings constructed from the specified lhs and rhs arguments, i.e., basic_string(lhs).append(rhs).
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::length(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::push_back(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::reserve().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > std::basic_ostream< CHAR_TYPE, CHAR_TRAITS > & bsl::operator<< (std::basic_ostream< CHAR_TYPE, CHAR_TRAITS > & os, const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & str)
Write the string specified by str into the output stream specified by os and return os. If the string is shorter than os.width(), then it is padded to os.width() with the current os.fill() character. The padding, if any, is output after the string (on the right) if os.flags() | ios::left is non-zero and before the string otherwise. This function will do nothing unless os.good() is true on entry.
References bsl::bslstl_string_fill().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > std::basic_istream< CHAR_TYPE, CHAR_TRAITS > & bsl::operator>> (std::basic_istream< CHAR_TYPE, CHAR_TRAITS > & is, basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & str)
Replace the contents of the specified str string with a word read from the specified is input stream and return is. The word begins at the first non-whitespace character on the input stream and ends when another whitespace character (or eof) is found. The trailing whitespace character is left on the input stream. If is.good() is not true on entry or if eof is found before any non-whitespace characters, then str is unchanged and is.fail() is becomes true. If eof is detected after some characters have been read into str, then is.eof() becomes true, but is.fail() does not.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::clear(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::push_back(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::reserve(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > void bsl::swap (basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & lhs, basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & rhs) [inline]
Exchange the values of the specified lhs and rhs strings in constant time without throwing an exception. The behavior is undefined unless lhs.get_allocator() == rhs.get_allocator().
References BSLS_ASSERT_SAFE, bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::get_allocator(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::swap().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > std::basic_istream< CHAR_TYPE, CHAR_TRAITS > & bsl::getline (std::basic_istream< CHAR_TYPE, CHAR_TRAITS > & is, basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & str, CHAR_TYPE delim)
Replace the contents of the specified str string by extracting characters from the specified is stream until the specified delim character is extracted and return is. The delim character is removed from the input stream but is not appended to str. If an eof is detected before delim, then the characters up to the eof are put into str and is.eof() becomes true. If is.good() is false on entry, then do nothing, otherwise if no characters are extracted (e.g., because because the stream is at eof), str will become empty and is.fail() will become true.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::clear(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::max_size(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::push_back().
Referenced by bsl::getline().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > std::basic_istream< CHAR_TYPE, CHAR_TRAITS > & bsl::getline (std::basic_istream< CHAR_TYPE, CHAR_TRAITS > & is, basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & str) [inline]
Replace the contents of the specified str string by extracting characters from the specified is stream until a newline character (is.widen(\n) is extracted and return is. The newline character is removed from the input stream but is not appended to str. If an eof is detected before the newline, then the characters up to the eof are put into str and is.eof() becomes true. If is.good() is false on entry, then do nothing, otherwise if no characters are extracted (e.g., because because the stream is at eof), str will become empty and is.fail() will become true.
References bsl::getline().
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > std::size_t bsl::hashBasicString (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & str)
Return a hash value for the specified str.
References bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::data(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size().
Referenced by bsl::hash< basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > >::operator()().
std::size_t bsl::hashBasicString (const string & str)
Return a hash value for the specified str.
template<class CHAR_TYPE , class CHAR_TRAITS , class ALLOCATOR > std::size_t bsl::hash< basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > >::operator() (const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR > & str) const [inline, inherited]
< Return a hash value computed using the specified str value.
References bsl::hashBasicString().
template<class CHAR_TYPE , class CHAR_TRAITS > bool bsl::bslstl_string_fill (std::basic_ostream< CHAR_TYPE, CHAR_TRAITS > & os, std::basic_streambuf< CHAR_TYPE, CHAR_TRAITS > * buf, size_t n)
Parameters:
n Do not use, for internal use by operator<< only.
References BSLS_ASSERT_SAFE.
Referenced by bsl::operator<<().
Variable Documentation
template<typename CHAR_TYPE, typename SIZE_TYPE> CHAR_TYPE* bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::d_start_p [inherited]
pointer to the data on heap
Referenced by bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::dataPtr(), bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::resetFields(), and bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::swap().
CHAR_TYPE* { ... } ::d_start_p [inherited]
pointer to the data on heap
union { ... } [inherited]
This is the union of the string storage options: it can either be stored inside the short string buffer, d_short, or in the externally allocated memory, pointed to by d_start_p.
BloombergLP::bsls::AlignedBuffer< { ... } ::d_short [inherited]
short string buffer
template<typename CHAR_TYPE, typename SIZE_TYPE> SIZE_TYPE bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::d_length [inherited]
length of the string
Referenced by bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::resetFields(), and bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::swap().
template<typename CHAR_TYPE, typename SIZE_TYPE> SIZE_TYPE bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::d_capacity [inherited]
capacity to which the string can grow
Referenced by bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::isShortString(), bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::resetFields(), and bsl::String_Imp< CHAR_TYPE, SIZE_TYPE >::swap().
template<typename CHAR_TYPE, typename CHAR_TRAITS = char_traits<CHAR_TYPE>, typename ALLOCATOR = allocator<CHAR_TYPE>> const basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::size_type bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::npos = ~size_type(0) [static, inherited]
Value used to denote "not-a-position", guaranteed to be outside the range [ 0, max_size() ].
Referenced by bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::append(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::assign(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_first_not_of(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_first_of(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_last_not_of(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::find_last_of(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::insert(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::operator=(), bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::rfind(), and bsl::basic_string< CHAR_TYPE, CHAR_TRAITS, ALLOCATOR >::~basic_string().