BDE 2.16 BETA: Struct bslalg::ScalarPrimitives
Quick Links:
bsl+bslhdrs | bsl+stdhdrs | bslalg | bsldoc | bslim | bslma | bslmf | bsls | bslscm | bslstl | bsltf
bslalg::ScalarPrimitives Struct Reference
#include <bslalg_scalarprimitives.h>
Static Public Member Functions
template<typename TARGET_TYPE >
static void defaultConstruct (TARGET_TYPE *address, bslma::Allocator *allocator)
template<typename TARGET_TYPE >
static void defaultConstruct (TARGET_TYPE *address, void *allocator)
template<typename TARGET_TYPE >
static void copyConstruct (TARGET_TYPE *address, const TARGET_TYPE &original, bslma::Allocator *allocator)
template<typename TARGET_TYPE >
static void copyConstruct (TARGET_TYPE *address, const TARGET_TYPE &original, void *allocator)
template<typename TARGET_TYPE , typename ALLOCATOR >
static void destructiveMove (TARGET_TYPE *address, TARGET_TYPE *original, ALLOCATOR *allocator)
template<typename TARGET_TYPE , typename ARG1 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, bslma::Allocator *allocator)
template<typename TARGET_TYPE , typename ARG1 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, void *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, bslma::Allocator *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, void *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, bslma::Allocator *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, void *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, bslma::Allocator *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, void *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, bslma::Allocator *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, void *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, bslma::Allocator *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, void *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, bslma::Allocator *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, void *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, bslma::Allocator *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, void *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, bslma::Allocator *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, void *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, const ARG10 &a10, bslma::Allocator *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, const ARG10 &a10, void *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, const ARG10 &a10, const ARG11 &a11, bslma::Allocator *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, const ARG10 &a10, const ARG11 &a11, void *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, const ARG10 &a10, const ARG11 &a11, const ARG12 &a12, bslma::Allocator *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, const ARG10 &a10, const ARG11 &a11, const ARG12 &a12, void *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 , typename ARG13 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, const ARG10 &a10, const ARG11 &a11, const ARG12 &a12, const ARG13 &a13, bslma::Allocator *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 , typename ARG13 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, const ARG10 &a10, const ARG11 &a11, const ARG12 &a12, const ARG13 &a13, void *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 , typename ARG13 , typename ARG14 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, const ARG10 &a10, const ARG11 &a11, const ARG12 &a12, const ARG13 &a13, const ARG14 &a14, bslma::Allocator *allocator)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 , typename ARG13 , typename ARG14 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, const ARG10 &a10, const ARG11 &a11, const ARG12 &a12, const ARG13 &a13, const ARG14 &a14, void *allocator)
template<typename LHS_TYPE , typename RHS_TYPE >
static void swap (LHS_TYPE &lhs, RHS_TYPE &rhs)
Detailed Description
This struct provides a namespace for a suite of utility functions that operate on elements of a parameterized type TARGET_TYPE. If any of the ...Construct methods throws, then its target address is left uninitialized and there are no effects, unless otherwise mentioned in the documentation.
Member Function Documentation
template<typename TARGET_TYPE > void bslalg::ScalarPrimitives::defaultConstruct (TARGET_TYPE * address, bslma::Allocator * allocator) [inline, static]
References BSLS_ASSERT_SAFE, bslalg::ScalarPrimitives_Imp::defaultConstruct(), bslalg::ScalarPrimitives_Imp::HAS_TRIVIAL_DEFAULT_CTOR_TRAITS, bslalg::ScalarPrimitives_Imp::NIL_TRAITS, bslalg::ScalarPrimitives_Imp::PAIR_TRAITS, and bslalg::ScalarPrimitives_Imp::USES_BSLMA_ALLOCATOR_TRAITS.
template<typename TARGET_TYPE > void bslalg::ScalarPrimitives::defaultConstruct (TARGET_TYPE * address, void * allocator) [inline, static]
Build a default-initialized object of the parameterized TARGET_TYPE in the uninitialized memory at the specified address, as if by using the TARGET_TYPE default constructor. If the specified allocator is based on bslma::Allocator and TARGET_TYPE takes an allocator constructor argument, then allocator is passed to the default constructor. If the constructor throws, the address is left in an uninitialized state. Note that this operation may bypass the constructor and simply fill memory with 0 if TARGET_TYPE has the trivial default constructor trait and does not use bslma::Allocator.
References BSLS_ASSERT_SAFE, bslalg::ScalarPrimitives_Imp::defaultConstruct(), bslalg::ScalarPrimitives_Imp::HAS_TRIVIAL_DEFAULT_CTOR_TRAITS, and bslalg::ScalarPrimitives_Imp::NIL_TRAITS.
template<typename TARGET_TYPE > void bslalg::ScalarPrimitives::copyConstruct (TARGET_TYPE * address, const TARGET_TYPE & original, bslma::Allocator * allocator) [inline, static]
References bslalg::ScalarPrimitives_Imp::BITWISE_COPYABLE_TRAITS, BSLS_ASSERT_SAFE, bslalg::ScalarPrimitives_Imp::copyConstruct(), bslalg::ScalarPrimitives_Imp::NIL_TRAITS, bslalg::ScalarPrimitives_Imp::PAIR_TRAITS, and bslalg::ScalarPrimitives_Imp::USES_BSLMA_ALLOCATOR_TRAITS.
template<typename TARGET_TYPE > void bslalg::ScalarPrimitives::copyConstruct (TARGET_TYPE * address, const TARGET_TYPE & original, void * allocator) [inline, static]
Build an object of the parameterized TARGET_TYPE from the specified original object of the same TARGET_TYPE in the uninitialized memory at the specified address, as if by using the copy constructor of TARGET_TYPE. If the specified allocator is based on bslma::Allocator and TARGET_TYPE takes an allocator constructor argument, then allocator is passed to the copy constructor. If the constructor throws, the address is left in an uninitialized state. Note that bit-wise copy will be used if TARGET_TYPE has the bit-wise copyable trait.
References bslalg::ScalarPrimitives_Imp::BITWISE_COPYABLE_TRAITS, BSLS_ASSERT_SAFE, bslalg::ScalarPrimitives_Imp::copyConstruct(), and bslalg::ScalarPrimitives_Imp::NIL_TRAITS.
template<typename TARGET_TYPE , typename ALLOCATOR > void bslalg::ScalarPrimitives::destructiveMove (TARGET_TYPE * address, TARGET_TYPE * original, ALLOCATOR * allocator) [inline, static]
Move the state of the object of the parameterized TARGET_TYPE from the object at the specified original address to the uninitialized memory at the specified address, as if by constructing a copy and then destroying the original. If the parameterized ALLOCATOR is based on bslma::Allocator and TARGET_TYPE takes an allocator constructor argument, then the moved object uses the specified allocator to supply memory. If the move constructor throws, the address is left in an uninitialized state. The behavior is undefined unless the original object also uses the allocator. Note that bit-wise copy will be used if TARGET_TYPE' has the bit-wise moveable trait.
References bslalg::ScalarPrimitives_Imp::BITWISE_MOVEABLE_TRAITS, BSLS_ASSERT_SAFE, bslalg::ScalarPrimitives_Imp::destructiveMove(), and bslalg::ScalarPrimitives_Imp::NIL_TRAITS.
template<typename TARGET_TYPE , typename ARG1 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, bslma::Allocator * allocator) [inline, static]
References bslalg::ScalarPrimitives_Imp::BITWISE_COPYABLE_TRAITS, BSLS_ASSERT_SAFE, bslalg::ScalarPrimitives_Imp::construct(), bslalg::ScalarPrimitives_Imp::NIL_TRAITS, bslalg::ScalarPrimitives_Imp::PAIR_TRAITS, and bslalg::ScalarPrimitives_Imp::USES_BSLMA_ALLOCATOR_TRAITS.
template<typename TARGET_TYPE , typename ARG1 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, void * allocator) [inline, static]
References BSLS_ASSERT_SAFE.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, bslma::Allocator * allocator) [inline, static]
References BSLS_ASSERT_SAFE, bslalg::ScalarPrimitives_Imp::construct(), bslalg::ScalarPrimitives_Imp::NIL_TRAITS, bslalg::ScalarPrimitives_Imp::PAIR_TRAITS, and bslalg::ScalarPrimitives_Imp::USES_BSLMA_ALLOCATOR_TRAITS.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, void * allocator) [inline, static]
References BSLS_ASSERT_SAFE.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, bslma::Allocator * allocator) [inline, static]
References BSLS_ASSERT_SAFE, bslalg::ScalarPrimitives_Imp::construct(), bslalg::ScalarPrimitives_Imp::NIL_TRAITS, and bslalg::ScalarPrimitives_Imp::USES_BSLMA_ALLOCATOR_TRAITS.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, void * allocator) [inline, static]
References BSLS_ASSERT_SAFE.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, bslma::Allocator * allocator) [inline, static]
References BSLS_ASSERT_SAFE, bslalg::ScalarPrimitives_Imp::construct(), bslalg::ScalarPrimitives_Imp::NIL_TRAITS, and bslalg::ScalarPrimitives_Imp::USES_BSLMA_ALLOCATOR_TRAITS.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, void * allocator) [inline, static]
References BSLS_ASSERT_SAFE.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, bslma::Allocator * allocator) [inline, static]
References BSLS_ASSERT_SAFE, bslalg::ScalarPrimitives_Imp::construct(), bslalg::ScalarPrimitives_Imp::NIL_TRAITS, and bslalg::ScalarPrimitives_Imp::USES_BSLMA_ALLOCATOR_TRAITS.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, void * allocator) [inline, static]
References BSLS_ASSERT_SAFE.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, bslma::Allocator * allocator) [inline, static]
References BSLS_ASSERT_SAFE, bslalg::ScalarPrimitives_Imp::construct(), bslalg::ScalarPrimitives_Imp::NIL_TRAITS, and bslalg::ScalarPrimitives_Imp::USES_BSLMA_ALLOCATOR_TRAITS.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, void * allocator) [inline, static]
References BSLS_ASSERT_SAFE.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, bslma::Allocator * allocator) [inline, static]
References BSLS_ASSERT_SAFE, bslalg::ScalarPrimitives_Imp::construct(), bslalg::ScalarPrimitives_Imp::NIL_TRAITS, and bslalg::ScalarPrimitives_Imp::USES_BSLMA_ALLOCATOR_TRAITS.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, void * allocator) [inline, static]
References BSLS_ASSERT_SAFE.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, bslma::Allocator * allocator) [inline, static]
References BSLS_ASSERT_SAFE, bslalg::ScalarPrimitives_Imp::construct(), bslalg::ScalarPrimitives_Imp::NIL_TRAITS, and bslalg::ScalarPrimitives_Imp::USES_BSLMA_ALLOCATOR_TRAITS.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, void * allocator) [inline, static]
References BSLS_ASSERT_SAFE.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, bslma::Allocator * allocator) [inline, static]
References BSLS_ASSERT_SAFE, bslalg::ScalarPrimitives_Imp::construct(), bslalg::ScalarPrimitives_Imp::NIL_TRAITS, and bslalg::ScalarPrimitives_Imp::USES_BSLMA_ALLOCATOR_TRAITS.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, void * allocator) [inline, static]
References BSLS_ASSERT_SAFE.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, const ARG10 & a10, bslma::Allocator * allocator) [inline, static]
References BSLS_ASSERT_SAFE, bslalg::ScalarPrimitives_Imp::construct(), bslalg::ScalarPrimitives_Imp::NIL_TRAITS, and bslalg::ScalarPrimitives_Imp::USES_BSLMA_ALLOCATOR_TRAITS.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, const ARG10 & a10, void * allocator) [inline, static]
References BSLS_ASSERT_SAFE.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, const ARG10 & a10, const ARG11 & a11, bslma::Allocator * allocator) [inline, static]
References BSLS_ASSERT_SAFE, bslalg::ScalarPrimitives_Imp::construct(), bslalg::ScalarPrimitives_Imp::NIL_TRAITS, and bslalg::ScalarPrimitives_Imp::USES_BSLMA_ALLOCATOR_TRAITS.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, const ARG10 & a10, const ARG11 & a11, void * allocator) [inline, static]
References BSLS_ASSERT_SAFE.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, const ARG10 & a10, const ARG11 & a11, const ARG12 & a12, bslma::Allocator * allocator) [inline, static]
References BSLS_ASSERT_SAFE, bslalg::ScalarPrimitives_Imp::construct(), bslalg::ScalarPrimitives_Imp::NIL_TRAITS, and bslalg::ScalarPrimitives_Imp::USES_BSLMA_ALLOCATOR_TRAITS.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, const ARG10 & a10, const ARG11 & a11, const ARG12 & a12, void * allocator) [inline, static]
References BSLS_ASSERT_SAFE.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 , typename ARG13 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, const ARG10 & a10, const ARG11 & a11, const ARG12 & a12, const ARG13 & a13, bslma::Allocator * allocator) [inline, static]
References BSLS_ASSERT_SAFE, bslalg::ScalarPrimitives_Imp::construct(), bslalg::ScalarPrimitives_Imp::NIL_TRAITS, and bslalg::ScalarPrimitives_Imp::USES_BSLMA_ALLOCATOR_TRAITS.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 , typename ARG13 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, const ARG10 & a10, const ARG11 & a11, const ARG12 & a12, const ARG13 & a13, void * allocator) [inline, static]
References BSLS_ASSERT_SAFE.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 , typename ARG13 , typename ARG14 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, const ARG10 & a10, const ARG11 & a11, const ARG12 & a12, const ARG13 & a13, const ARG14 & a14, bslma::Allocator * allocator) [inline, static]
References BSLS_ASSERT_SAFE, bslalg::ScalarPrimitives_Imp::construct(), bslalg::ScalarPrimitives_Imp::NIL_TRAITS, and bslalg::ScalarPrimitives_Imp::USES_BSLMA_ALLOCATOR_TRAITS.
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 , typename ARG13 , typename ARG14 > void bslalg::ScalarPrimitives::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, const ARG10 & a10, const ARG11 & a11, const ARG12 & a12, const ARG13 & a13, const ARG14 & a14, void * allocator) [inline, static]
Build an object of the parameterized TARGET_TYPE in the uninitialized memory at the specified address. Use the TARGET_TYPE constructor TARGET_TYPE(ARG1 const&, ...) taking the specified a1 up to a14 arguments of the respective parameterized ARG1 up to ARG14 types. If allocator is based on bslma::Allocator and TARGET_TYPE takes an allocator constructor argument, then allocator is passed to the TARGET_TYPE constructor in the last position.
References BSLS_ASSERT_SAFE.
template<typename LHS_TYPE , typename RHS_TYPE > void bslalg::ScalarPrimitives::swap (LHS_TYPE & lhs, RHS_TYPE & rhs) [static]
Swap the contents of the specified lhs modifiable reference of the parameterized LHS_TYPE with those of the specified rhs modifiable reference of the parameterized RHS_TYPE. Note that, if LHS_TYPE and RHS_TYPE are the same type and that type has the bit-wise moveable trait but does not use bslma allocators, the swap can be performed using a three-way bit-wise move.
References bslalg::ScalarPrimitives_Imp::BITWISE_MOVEABLE_TRAITS, bslalg::ScalarPrimitives_Imp::NIL_TRAITS, and bslalg::ScalarPrimitives_Imp::swap().
The documentation for this struct was generated from the following file:
bslalg_scalarprimitives.h