BDE 3.0: Struct btlso::SocketImpUtil_Address_3_01class_01IPv4Address_01_4
Quick Links:
bal | bbl | bdl | bsl | btl
btlso::SocketImpUtil_Address< class IPv4Address > Struct Template Reference
#include <btlso_socketimputil.h>
Public Types
enum { SocketDomain = AF_INET }
Public Member Functions
SocketImpUtil_Address ()
SocketImpUtil_Address (const IPv4Address &addr)
void fromSocketAddress (IPv4Address *addr) const
Public Attributes
sockaddr_in d_address
Detailed Description
template<>
struct btlso::SocketImpUtil_Address< class IPv4Address >
Encapsulate the sockaddr_in structure and provide a mapping to the equivalent IPv4Address.
Member Enumeration Documentation
anonymous enum
Enumerator:
SocketDomain
Constructor & Destructor Documentation
btlso::SocketImpUtil_Address< class IPv4Address >::SocketImpUtil_Address () [inline]
btlso::SocketImpUtil_Address< class IPv4Address >::SocketImpUtil_Address (const IPv4Address & addr) [inline]
References BSLMF_ASSERT(), btlso::IPv4Address::ipAddress(), btlso::IPv4Address::k_ANY_ADDRESS, and btlso::IPv4Address::portNumber().
Member Function Documentation
void btlso::SocketImpUtil_Address< class IPv4Address >::fromSocketAddress (IPv4Address * addr) const [inline]
References btlso::IPv4Address::k_ANY_ADDRESS, btlso::IPv4Address::setIpAddress(), and btlso::IPv4Address::setPortNumber().
Member Data Documentation
sockaddr_in btlso::SocketImpUtil_Address< class IPv4Address >::d_address
The documentation for this struct was generated from the following file:
btlso_socketimputil.h