BDE 3.0: Struct bdlf::MemFn_Dereference
Quick Links:
bal | bbl | bdl | bsl | btl
bdlf::MemFn_Dereference< OBJTYPE > Struct Template Reference
#include <bdlf_memfn.h>
Static Public Member Functions
static OBJTYPE & derefImp (OBJTYPE &obj, bslmf::MetaInt< 0 > *)
template<class TYPE >
static OBJTYPE & derefImp (TYPE &obj, bslmf::MetaInt< 1 > *)
template<class TYPE >
static OBJTYPE & derefImp (const TYPE &obj, bslmf::MetaInt< 1 > *)
template<class TYPE >
static OBJTYPE & deref (TYPE &obj)
template<class TYPE >
static OBJTYPE & deref (const TYPE &obj)
Detailed Description
template<class OBJTYPE>
struct bdlf::MemFn_Dereference< OBJTYPE >
This utility is used to convert user supplied values to references to OBJTYPE for object references that are directly convertible to OBJTYPE, the reference is returned directly. For pointers and objects that are not directly convertible (e.g., "smart pointers to <code>OBJTYPE</code>"), the result of *OBJECT is returned, where OBJECT is the pointer or object reference.
Member Function Documentation
template<class OBJTYPE > static OBJTYPE& bdlf::MemFn_Dereference< OBJTYPE >::derefImp (OBJTYPE & obj, bslmf::MetaInt< 0 > *) [inline, static]
Referenced by bdlf::MemFn_Dereference< OBJTYPE >::deref().
template<class OBJTYPE > template<class TYPE > static OBJTYPE& bdlf::MemFn_Dereference< OBJTYPE >::derefImp (TYPE & obj, bslmf::MetaInt< 1 > *) [inline, static]
template<class OBJTYPE > template<class TYPE > static OBJTYPE& bdlf::MemFn_Dereference< OBJTYPE >::derefImp (const TYPE & obj, bslmf::MetaInt< 1 > *) [inline, static]
template<class OBJTYPE > template<class TYPE > static OBJTYPE& bdlf::MemFn_Dereference< OBJTYPE >::deref (TYPE & obj) [inline, static]
References bdlf::MemFn_Dereference< OBJTYPE >::derefImp().
Referenced by bdlf::MemFn< PROTOTYPE >::operator()().
template<class OBJTYPE > template<class TYPE > static OBJTYPE& bdlf::MemFn_Dereference< OBJTYPE >::deref (const TYPE & obj) [inline, static]
References bdlf::MemFn_Dereference< OBJTYPE >::derefImp().
The documentation for this struct was generated from the following file:
bdlf_memfn.h