BDE 3.0: Struct balxml::TypesPrintUtil_Imp
Quick Links:
bal | bbl | bdl | bsl | btl
balxml::TypesPrintUtil_Imp Struct Reference
#include <balxml_typesprintutil.h>
Static Public Member Functions
template<class TYPE >
static bsl::ostream & printBase64 (bsl::ostream &stream, const TYPE &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::DynamicType)
template<class TYPE , class ANY_CATEGORY >
static bsl::ostream & printBase64 (bsl::ostream &stream, const TYPE &object, const EncoderOptions *encoderOptions, ANY_CATEGORY)
static bsl::ostream & printBase64 (bsl::ostream &stream, const bsl::string &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printBase64 (bsl::ostream &stream, const bslstl::StringRef &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printBase64 (bsl::ostream &stream, const bsl::vector< char > &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Array)
template<class TYPE >
static bsl::ostream & printDecimal (bsl::ostream &stream, const TYPE &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Enumeration)
template<class TYPE >
static bsl::ostream & printDecimal (bsl::ostream &stream, const TYPE &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::CustomizedType)
template<class TYPE >
static bsl::ostream & printDecimal (bsl::ostream &stream, const TYPE &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::DynamicType)
template<class TYPE , class ANY_CATEGORY >
static bsl::ostream & printDecimal (bsl::ostream &stream, const TYPE &object, const EncoderOptions *encoderOptions, ANY_CATEGORY)
static bsl::ostream & printDecimal (bsl::ostream &stream, const bool &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDecimal (bsl::ostream &stream, const char &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDecimal (bsl::ostream &stream, const short &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDecimal (bsl::ostream &stream, const int &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDecimal (bsl::ostream &stream, const long &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDecimal (bsl::ostream &stream, const bsls::Types::Int64 &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDecimal (bsl::ostream &stream, const unsigned char &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDecimal (bsl::ostream &stream, const unsigned short &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDecimal (bsl::ostream &stream, const unsigned int &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDecimal (bsl::ostream &stream, const unsigned long &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDecimal (bsl::ostream &stream, const bsls::Types::Uint64 &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDecimal (bsl::ostream &stream, const float &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDecimal (bsl::ostream &stream, const double &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
template<class TYPE >
static bsl::ostream & printDefault (bsl::ostream &stream, const TYPE &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Enumeration)
template<class TYPE >
static bsl::ostream & printDefault (bsl::ostream &stream, const TYPE &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::CustomizedType)
template<class TYPE >
static bsl::ostream & printDefault (bsl::ostream &stream, const TYPE &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::DynamicType)
template<class TYPE , class ANY_CATEGORY >
static bsl::ostream & printDefault (bsl::ostream &stream, const TYPE &object, const EncoderOptions *encoderOptions, ANY_CATEGORY)
static bsl::ostream & printDefault (bsl::ostream &stream, const bool &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const char &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const short &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const int &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const long &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const bsls::Types::Int64 &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const unsigned char &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const unsigned short &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const unsigned int &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const unsigned long &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const bsls::Types::Uint64 &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const float &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const double &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const char *object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const bsl::string &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const bslstl::StringRef &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const bdlt::Date &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const bdlt::DateTz &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const bdlt::Datetime &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const bdlt::DatetimeTz &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const bdlt::Time &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const bdlt::TimeTz &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printDefault (bsl::ostream &stream, const bsl::vector< char > &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Array)
template<class TYPE >
static bsl::ostream & printHex (bsl::ostream &stream, const TYPE &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::DynamicType)
template<class TYPE , class ANY_CATEGORY >
static bsl::ostream & printHex (bsl::ostream &stream, const TYPE &object, const EncoderOptions *encoderOptions, ANY_CATEGORY)
static bsl::ostream & printHex (bsl::ostream &stream, const bsl::string &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printHex (bsl::ostream &stream, const bslstl::StringRef &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printHex (bsl::ostream &stream, const bsl::vector< char > &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Array)
template<class TYPE >
static bsl::ostream & printList (bsl::ostream &stream, const TYPE &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Array)
template<class TYPE >
static bsl::ostream & printList (bsl::ostream &stream, const TYPE &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::DynamicType)
template<class TYPE , class ANY_CATEGORY >
static bsl::ostream & printList (bsl::ostream &stream, const TYPE &object, const EncoderOptions *encoderOptions, ANY_CATEGORY)
template<class TYPE >
static bsl::ostream & printText (bsl::ostream &stream, const TYPE &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Enumeration)
template<class TYPE >
static bsl::ostream & printText (bsl::ostream &stream, const TYPE &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::CustomizedType)
template<class TYPE >
static bsl::ostream & printText (bsl::ostream &stream, const TYPE &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::DynamicType)
template<class TYPE , class ANY_CATEGORY >
static bsl::ostream & printText (bsl::ostream &stream, const TYPE &object, const EncoderOptions *encoderOptions, ANY_CATEGORY)
static bsl::ostream & printText (bsl::ostream &stream, const bool &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printText (bsl::ostream &stream, const char &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printText (bsl::ostream &stream, const char *object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printText (bsl::ostream &stream, const bsl::string &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printText (bsl::ostream &stream, const bslstl::StringRef &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Simple)
static bsl::ostream & printText (bsl::ostream &stream, const bsl::vector< char > &object, const EncoderOptions *encoderOptions, bdlat_TypeCategory::Array)
Detailed Description
This struct contains functions that are used in the implementation of this component.
Member Function Documentation
template<class TYPE > static bsl::ostream& balxml::TypesPrintUtil_Imp::printBase64 (bsl::ostream & stream, const TYPE & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::DynamicType) [static]
Referenced by balxml::TypesPrintUtil_Imp_printBase64Proxy::operator()().
template<class TYPE , class ANY_CATEGORY > static bsl::ostream& balxml::TypesPrintUtil_Imp::printBase64 (bsl::ostream & stream, const TYPE & object, const EncoderOptions * encoderOptions, ANY_CATEGORY) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printBase64 (bsl::ostream & stream, const bsl::string & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printBase64 (bsl::ostream & stream, const bslstl::StringRef & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printBase64 (bsl::ostream & stream, const bsl::vector< char > & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Array) [static]
template<class TYPE > static bsl::ostream& balxml::TypesPrintUtil_Imp::printDecimal (bsl::ostream & stream, const TYPE & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Enumeration) [static]
Referenced by balxml::TypesPrintUtil_Imp_printDecimalProxy::operator()().
template<class TYPE > static bsl::ostream& balxml::TypesPrintUtil_Imp::printDecimal (bsl::ostream & stream, const TYPE & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::CustomizedType) [static]
template<class TYPE > static bsl::ostream& balxml::TypesPrintUtil_Imp::printDecimal (bsl::ostream & stream, const TYPE & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::DynamicType) [static]
template<class TYPE , class ANY_CATEGORY > static bsl::ostream& balxml::TypesPrintUtil_Imp::printDecimal (bsl::ostream & stream, const TYPE & object, const EncoderOptions * encoderOptions, ANY_CATEGORY) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDecimal (bsl::ostream & stream, const bool & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDecimal (bsl::ostream & stream, const char & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDecimal (bsl::ostream & stream, const short & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDecimal (bsl::ostream & stream, const int & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDecimal (bsl::ostream & stream, const long & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDecimal (bsl::ostream & stream, const bsls::Types::Int64 & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDecimal (bsl::ostream & stream, const unsigned char & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDecimal (bsl::ostream & stream, const unsigned short & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDecimal (bsl::ostream & stream, const unsigned int & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDecimal (bsl::ostream & stream, const unsigned long & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDecimal (bsl::ostream & stream, const bsls::Types::Uint64 & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDecimal (bsl::ostream & stream, const float & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDecimal (bsl::ostream & stream, const double & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
template<class TYPE > static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const TYPE & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Enumeration) [static]
Referenced by balxml::TypesPrintUtil_Imp_printDefaultProxy::operator()().
template<class TYPE > static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const TYPE & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::CustomizedType) [static]
template<class TYPE > static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const TYPE & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::DynamicType) [static]
template<class TYPE , class ANY_CATEGORY > static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const TYPE & object, const EncoderOptions * encoderOptions, ANY_CATEGORY) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const bool & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const char & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const short & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const int & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const long & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const bsls::Types::Int64 & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const unsigned char & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const unsigned short & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const unsigned int & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const unsigned long & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const bsls::Types::Uint64 & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const float & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const double & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const char * object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const bsl::string & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const bslstl::StringRef & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const bdlt::Date & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const bdlt::DateTz & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const bdlt::Datetime & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const bdlt::DatetimeTz & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const bdlt::Time & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const bdlt::TimeTz & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printDefault (bsl::ostream & stream, const bsl::vector< char > & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Array) [static]
template<class TYPE > static bsl::ostream& balxml::TypesPrintUtil_Imp::printHex (bsl::ostream & stream, const TYPE & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::DynamicType) [static]
Referenced by balxml::TypesPrintUtil_Imp_printHexProxy::operator()().
template<class TYPE , class ANY_CATEGORY > static bsl::ostream& balxml::TypesPrintUtil_Imp::printHex (bsl::ostream & stream, const TYPE & object, const EncoderOptions * encoderOptions, ANY_CATEGORY) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printHex (bsl::ostream & stream, const bsl::string & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printHex (bsl::ostream & stream, const bslstl::StringRef & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printHex (bsl::ostream & stream, const bsl::vector< char > & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Array) [static]
template<class TYPE > static bsl::ostream& balxml::TypesPrintUtil_Imp::printList (bsl::ostream & stream, const TYPE & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Array) [static]
Referenced by balxml::TypesPrintUtil_Imp_printListProxy::operator()().
template<class TYPE > static bsl::ostream& balxml::TypesPrintUtil_Imp::printList (bsl::ostream & stream, const TYPE & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::DynamicType) [static]
template<class TYPE , class ANY_CATEGORY > static bsl::ostream& balxml::TypesPrintUtil_Imp::printList (bsl::ostream & stream, const TYPE & object, const EncoderOptions * encoderOptions, ANY_CATEGORY) [static]
template<class TYPE > static bsl::ostream& balxml::TypesPrintUtil_Imp::printText (bsl::ostream & stream, const TYPE & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Enumeration) [static]
Referenced by balxml::TypesPrintUtil_Imp_printTextProxy::operator()().
template<class TYPE > static bsl::ostream& balxml::TypesPrintUtil_Imp::printText (bsl::ostream & stream, const TYPE & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::CustomizedType) [static]
template<class TYPE > static bsl::ostream& balxml::TypesPrintUtil_Imp::printText (bsl::ostream & stream, const TYPE & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::DynamicType) [static]
template<class TYPE , class ANY_CATEGORY > static bsl::ostream& balxml::TypesPrintUtil_Imp::printText (bsl::ostream & stream, const TYPE & object, const EncoderOptions * encoderOptions, ANY_CATEGORY) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printText (bsl::ostream & stream, const bool & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printText (bsl::ostream & stream, const char & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printText (bsl::ostream & stream, const char * object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printText (bsl::ostream & stream, const bsl::string & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printText (bsl::ostream & stream, const bslstl::StringRef & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Simple) [static]
static bsl::ostream& balxml::TypesPrintUtil_Imp::printText (bsl::ostream & stream, const bsl::vector< char > & object, const EncoderOptions * encoderOptions, bdlat_TypeCategory::Array) [static]
The documentation for this struct was generated from the following file:
balxml_typesprintutil.h