BDE 3.0: Struct balxml::TypesParserUtil_Imp
Quick Links:
bal | bbl | bdl | bsl | btl
balxml::TypesParserUtil_Imp Struct Reference
#include <balxml_typesparserutil.h>
Static Public Member Functions
template<class TYPE >
static int parseBase64 (TYPE *result, const char *input, int inputLength, bdlat_TypeCategory::DynamicType)
template<class TYPE , class ANY_CATEGORY >
static int parseBase64 (TYPE *result, const char *input, int inputLength, ANY_CATEGORY)
static int parseBase64 (bsl::string *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseBase64 (bsl::vector< char > *result, const char *input, int inputLength, bdlat_TypeCategory::Array)
template<class TYPE >
static int parseDecimal (TYPE *result, const char *input, int inputLength, bdlat_TypeCategory::Enumeration)
template<class TYPE >
static int parseDecimal (TYPE *result, const char *input, int inputLength, bdlat_TypeCategory::CustomizedType)
template<class TYPE >
static int parseDecimal (TYPE *result, const char *input, int inputLength, bdlat_TypeCategory::DynamicType)
template<class TYPE , class ANY_CATEGORY >
static int parseDecimal (TYPE *result, const char *input, int inputLength, ANY_CATEGORY)
static int parseDecimal (bool *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDecimal (char *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDecimal (short *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDecimal (int *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDecimal (bsls::Types::Int64 *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDecimal (unsigned char *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDecimal (unsigned short *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDecimal (unsigned int *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDecimal (bsls::Types::Uint64 *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDecimal (float *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDecimal (double *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDefault (bdldfp::Decimal64 *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
template<class TYPE >
static int parseDefault (TYPE *result, const char *input, int inputLength, bdlat_TypeCategory::Enumeration)
template<class TYPE >
static int parseDefault (TYPE *result, const char *input, int inputLength, bdlat_TypeCategory::CustomizedType)
template<class TYPE >
static int parseDefault (TYPE *result, const char *input, int inputLength, bdlat_TypeCategory::DynamicType)
template<class TYPE , class ANY_CATEGORY >
static int parseDefault (TYPE *result, const char *input, int inputLength, ANY_CATEGORY)
static int parseDefault (bool *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDefault (char *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDefault (short *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDefault (int *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDefault (bsls::Types::Int64 *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDefault (unsigned char *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDefault (unsigned short *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDefault (unsigned int *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDefault (bsls::Types::Uint64 *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDefault (float *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDefault (double *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDefault (bsl::string *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDefault (bdlt::Date *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDefault (bdlt::DateTz *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDefault (bdlt::Datetime *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDefault (bdlt::DatetimeTz *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDefault (bdlt::Time *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDefault (bdlt::TimeTz *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseDefault (bsl::vector< char > *result, const char *input, int inputLength, bdlat_TypeCategory::Array)
template<class TYPE >
static int parseHex (TYPE *result, const char *input, int inputLength, bdlat_TypeCategory::DynamicType)
template<class TYPE , class ANY_CATEGORY >
static int parseHex (TYPE *result, const char *input, int inputLength, ANY_CATEGORY)
static int parseHex (bsl::string *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseHex (bsl::vector< char > *result, const char *input, int inputLength, bdlat_TypeCategory::Array)
template<class TYPE >
static int parseList (TYPE *result, const char *input, int inputLength, bdlat_TypeCategory::Array)
template<class TYPE >
static int parseList (TYPE *result, const char *input, int inputLength, bdlat_TypeCategory::DynamicType)
template<class TYPE , class ANY_CATEGORY >
static int parseList (TYPE *result, const char *input, int inputLength, ANY_CATEGORY)
template<class TYPE >
static int parseText (TYPE *result, const char *input, int inputLength, bdlat_TypeCategory::Enumeration)
template<class TYPE >
static int parseText (TYPE *result, const char *input, int inputLength, bdlat_TypeCategory::CustomizedType)
template<class TYPE >
static int parseText (TYPE *result, const char *input, int inputLength, bdlat_TypeCategory::DynamicType)
template<class TYPE , class ANY_CATEGORY >
static int parseText (TYPE *result, const char *input, int inputLength, ANY_CATEGORY)
static int parseText (bool *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseText (char *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseText (bsl::string *result, const char *input, int inputLength, bdlat_TypeCategory::Simple)
static int parseText (bsl::vector< char > *result, const char *input, int inputLength, bdlat_TypeCategory::Array)
Detailed Description
This struct contains functions that are used in the implementation of this component.
Member Function Documentation
template<class TYPE > static int balxml::TypesParserUtil_Imp::parseBase64 (TYPE * result, const char * input, int inputLength, bdlat_TypeCategory::DynamicType) [static]
Referenced by balxml::TypesParserUtil_Imp_parseBase64Proxy::operator()().
template<class TYPE , class ANY_CATEGORY > static int balxml::TypesParserUtil_Imp::parseBase64 (TYPE * result, const char * input, int inputLength, ANY_CATEGORY) [static]
static int balxml::TypesParserUtil_Imp::parseBase64 (bsl::string * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseBase64 (bsl::vector< char > * result, const char * input, int inputLength, bdlat_TypeCategory::Array) [static]
template<class TYPE > static int balxml::TypesParserUtil_Imp::parseDecimal (TYPE * result, const char * input, int inputLength, bdlat_TypeCategory::Enumeration) [static]
Referenced by balxml::TypesParserUtil_Imp_parseDecimalProxy::operator()().
template<class TYPE > static int balxml::TypesParserUtil_Imp::parseDecimal (TYPE * result, const char * input, int inputLength, bdlat_TypeCategory::CustomizedType) [static]
template<class TYPE > static int balxml::TypesParserUtil_Imp::parseDecimal (TYPE * result, const char * input, int inputLength, bdlat_TypeCategory::DynamicType) [static]
template<class TYPE , class ANY_CATEGORY > static int balxml::TypesParserUtil_Imp::parseDecimal (TYPE * result, const char * input, int inputLength, ANY_CATEGORY) [static]
static int balxml::TypesParserUtil_Imp::parseDecimal (bool * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDecimal (char * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDecimal (short * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDecimal (int * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDecimal (bsls::Types::Int64 * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDecimal (unsigned char * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDecimal (unsigned short * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDecimal (unsigned int * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDecimal (bsls::Types::Uint64 * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDecimal (float * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDecimal (double * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDefault (bdldfp::Decimal64 * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
Referenced by balxml::TypesParserUtil_Imp_parseDefaultProxy::operator()().
template<class TYPE > static int balxml::TypesParserUtil_Imp::parseDefault (TYPE * result, const char * input, int inputLength, bdlat_TypeCategory::Enumeration) [static]
template<class TYPE > static int balxml::TypesParserUtil_Imp::parseDefault (TYPE * result, const char * input, int inputLength, bdlat_TypeCategory::CustomizedType) [static]
template<class TYPE > static int balxml::TypesParserUtil_Imp::parseDefault (TYPE * result, const char * input, int inputLength, bdlat_TypeCategory::DynamicType) [static]
template<class TYPE , class ANY_CATEGORY > static int balxml::TypesParserUtil_Imp::parseDefault (TYPE * result, const char * input, int inputLength, ANY_CATEGORY) [static]
static int balxml::TypesParserUtil_Imp::parseDefault (bool * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDefault (char * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDefault (short * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDefault (int * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDefault (bsls::Types::Int64 * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDefault (unsigned char * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDefault (unsigned short * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDefault (unsigned int * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDefault (bsls::Types::Uint64 * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDefault (float * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDefault (double * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDefault (bsl::string * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDefault (bdlt::Date * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDefault (bdlt::DateTz * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDefault (bdlt::Datetime * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDefault (bdlt::DatetimeTz * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDefault (bdlt::Time * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDefault (bdlt::TimeTz * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseDefault (bsl::vector< char > * result, const char * input, int inputLength, bdlat_TypeCategory::Array) [static]
template<class TYPE > static int balxml::TypesParserUtil_Imp::parseHex (TYPE * result, const char * input, int inputLength, bdlat_TypeCategory::DynamicType) [static]
Referenced by balxml::TypesParserUtil_Imp_parseHexProxy::operator()().
template<class TYPE , class ANY_CATEGORY > static int balxml::TypesParserUtil_Imp::parseHex (TYPE * result, const char * input, int inputLength, ANY_CATEGORY) [static]
static int balxml::TypesParserUtil_Imp::parseHex (bsl::string * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseHex (bsl::vector< char > * result, const char * input, int inputLength, bdlat_TypeCategory::Array) [static]
template<class TYPE > static int balxml::TypesParserUtil_Imp::parseList (TYPE * result, const char * input, int inputLength, bdlat_TypeCategory::Array) [static]
Referenced by balxml::TypesParserUtil_Imp_parseListProxy::operator()().
template<class TYPE > static int balxml::TypesParserUtil_Imp::parseList (TYPE * result, const char * input, int inputLength, bdlat_TypeCategory::DynamicType) [static]
template<class TYPE , class ANY_CATEGORY > static int balxml::TypesParserUtil_Imp::parseList (TYPE * result, const char * input, int inputLength, ANY_CATEGORY) [static]
template<class TYPE > static int balxml::TypesParserUtil_Imp::parseText (TYPE * result, const char * input, int inputLength, bdlat_TypeCategory::Enumeration) [static]
Referenced by balxml::TypesParserUtil_Imp_parseTextProxy::operator()().
template<class TYPE > static int balxml::TypesParserUtil_Imp::parseText (TYPE * result, const char * input, int inputLength, bdlat_TypeCategory::CustomizedType) [static]
template<class TYPE > static int balxml::TypesParserUtil_Imp::parseText (TYPE * result, const char * input, int inputLength, bdlat_TypeCategory::DynamicType) [static]
template<class TYPE , class ANY_CATEGORY > static int balxml::TypesParserUtil_Imp::parseText (TYPE * result, const char * input, int inputLength, ANY_CATEGORY) [static]
static int balxml::TypesParserUtil_Imp::parseText (bool * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseText (char * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseText (bsl::string * result, const char * input, int inputLength, bdlat_TypeCategory::Simple) [static]
static int balxml::TypesParserUtil_Imp::parseText (bsl::vector< char > * result, const char * input, int inputLength, bdlat_TypeCategory::Array) [static]
The documentation for this struct was generated from the following file:
balxml_typesparserutil.h