BDE 3.0: Struct btlso::SocketImpUtil
Quick Links:
bal | bbl | bdl | bsl | btl
btlso::SocketImpUtil Struct Reference
#include <btlso_socketimputil.h>
Public Types
enum Type { k_SOCKET_STREAM = SOCK_STREAM, k_SOCKET_DATAGRAM = SOCK_DGRAM, k_SOCKET_RAW = SOCK_RAW }
enum ShutDownType { e_SHUTDOWN_RECEIVE, e_SHUTDOWN_SEND, e_SHUTDOWN_BOTH }
Indicates how to shut down the socket with shutDown operation.
Static Public Member Functions
template<class ADDRESS >
static int accept (SocketHandle::Handle *newSocket, const SocketHandle::Handle &socket)
template<class ADDRESS >
static int accept (SocketHandle::Handle *newSocket, const SocketHandle::Handle &socket, int *errorCode)
template<class ADDRESS >
static int accept (SocketHandle::Handle *newSocket, ADDRESS *peerAddress, const SocketHandle::Handle &socket)
template<class ADDRESS >
static int accept (SocketHandle::Handle *newSocket, ADDRESS *peerAddress, const SocketHandle::Handle &socket, int *errorCode)
template<class ADDRESS >
static int bind (const SocketHandle::Handle &socket, const ADDRESS &address)
template<class ADDRESS >
static int bind (const SocketHandle::Handle &socket, const ADDRESS &address, int *errorCode)
static int cleanup (int *errorCode=0)
static int close (const SocketHandle::Handle &socket, int *errorCode=0)
template<class ADDRESS >
static int connect (const SocketHandle::Handle &socket, const ADDRESS &address)
template<class ADDRESS >
static int connect (const SocketHandle::Handle &socket, const ADDRESS &address, int *errorCode)
template<class ADDRESS >
static int getLocalAddress (ADDRESS *localAddress, const SocketHandle::Handle &socket)
template<class ADDRESS >
static int getLocalAddress (ADDRESS *localAddress, const SocketHandle::Handle &socket, int *errorCode)
template<class ADDRESS >
static int getPeerAddress (ADDRESS *peerAddress, const SocketHandle::Handle &socket)
template<class ADDRESS >
static int getPeerAddress (ADDRESS *peerAddress, const SocketHandle::Handle &socket, int *errorCode)
static int listen (const SocketHandle::Handle &socket, int queueSize, int *errorCode=0)
template<class ADDRESS >
static int open (SocketHandle::Handle *newSocket, SocketImpUtil::Type type)
template<class ADDRESS >
static int open (SocketHandle::Handle *newSocket, SocketImpUtil::Type type, int *errorCode)
template<class ADDRESS >
static int open (SocketHandle::Handle *newSocket, SocketImpUtil::Type type, int protocol)
template<class ADDRESS >
static int open (SocketHandle::Handle *newSocket, SocketImpUtil::Type type, int protocol, int *errorCode)
static int read (void *buffer, const SocketHandle::Handle &socket, int numBytes, int *errorCode=0)
template<class ADDRESS >
static int readFrom (ADDRESS *fromAddress, void *buffer, const SocketHandle::Handle &socket, int numBytes)
template<class ADDRESS >
static int readFrom (ADDRESS *fromAddress, void *buffer, const SocketHandle::Handle &socket, int numBytes, int *errorCode)
static int readv (const btls::Iovec *iovec, const SocketHandle::Handle &socket, int numBuffs, int *errorCode=0)
template<class ADDRESS >
static int socketPair (SocketHandle::Handle *newSockets, SocketImpUtil::Type type)
template<class ADDRESS >
static int socketPair (SocketHandle::Handle *newSockets, SocketImpUtil::Type type, int *errorCode)
template<class ADDRESS >
static int socketPair (SocketHandle::Handle *newSockets, SocketImpUtil::Type type, int protocol)
template<class ADDRESS >
static int socketPair (SocketHandle::Handle *newSockets, SocketImpUtil::Type type, int protocol, int *errorCode)
static int write (const SocketHandle::Handle &socket, const void *buffer, int numBytes, int *errorCode=0)
template<class ADDRESS >
static int writeTo (const SocketHandle::Handle &socket, const ADDRESS &toAddress, const void *buffer, int numBytes)
template<class ADDRESS >
static int writeTo (const SocketHandle::Handle &socket, const ADDRESS &toAddress, const void *buffer, int numBytes, int *errorCode)
static int writev (const SocketHandle::Handle &socket, const btls::Ovec *ovec, int numBuffs, int *errorCode=0)
template<class ADDRESS >
static int writevTo (const SocketHandle::Handle &socket, const ADDRESS &toAddress, const btls::Ovec *ovec, int numBuffs, int *errorCode=0)
static int shutDown (const SocketHandle::Handle &socket, SocketImpUtil::ShutDownType value, int *errorCode=0)
static int startup (int *errorCode=0)
Detailed Description
This class provides a suite of platform-independent pure procedures that manipulate operating-system-level sockets. All methods take an errorCode as an optional parameter, which is loaded with platform-specific error number if an error occurs during the operation. All functions return a negative value on error. This value defined in SocketHandle classifies the error and is not platform-specific.
Member Enumeration Documentation
enum btlso::SocketImpUtil::Type
When creating a socket with the open or socketPair operations, this indicates the type of socket(s) to be created.
Enumerator:
k_SOCKET_STREAM
Provides sequenced, reliable, two-way, connection-based byte streams. An out-of-band data transmission mechanism may be supported.
k_SOCKET_DATAGRAM
Supports datagrams (connectionless, unreliable messages of a fixed maximum length).
k_SOCKET_RAW
Provides raw network protocol access.
enum btlso::SocketImpUtil::ShutDownType
Enumerator:
e_SHUTDOWN_RECEIVE
shut down the receive half of the full-duplex connection associated with the specified socket, leaving its send half unaffected.
e_SHUTDOWN_SEND
shut down the send half of the full-duplex connection associated with the specified socket, leaving its receive half unaffected.
e_SHUTDOWN_BOTH
shut down both halves of the full-duplex connection associated with the specified socket.
Member Function Documentation
template<class ADDRESS > static int btlso::SocketImpUtil::accept (SocketHandle::Handle * newSocket, const SocketHandle::Handle & socket) [static]
template<class ADDRESS > static int btlso::SocketImpUtil::accept (SocketHandle::Handle * newSocket, const SocketHandle::Handle & socket, int * errorCode) [static]
Accept a connection request on the specified listening socket. On success, load the specified newSocket with the handle for the socket created for the newly established connection. Load the optionally specified errorCode with the platform-specific error number on error. Return 0 on success and a negative value otherwise representing an error classification. Note that if socket is in non-blocking mode and there is no pending connection request available, this call returns immediately with an error status, but if socket is in blocking mode, this call blocks until either it succeeds or an error occurs. Also note that, when created, newSocket has exactly the same socket options as socket.
template<class ADDRESS > static int btlso::SocketImpUtil::accept (SocketHandle::Handle * newSocket, ADDRESS * peerAddress, const SocketHandle::Handle & socket) [static]
template<class ADDRESS > static int btlso::SocketImpUtil::accept (SocketHandle::Handle * newSocket, ADDRESS * peerAddress, const SocketHandle::Handle & socket, int * errorCode) [static]
Accept a connection request on the specified listening socket. On success, load the specified newSocket with the handle for the socket created for the newly established connection, and also load the specified peerAddress with the address of the newly connected client. Load the optionally specified errorCode with the platform-specific error number on error. Return 0 on success, and a negative value otherwise representing an error classification. Note that if socket is in non-blocking mode and there is no pending connection request available, this call returns immediately with an error status, but if socket is in blocking mode, this call blocks until either it succeeds or an error occurs. Also note that, when created, newSocket has exactly the same socket options as socket. If a connection has been closed before the accept call is made, the call may fail and SocketHandle::e_ERROR_CONNDEAD will be returned.
template<class ADDRESS > static int btlso::SocketImpUtil::bind (const SocketHandle::Handle & socket, const ADDRESS & address) [static]
template<class ADDRESS > static int btlso::SocketImpUtil::bind (const SocketHandle::Handle & socket, const ADDRESS & address, int * errorCode) [static]
Associate the specified address with the specified socket. Load the optionally specified errorCode with a platform-specific error number on error. Return 0 on success and a negative value otherwise representing an error classification. Note that (a) typically, servers call bind with a well-known port number since they are known by their port numbers, and (b) typically, stream based clients allow the kernel to choose a temporary (ephemeral) port by not invoking this operation at all. Note also that a port number 0 can be specified so that an address can be bound to a socket without binding a specific port number.
static int btlso::SocketImpUtil::cleanup (int * errorCode = 0) [static]
Clean up the environment created for sockets-based activity. All open sockets should be explicitly closed prior to this operation. No assumptions should be made about the state of any remaining open socket after this operation. Load the optionally specified errorCode with a platform-specific error number on error. Return 0 on success and a negative value otherwise representing an error classification.
Referenced by btlso::InetStreamSocketFactory< ADDRESS >::~InetStreamSocketFactory().
static int btlso::SocketImpUtil::close (const SocketHandle::Handle & socket, int * errorCode = 0) [static]
Close the specified socket and release all the resources associated with it. If this socket is the last reference to an existing connection, this connection will be terminated. Load the optionally specified errorCode with a platform-specific error number on error. Return 0 on success, and a negative value otherwise representing an error classification. Note that although call to close returns immediately, by default, the kernel tries to send all untransmitted data before actually closing the connection. This default behavior can be altered by changing the socket linger options (see btlso_socketoptutil).
Referenced by btlso::InetStreamSocketFactory< ADDRESS >::deallocate(), and btlso::InetStreamSocketCloseGuard::~InetStreamSocketCloseGuard().
template<class ADDRESS > static int btlso::SocketImpUtil::connect (const SocketHandle::Handle & socket, const ADDRESS & address) [static]
template<class ADDRESS > static int btlso::SocketImpUtil::connect (const SocketHandle::Handle & socket, const ADDRESS & address, int * errorCode) [static]
For a stream type socket, connect the specified socket with the server process listening at the specified address. Load the optionally specified errorCode with a platform-specific error number on error. Return 0 on success, and a negative value otherwise representing an error classification. If the socket is in blocking mode, the call will block until the connection is established or an error occurs. If the socket is in non-blocking mode, the call may complete immediately returning SocketHandle::e_ERROR_WOULDBLOCK indicating that the operation has been initiated but may not have completed. In this case the select function can be used to determine when the connection has completed. For a datagram socket, associate the specified address with the specified socket. If no address is specified for a send operation, the specified address is used. For receive operations, only data from the specified address is received.
template<class ADDRESS > static int btlso::SocketImpUtil::getLocalAddress (ADDRESS * localAddress, const SocketHandle::Handle & socket) [static]
template<class ADDRESS > static int btlso::SocketImpUtil::getLocalAddress (ADDRESS * localAddress, const SocketHandle::Handle & socket, int * errorCode) [static]
Load the local address and port number associated with the specified socket in the specified localAddress. The result is undefined if the socket was not initially created with the specified ADDRESS type. Load the optionally specified errorCode with a platform-specific error number on error. Return 0 on success, and a negative value otherwise representing an error classification.
template<class ADDRESS > static int btlso::SocketImpUtil::getPeerAddress (ADDRESS * peerAddress, const SocketHandle::Handle & socket) [static]
template<class ADDRESS > static int btlso::SocketImpUtil::getPeerAddress (ADDRESS * peerAddress, const SocketHandle::Handle & socket, int * errorCode) [static]
Load the specified peerAddress with the address and port number of the peer connected to the specified socket. Load the optionally specified errorCode with a platform-specific error number on error. Return 0 on success, and a negative value otherwise representing an error classification.
static int btlso::SocketImpUtil::listen (const SocketHandle::Handle & socket, int queueSize, int * errorCode = 0) [static]
Listen passively to the incoming connection requests on the specified stream socket. Also set the maximum number of pending connection requests to be queued before "accepted" to the specified queueSize. If the backlog value is (system dependent) SOMAXCONN, then the backlog will be set to the maximum "reasonable" value. There is no standard provision to find out the actual backlog value. Load the optionally specified errorCode with a platform-specific error number on error. Return 0 on success, and a negative value otherwise representing an error classification. The behavior is undefined unless 0 < queueSize.
template<class ADDRESS > static int btlso::SocketImpUtil::open (SocketHandle::Handle * newSocket, SocketImpUtil::Type type) [static]
template<class ADDRESS > static int btlso::SocketImpUtil::open (SocketHandle::Handle * newSocket, SocketImpUtil::Type type, int * errorCode) [static]
Initialize the specified newSocket with a newly created socket of the specified type. Load the optionally specified errorCode with the platform-specific error number on error. Return 0 on success, and a negative value otherwise representing an error classification.
template<class ADDRESS > static int btlso::SocketImpUtil::open (SocketHandle::Handle * newSocket, SocketImpUtil::Type type, int protocol) [static]
template<class ADDRESS > static int btlso::SocketImpUtil::open (SocketHandle::Handle * newSocket, SocketImpUtil::Type type, int protocol, int * errorCode) [static]
Initialize the specified newSocket with a newly created socket of the specified type and the specified protocol. Load the optionally specified errorCode with the platform-specific error number on error. Return 0 on success, and a negative value otherwise representing an error classification.
static int btlso::SocketImpUtil::read (void * buffer, const SocketHandle::Handle & socket, int numBytes, int * errorCode = 0) [static]
Receive up to a maximum of the specified numBytes bytes from the specified socket in the specified buffer. Load the optionally specified errorCode with the platform-specific error number on error. Return the non-negative number of bytes read on success, 0 on EOF (when 0 < numBytes), and a negative value otherwise representing an error classification. The behavior is undefined unless 0 <= numBytes and buffer refers to at least numBytes valid memory locations. Note that if socket is in blocking mode, this call blocks until (a) data is read, (b) an EOF indication occurs, or (c) an error occurs. Note that if numBytes is 0, this call returns immediately, with no effect on buffer.
template<class ADDRESS > static int btlso::SocketImpUtil::readFrom (ADDRESS * fromAddress, void * buffer, const SocketHandle::Handle & socket, int numBytes) [static]
template<class ADDRESS > static int btlso::SocketImpUtil::readFrom (ADDRESS * fromAddress, void * buffer, const SocketHandle::Handle & socket, int numBytes, int * errorCode) [static]
Receive up to a maximum of the specified numBytes bytes from the specified socket in the specified buffer and load the address and port number of the source of the data in fromAddress. Load the optionally specified errorCode with the platform-specific error number on error. Return the non-negative number of bytes read on success, 0 on EOF or when 0 == numBytes, and a negative value otherwise representing an error classification. The socket must not be connected. The fromAddress parameter will be ignored for connection-oriented sockets. For message-oriented sockets data is extracted from the first enqueued message, up to the size of buffer. If the datagram or message is larger than the buffer, it is filled with the first part of the datagram, and an error is generated. For unreliable protocols (e.g., UDP) the excess data is lost. The behavior is undefined unless 0 <= numBytes and buffer refers to at least numBytes valid memory locations. Note that if socket is in blocking mode, this call blocks until (a) data is read, (b) an EOF indication occurs, or (c) an error occurs. Note also that if numBytes is 0, this call returns immediately, with no effect on buffer.
static int btlso::SocketImpUtil::readv (const btls::Iovec * iovec, const SocketHandle::Handle & socket, int numBuffs, int * errorCode = 0) [static]
Receive from the specified socket into the buffers specified by iovec where the specified numBuffs is the number of buffers. Load the optionally specified errorCode with the platform-specific error number on error. Return the non-negative number of bytes read on success, 0 on EOF or when 0 == numBytes, and a negative value otherwise representing an error classification. The behavior is undefined unless 0 < numBuffs and iovec refers to buffers at valid memory locations. Note that if socket is in blocking mode, this call blocks until (a) data is read, (b) an EOF indication occurs, or (c) an error occurs.
template<class ADDRESS > static int btlso::SocketImpUtil::socketPair (SocketHandle::Handle * newSockets, SocketImpUtil::Type type) [static]
template<class ADDRESS > static int btlso::SocketImpUtil::socketPair (SocketHandle::Handle * newSockets, SocketImpUtil::Type type, int * errorCode) [static]
Create a pair of connected sockets of the specified type. On success, the specified newSockets will point to the handles for the new sockets. Load the optionally specified errorCode with the platform-specific error number on error. Return 0 on success, and a negative value otherwise representing an error classification.
template<class ADDRESS > static int btlso::SocketImpUtil::socketPair (SocketHandle::Handle * newSockets, SocketImpUtil::Type type, int protocol) [static]
template<class ADDRESS > static int btlso::SocketImpUtil::socketPair (SocketHandle::Handle * newSockets, SocketImpUtil::Type type, int protocol, int * errorCode) [static]
Create a pair of connected sockets of the specified type and protocol. On success, the specified newSockets will point to the handles for the new sockets. Load the optionally specified errorCode with the platform-specific error number on error. Return 0 on success, and a negative value otherwise representing an error classification. The behavior is undefined unless newSockets refers to at least 2 writable memory locations.
static int btlso::SocketImpUtil::write (const SocketHandle::Handle & socket, const void * buffer, int numBytes, int * errorCode = 0) [static]
Send up to a maximum of the specified numBytes bytes using the specified socket from the specified buffer. Load the optionally specified errorCode with the platform-specific error number on error. Return the non-negative number of bytes written on success, and a negative value otherwise representing an error classification. The behavior is undefined unless 0 <= numBytes and buffer refers to at least numBytes valid memory locations. Note that if socket is in blocking mode, this call blocks until either data is written or an error occurs.
template<class ADDRESS > static int btlso::SocketImpUtil::writeTo (const SocketHandle::Handle & socket, const ADDRESS & toAddress, const void * buffer, int numBytes) [static]
template<class ADDRESS > static int btlso::SocketImpUtil::writeTo (const SocketHandle::Handle & socket, const ADDRESS & toAddress, const void * buffer, int numBytes, int * errorCode) [static]
Send up to a maximum of the specified numBytes bytes using the specified socket from the specified buffer to the destination described by the specified toAddress. Load the optionally specified errorCode with the platform-specific error number on error. Return the non-negative number of bytes written on success, and a negative value otherwise representing an error classification. If socket is a connectionless socket that had previously been connected to a specific destination, the toAddress will override the destination (if different) for this call only. If socket is a connection-oriented socket, toAddress are ignored, making the function equivalent to write. For message-oriented sockets, care must be taken not to exceed the maximum packet size of the underlying subnets; if the data is too long to pass atomically through the underlying protocol, an error indication will be returned and no data will be sent. The behavior is undefined unless 0 <= numBytes and buffer refers to at least numBytes valid memory locations. Note that if socket is in blocking mode, this call blocks until either data is written or an error occurs. Note also that if numBytes is 0, this call returns immediately.
static int btlso::SocketImpUtil::writev (const SocketHandle::Handle & socket, const btls::Ovec * ovec, int numBuffs, int * errorCode = 0) [static]
Send to the specified socket from the buffers specified by ovec where numBuffs is the number of buffers. Load the optionally specified errorCode with the platform-specific error number on error. Return the non-negative number of bytes written on success, and a negative value otherwise representing an error classification. The behavior is undefined unless 0 < numBuffs and iovec refers to buffers at valid writable memory locations. Note that if socket is in blocking mode, this call blocks until either data is written or an error occurs.
template<class ADDRESS > static int btlso::SocketImpUtil::writevTo (const SocketHandle::Handle & socket, const ADDRESS & toAddress, const btls::Ovec * ovec, int numBuffs, int * errorCode = 0) [static]
Send to the specified socket from the buffers specified by ovec where numBuffs is the number of buffers to the destination described by the specified toAddress. Load the optionally specified errorCode with the platform-specific error number on error. Return the non-negative number of bytes written on success and a negative value otherwise representing an error classification. For message-oriented sockets, care must be taken not to exceed the maximum packet size of the underlying subnets; if the data is too long to pass atomically through the underlying protocol, an error indication will be returned and no data will be sent. The behavior is undefined unless the specified socket is not connected, 0 < numBuffs and iovec refers to buffers at valid writable memory locations. Note that if socket is in blocking mode, this call blocks until either data is written or an error occurs.
static int btlso::SocketImpUtil::shutDown (const SocketHandle::Handle & socket, SocketImpUtil::ShutDownType value, int * errorCode = 0) [static]
Shutdown the specified send and/or receive direction of the full-duplexed connection associated with this socket. Return 0 on success, and a non-zero value otherwise representing an error classification. A value of e_SHUTDOWN_RECEIVE or e_SHUTDOWN_SEND will close the receive or send stream, respectively, leaving the other stream unaffected. A value of e_SHUTDOWN_BOTH will close both. Once the receive(send) stream has been closed, any attempted read(write) operations will fail. Any data received after successfully shutting down the receive stream will be acknowledged but silently discarded. Note that this function is typically used to transmit an EOF indication to the peer. Load the optionally specified errorCode with the platform-specific error number on error.
Referenced by btlso::InetStreamSocket< ADDRESS >::shutdown().
static int btlso::SocketImpUtil::startup (int * errorCode = 0) [static]
Initialize the environment for sockets-based activity. Load the optionally specified errorCode with the platform-specific error number on error. Return 0 on success, and a negative value otherwise representing an error classification.
Referenced by btlso::InetStreamSocketFactory< ADDRESS >::InetStreamSocketFactory().
The documentation for this struct was generated from the following file:
btlso_socketimputil.h