BDE 2.16 BETA: Struct bslalg::ScalarPrimitives_Imp
Quick Links:
bsl+bslhdrs | bsl+stdhdrs | bslalg | bsldoc | bslim | bslma | bslmf | bsls | bslscm | bslstl | bsltf
bslalg::ScalarPrimitives_Imp Struct Reference
#include <bslalg_scalarprimitives.h>
Public Types
enum {
USES_BSLMA_ALLOCATOR_TRAITS = 5, PAIR_TRAITS = 4, HAS_TRIVIAL_DEFAULT_CTOR_TRAITS = 3, BITWISE_COPYABLE_TRAITS = 2,
BITWISE_MOVEABLE_TRAITS = 1, NIL_TRAITS = 0
}
Static Public Member Functions
template<typename TARGET_TYPE >
static TARGET_TYPE * unconst (const TARGET_TYPE *pointer)
template<typename TARGET_TYPE >
static void defaultConstruct (TARGET_TYPE *address, bslma::Allocator *allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *)
template<typename TARGET_TYPE >
static void defaultConstruct (TARGET_TYPE *address, bslma::Allocator *allocator, bslmf::MetaInt< HAS_TRIVIAL_DEFAULT_CTOR_TRAITS > *)
template<typename TARGET_TYPE >
static void defaultConstruct (TARGET_TYPE *address, bslma::Allocator *allocator, bslmf::MetaInt< PAIR_TRAITS > *)
template<typename TARGET_TYPE >
static void defaultConstruct (TARGET_TYPE *address, bslma::Allocator *allocator, bslmf::MetaInt< NIL_TRAITS > *)
template<typename TARGET_TYPE >
static void defaultConstruct (TARGET_TYPE *address, bslmf::MetaInt< HAS_TRIVIAL_DEFAULT_CTOR_TRAITS > *)
template<typename TARGET_TYPE >
static void defaultConstruct (TARGET_TYPE *address, bslmf::MetaInt< NIL_TRAITS > *)
template<typename TARGET_TYPE >
static void copyConstruct (TARGET_TYPE *address, const TARGET_TYPE &original, bslma::Allocator *allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *)
template<typename TARGET_TYPE >
static void copyConstruct (TARGET_TYPE *address, const TARGET_TYPE &original, bslma::Allocator *allocator, bslmf::MetaInt< PAIR_TRAITS > *)
template<typename TARGET_TYPE >
static void copyConstruct (TARGET_TYPE *address, const TARGET_TYPE &original, bslma::Allocator *allocator, bslmf::MetaInt< BITWISE_COPYABLE_TRAITS > *)
template<typename TARGET_TYPE >
static void copyConstruct (TARGET_TYPE *address, const TARGET_TYPE &original, bslma::Allocator *allocator, bslmf::MetaInt< NIL_TRAITS > *)
template<typename TARGET_TYPE >
static void copyConstruct (TARGET_TYPE *address, const TARGET_TYPE &original, bslmf::MetaInt< BITWISE_COPYABLE_TRAITS > *)
template<typename TARGET_TYPE >
static void copyConstruct (TARGET_TYPE *address, const TARGET_TYPE &original, bslmf::MetaInt< NIL_TRAITS > *)
template<typename TARGET_TYPE , typename ALLOCATOR >
static void destructiveMove (TARGET_TYPE *address, TARGET_TYPE *original, ALLOCATOR *allocator, bslmf::MetaInt< BITWISE_MOVEABLE_TRAITS > *)
template<typename TARGET_TYPE , typename ALLOCATOR >
static void destructiveMove (TARGET_TYPE *address, TARGET_TYPE *original, ALLOCATOR *allocator, bslmf::MetaInt< NIL_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, bslma::Allocator *allocator, bslmf::MetaInt< BITWISE_COPYABLE_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, bslma::Allocator *allocator, bslmf::MetaInt< PAIR_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, bslma::Allocator *allocator, bslmf::MetaInt< PAIR_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, bslma::Allocator *allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, bslma::Allocator *allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, bslma::Allocator *allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, bslma::Allocator *allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, bslma::Allocator *allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, bslma::Allocator *allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, bslma::Allocator *allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, bslma::Allocator *allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, bslma::Allocator *allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, const ARG10 &a10, bslma::Allocator *allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, const ARG10 &a10, const ARG11 &a11, bslma::Allocator *allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, const ARG10 &a10, const ARG11 &a11, const ARG12 &a12, bslma::Allocator *allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 , typename ARG13 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, const ARG10 &a10, const ARG11 &a11, const ARG12 &a12, const ARG13 &a13, bslma::Allocator *allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 , typename ARG13 , typename ARG14 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, const ARG10 &a10, const ARG11 &a11, const ARG12 &a12, const ARG13 &a13, const ARG14 &a14, bslma::Allocator *allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, bslma::Allocator *allocator, bslmf::MetaInt< NIL_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, bslma::Allocator *allocator, bslmf::MetaInt< NIL_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, bslma::Allocator *allocator, bslmf::MetaInt< NIL_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, bslma::Allocator *allocator, bslmf::MetaInt< NIL_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, bslma::Allocator *allocator, bslmf::MetaInt< NIL_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, bslma::Allocator *allocator, bslmf::MetaInt< NIL_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, bslma::Allocator *allocator, bslmf::MetaInt< NIL_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, bslma::Allocator *allocator, bslmf::MetaInt< NIL_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, bslma::Allocator *allocator, bslmf::MetaInt< NIL_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, const ARG10 &a10, bslma::Allocator *allocator, bslmf::MetaInt< NIL_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, const ARG10 &a10, const ARG11 &a11, bslma::Allocator *allocator, bslmf::MetaInt< NIL_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, const ARG10 &a10, const ARG11 &a11, const ARG12 &a12, bslma::Allocator *allocator, bslmf::MetaInt< NIL_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 , typename ARG13 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, const ARG10 &a10, const ARG11 &a11, const ARG12 &a12, const ARG13 &a13, bslma::Allocator *allocator, bslmf::MetaInt< NIL_TRAITS > *)
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 , typename ARG13 , typename ARG14 >
static void construct (TARGET_TYPE *address, const ARG1 &a1, const ARG2 &a2, const ARG3 &a3, const ARG4 &a4, const ARG5 &a5, const ARG6 &a6, const ARG7 &a7, const ARG8 &a8, const ARG9 &a9, const ARG10 &a10, const ARG11 &a11, const ARG12 &a12, const ARG13 &a13, const ARG14 &a14, bslma::Allocator *allocator, bslmf::MetaInt< NIL_TRAITS > *)
template<typename LHS_TYPE , typename RHS_TYPE >
static void swap (LHS_TYPE &lhs, RHS_TYPE &rhs, bslmf::MetaInt< BITWISE_MOVEABLE_TRAITS > *)
template<typename LHS_TYPE , typename RHS_TYPE >
static void swap (LHS_TYPE &lhs, RHS_TYPE &rhs, bslmf::MetaInt< NIL_TRAITS > *)
Detailed Description
This struct provides a namespace for a suite of utility functions that operate on arrays of elements of a parameterized type TARGET_TYPE. These utility functions are only for the purpose of implementing those in the ScalarPrimitives utility, and should not be used outside this component.
Member Enumeration Documentation
anonymous enum
These constants are used in the overloads below, when the last argument is of type bslmf::MetaInt<N> *, indicating that TARGET_TYPE has the traits for which the enumerator equal to N is named.
Enumerator:
USES_BSLMA_ALLOCATOR_TRAITS
PAIR_TRAITS
HAS_TRIVIAL_DEFAULT_CTOR_TRAITS
BITWISE_COPYABLE_TRAITS
BITWISE_MOVEABLE_TRAITS
NIL_TRAITS
Member Function Documentation
template<typename TARGET_TYPE > TARGET_TYPE * bslalg::ScalarPrimitives_Imp::unconst (const TARGET_TYPE * pointer) [inline, static]
Return the const-unqualified value of the specified pointer. This function resolves into a const_cast and therefore has no runtime cost, it exists only for template argument deduction.
Referenced by construct(), copyConstruct(), and defaultConstruct().
template<typename TARGET_TYPE > void bslalg::ScalarPrimitives_Imp::defaultConstruct (TARGET_TYPE * address, bslma::Allocator * allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *) [inline, static]
Referenced by defaultConstruct(), and bslalg::ScalarPrimitives::defaultConstruct().
template<typename TARGET_TYPE > void bslalg::ScalarPrimitives_Imp::defaultConstruct (TARGET_TYPE * address, bslma::Allocator * allocator, bslmf::MetaInt< HAS_TRIVIAL_DEFAULT_CTOR_TRAITS > *) [inline, static]
References defaultConstruct().
template<typename TARGET_TYPE > void bslalg::ScalarPrimitives_Imp::defaultConstruct (TARGET_TYPE * address, bslma::Allocator * allocator, bslmf::MetaInt< PAIR_TRAITS > *) [inline, static]
References BSLS_UTIL_ADDRESSOF, defaultConstruct(), and unconst().
template<typename TARGET_TYPE > void bslalg::ScalarPrimitives_Imp::defaultConstruct (TARGET_TYPE * address, bslma::Allocator * allocator, bslmf::MetaInt< NIL_TRAITS > *) [inline, static]
Build a TARGET_TYPE object in a default state in the uninitialized memory at the specified address, using the specified allocator to supply memory if TARGET_TYPE uses bslma allocators. Use the default constructor of the parameterized TARGET_TYPE, or memset to 0 if TARGET_TYPE has a trivial default constructor. The last argument is for traits overloading resolution only and its value is ignored.
template<typename TARGET_TYPE > void bslalg::ScalarPrimitives_Imp::defaultConstruct (TARGET_TYPE * address, bslmf::MetaInt< HAS_TRIVIAL_DEFAULT_CTOR_TRAITS > *) [inline, static]
template<typename TARGET_TYPE > void bslalg::ScalarPrimitives_Imp::defaultConstruct (TARGET_TYPE * address, bslmf::MetaInt< NIL_TRAITS > *) [inline, static]
Build a TARGET_TYPE object in a default state in the uninitialized memory at the specified address. Use the default constructor of the parameterized TARGET_TYPE, or memset to 0 if TARGET_TYPE has a trivial default constructor. The last argument is for traits overloading resolution only and its value is ignored.
template<typename TARGET_TYPE > void bslalg::ScalarPrimitives_Imp::copyConstruct (TARGET_TYPE * address, const TARGET_TYPE & original, bslma::Allocator * allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *) [inline, static]
Referenced by copyConstruct(), bslalg::ScalarPrimitives::copyConstruct(), and destructiveMove().
template<typename TARGET_TYPE > void bslalg::ScalarPrimitives_Imp::copyConstruct (TARGET_TYPE * address, const TARGET_TYPE & original, bslma::Allocator * allocator, bslmf::MetaInt< PAIR_TRAITS > *) [inline, static]
References BSLS_UTIL_ADDRESSOF, copyConstruct(), and unconst().
template<typename TARGET_TYPE > void bslalg::ScalarPrimitives_Imp::copyConstruct (TARGET_TYPE * address, const TARGET_TYPE & original, bslma::Allocator * allocator, bslmf::MetaInt< BITWISE_COPYABLE_TRAITS > *) [inline, static]
References BSLS_UTIL_ADDRESSOF.
template<typename TARGET_TYPE > void bslalg::ScalarPrimitives_Imp::copyConstruct (TARGET_TYPE * address, const TARGET_TYPE & original, bslma::Allocator * allocator, bslmf::MetaInt< NIL_TRAITS > *) [inline, static]
Build in the uninitialized memory at the specified address an object of the parameterized TARGET_TYPE that is a copy of the specified original object of the same TARGET_TYPE, using the specified allocator to supply memory. Use the copy constructor of the TARGET_TYPE, or a bit-wise copy if TARGET_TYPE is a bit-wise copyable type. The last argument is for traits overloading resolution only and its value is ignored. Note that a bit-wise copy is only appropriate if TARGET_TYPE does not take allocators.
template<typename TARGET_TYPE > void bslalg::ScalarPrimitives_Imp::copyConstruct (TARGET_TYPE * address, const TARGET_TYPE & original, bslmf::MetaInt< BITWISE_COPYABLE_TRAITS > *) [inline, static]
References BSLS_UTIL_ADDRESSOF.
template<typename TARGET_TYPE > void bslalg::ScalarPrimitives_Imp::copyConstruct (TARGET_TYPE * address, const TARGET_TYPE & original, bslmf::MetaInt< NIL_TRAITS > *) [inline, static]
Build in the uninitialized memory at the specified address an object of the parameterized TARGET_TYPE that is a copy of the specified original object of the same TARGET_TYPE. Use the copy constructor of the TARGET_TYPE, or a bit-wise copy if TARGET_TYPE is a bit-wise copyable type. The last argument is for traits overloading resolution only and its value is ignored. Note that a bit-wise copy is only appropriate if TARGET_TYPE does not take allocators.
template<typename TARGET_TYPE , typename ALLOCATOR > void bslalg::ScalarPrimitives_Imp::destructiveMove (TARGET_TYPE * address, TARGET_TYPE * original, ALLOCATOR * allocator, bslmf::MetaInt< BITWISE_MOVEABLE_TRAITS > *) [inline, static]
Referenced by bslalg::ScalarPrimitives::destructiveMove().
template<typename TARGET_TYPE , typename ALLOCATOR > void bslalg::ScalarPrimitives_Imp::destructiveMove (TARGET_TYPE * address, TARGET_TYPE * original, ALLOCATOR * allocator, bslmf::MetaInt< NIL_TRAITS > *) [inline, static]
Build a copy of the specified original in the uninitialized memory at the specified address. Use the copy constructor of the parameterized TARGET_TYPE (or a bit-wise copy if TARGET_TYPE is bit-wise moveable). If TARGET_TYPE is not bit-wise moveable, also destroy the original. The last argument is for traits overloading resolution only and its value is ignored.
References copyConstruct().
template<typename TARGET_TYPE , typename ARG1 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, bslma::Allocator * allocator, bslmf::MetaInt< BITWISE_COPYABLE_TRAITS > *) [inline, static]
Build an object from the specified a1 in the uninitialized memory at the specified address. The specified allocator is ignored. Use the parameterized TARGET_TYPE constructor with the signature TARGET_TYPE(ARG1 const&) or bitwise copy for non-fundamental types. The traits argument is for overloading resolution only and is ignored.
References BSLS_UTIL_ADDRESSOF.
Referenced by construct(), and bslalg::ScalarPrimitives::construct().
template<typename TARGET_TYPE , typename ARG1 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, bslma::Allocator * allocator, bslmf::MetaInt< PAIR_TRAITS > *) [inline, static]
References BSLS_UTIL_ADDRESSOF, construct(), and unconst().
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, bslma::Allocator * allocator, bslmf::MetaInt< PAIR_TRAITS > *) [inline, static]
Build an object from the specified a1 (and optionally a2) in the uninitialized memory at the specified address. The specified allocator is passed through to the first_type and second_type members of TARGET_TYPE. Use the parameterized TARGET_TYPE constructor with the signature TARGET_TYPE(ARG1 const&, ...). The traits argument is for overloading resolution only and is ignored. Note that because pair types have at most two constructor arguments, only two versions of this function are needed.
References BSLS_UTIL_ADDRESSOF, construct(), and unconst().
template<typename TARGET_TYPE , typename ARG1 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, bslma::Allocator * allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, bslma::Allocator * allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, bslma::Allocator * allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, bslma::Allocator * allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, bslma::Allocator * allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, bslma::Allocator * allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, bslma::Allocator * allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, bslma::Allocator * allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, bslma::Allocator * allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, const ARG10 & a10, bslma::Allocator * allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, const ARG10 & a10, const ARG11 & a11, bslma::Allocator * allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, const ARG10 & a10, const ARG11 & a11, const ARG12 & a12, bslma::Allocator * allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 , typename ARG13 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, const ARG10 & a10, const ARG11 & a11, const ARG12 & a12, const ARG13 & a13, bslma::Allocator * allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 , typename ARG13 , typename ARG14 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, const ARG10 & a10, const ARG11 & a11, const ARG12 & a12, const ARG13 & a13, const ARG14 & a14, bslma::Allocator * allocator, bslmf::MetaInt< USES_BSLMA_ALLOCATOR_TRAITS > *) [inline, static]
Build an object of the parameterized TARGET_TYPE in the uninitialized memory at the specified address, passing the specified a1 up to a14 arguments of the corresponding parameterized ARG1 up to ARG14 types to the TARGET_TYPE constructor with the signature TARGET_TYPE(ARG1 const&, ..., bslma::Allocator *), and pass the specified allocator in the last position. The last argument is for overloading resolution only and its value is ignored.
template<typename TARGET_TYPE , typename ARG1 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, bslma::Allocator * allocator, bslmf::MetaInt< NIL_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, bslma::Allocator * allocator, bslmf::MetaInt< NIL_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, bslma::Allocator * allocator, bslmf::MetaInt< NIL_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, bslma::Allocator * allocator, bslmf::MetaInt< NIL_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, bslma::Allocator * allocator, bslmf::MetaInt< NIL_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, bslma::Allocator * allocator, bslmf::MetaInt< NIL_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, bslma::Allocator * allocator, bslmf::MetaInt< NIL_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, bslma::Allocator * allocator, bslmf::MetaInt< NIL_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, bslma::Allocator * allocator, bslmf::MetaInt< NIL_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, const ARG10 & a10, bslma::Allocator * allocator, bslmf::MetaInt< NIL_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, const ARG10 & a10, const ARG11 & a11, bslma::Allocator * allocator, bslmf::MetaInt< NIL_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, const ARG10 & a10, const ARG11 & a11, const ARG12 & a12, bslma::Allocator * allocator, bslmf::MetaInt< NIL_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 , typename ARG13 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, const ARG10 & a10, const ARG11 & a11, const ARG12 & a12, const ARG13 & a13, bslma::Allocator * allocator, bslmf::MetaInt< NIL_TRAITS > *) [inline, static]
template<typename TARGET_TYPE , typename ARG1 , typename ARG2 , typename ARG3 , typename ARG4 , typename ARG5 , typename ARG6 , typename ARG7 , typename ARG8 , typename ARG9 , typename ARG10 , typename ARG11 , typename ARG12 , typename ARG13 , typename ARG14 > void bslalg::ScalarPrimitives_Imp::construct (TARGET_TYPE * address, const ARG1 & a1, const ARG2 & a2, const ARG3 & a3, const ARG4 & a4, const ARG5 & a5, const ARG6 & a6, const ARG7 & a7, const ARG8 & a8, const ARG9 & a9, const ARG10 & a10, const ARG11 & a11, const ARG12 & a12, const ARG13 & a13, const ARG14 & a14, bslma::Allocator * allocator, bslmf::MetaInt< NIL_TRAITS > *) [inline, static]
Build an object of the parameterized TARGET_TYPE in the uninitialized memory at the specified address, passing the specified a1 up to a14 arguments of the corresponding parameterized ARG1 up to ARG14 types to the TARGET_TYPE constructor with the signature TARGET_TYPE(ARG1 const&, ...). The specified allocator is not passed through to the TARGET_TYPE constructor. The last argument is for overloading resolution only and is ignored.
template<typename LHS_TYPE , typename RHS_TYPE > void bslalg::ScalarPrimitives_Imp::swap (LHS_TYPE & lhs, RHS_TYPE & rhs, bslmf::MetaInt< BITWISE_MOVEABLE_TRAITS > *) [static]
References BSLS_UTIL_ADDRESSOF.
Referenced by bslalg::ScalarPrimitives::swap().
template<typename LHS_TYPE , typename RHS_TYPE > void bslalg::ScalarPrimitives_Imp::swap (LHS_TYPE & lhs, RHS_TYPE & rhs, bslmf::MetaInt< NIL_TRAITS > *) [static]
Swap the contents of the specified lhs object of the parameterized LHS_TYPE with the specified rhs object of the parameterized RHS_TYPE. Use a three-way bit-wise copy (with a temporary uninitialized buffer), if LHS_TYPE and RHS_TYPE are the same bit-wise moveable type, and a three-way assignment with a temporary if not. The last argument is for overloading resolution only and is ignored.
The documentation for this struct was generated from the following file:
bslalg_scalarprimitives.h