#!/bin/sh

./generate_configschema

./generate s_baltst_address.xsd
./generate s_baltst_basicrecord.xsd
./generate s_baltst_basicschema.xsd
./generate s_baltst_bigrecord.xsd
./generate s_baltst_customint.xsd
./generate s_baltst_customizedstring.xsd
./generate s_baltst_customstring.xsd
./generate s_baltst_employee.xsd
./generate s_baltst_enumerated.xsd
./generate s_baltst_featuretestmessage.xsd
./generate s_baltst_mychoice.xsd
./generate s_baltst_myenumeration.xsd
./generate s_baltst_myenumerationwithfallback.xsd
./generate s_baltst_mysequence.xsd
./generate s_baltst_mysequencewithanonymouschoice.xsd
./generate s_baltst_mysequencewitharray.xsd
./generate s_baltst_mysequencewithattributes.xsd
./generate s_baltst_mysequencewithchoice.xsd
./generate s_baltst_mysequencewithchoicearray.xsd
./generate s_baltst_mysequencewithchoices.xsd
./generate s_baltst_mysequencewithdecimalattribute.xsd
./generate s_baltst_mysequencewithdoubleattribute.xsd
./generate s_baltst_mysequencewithnillable.xsd
./generate s_baltst_mysequencewithnillables.xsd
./generate s_baltst_mysequencewithnullable.xsd
./generate s_baltst_mysequencewithnullables.xsd
./generate s_baltst_mysequencewithprecisiondecimalattribute.xsd
./generate s_baltst_mysimplecontent.xsd
./generate s_baltst_mysimpleintcontent.xsd
./generate s_baltst_ratsnest.xsd
./generate s_baltst_rawdata.xsd
./generate s_baltst_rawdataswitched.xsd
./generate s_baltst_rawdataunformatted.xsd
./generate s_baltst_request.xsd
./generate s_baltst_response.xsd
./generate s_baltst_sequencewithanonymity.xsd
./generate s_baltst_simplerequest.xsd
./generate s_baltst_sqrt.xsd
./generate s_baltst_sqrtf.xsd
./generate s_baltst_timingrequest.xsd
./generate s_baltst_topchoice.xsd
./generate s_baltst_unsignedsequence.xsd
./generate s_baltst_voidsequence.xsd
