// s_baltst_mysequencewithprecisiondecimalattribute.cpp        *DO NOT EDIT*         @generated -*-C++-*-

#include <bsls_ident.h>
BSLS_IDENT_RCSID(s_baltst_mysequencewithprecisiondecimalattribute_cpp,"$Id$ $CSID$")

#include <s_baltst_mysequencewithprecisiondecimalattribute.h>

#include <bdlat_formattingmode.h>
#include <bdlat_valuetypefunctions.h>
#include <bdlb_print.h>
#include <bdlb_printmethods.h>
#include <bdlb_string.h>

#include <bdlb_nullablevalue.h>
#include <bdldfp_decimal.h>
#include <s_baltst_address.h>
#include <s_baltst_basicrecord.h>
#include <s_baltst_customint.h>
#include <s_baltst_customstring.h>
#include <s_baltst_customizedstring.h>
#include <s_baltst_enumerated.h>
#include <s_baltst_mychoice.h>
#include <s_baltst_myenumeration.h>
#include <s_baltst_mysequence.h>
#include <s_baltst_mysequencewithanonymouschoicechoice.h>
#include <s_baltst_mysequencewitharray.h>
#include <s_baltst_mysequencewithattributes.h>
#include <s_baltst_mysequencewithdecimalattribute.h>
#include <s_baltst_mysequencewithdoubleattribute.h>
#include <s_baltst_mysequencewithnillable.h>
#include <s_baltst_mysequencewithnullable.h>
#include <bslim_printer.h>
#include <bsls_assert.h>

#include <bsl_iomanip.h>
#include <bsl_limits.h>
#include <bsl_ostream.h>

namespace BloombergLP {
namespace s_baltst {

               // ---------------------------------------------
               // class MySequenceWithPrecisionDecimalAttribute
               // ---------------------------------------------

// CONSTANTS

const char MySequenceWithPrecisionDecimalAttribute::CLASS_NAME[] = "MySequenceWithPrecisionDecimalAttribute";

const bdlat_AttributeInfo MySequenceWithPrecisionDecimalAttribute::ATTRIBUTE_INFO_ARRAY[] = {
    {
        ATTRIBUTE_ID_ATTRIBUTE1,
        "attribute1",
        sizeof("attribute1") - 1,
        "",
        bdlat_FormattingMode::e_DEFAULT
      | bdlat_FormattingMode::e_ATTRIBUTE
    }
};

// CLASS METHODS

const bdlat_AttributeInfo *MySequenceWithPrecisionDecimalAttribute::lookupAttributeInfo(
        const char *name,
        int         nameLength)
{
    for (int i = 0; i < 1; ++i) {
        const bdlat_AttributeInfo& attributeInfo =
                    MySequenceWithPrecisionDecimalAttribute::ATTRIBUTE_INFO_ARRAY[i];

        if (nameLength == attributeInfo.d_nameLength
        &&  0 == bsl::memcmp(attributeInfo.d_name_p, name, nameLength))
        {
            return &attributeInfo;
        }
    }

    return 0;
}

const bdlat_AttributeInfo *MySequenceWithPrecisionDecimalAttribute::lookupAttributeInfo(int id)
{
    switch (id) {
      case ATTRIBUTE_ID_ATTRIBUTE1:
        return &ATTRIBUTE_INFO_ARRAY[ATTRIBUTE_INDEX_ATTRIBUTE1];
      default:
        return 0;
    }
}

// CREATORS

MySequenceWithPrecisionDecimalAttribute::MySequenceWithPrecisionDecimalAttribute()
: d_attribute1()
{
}

MySequenceWithPrecisionDecimalAttribute::MySequenceWithPrecisionDecimalAttribute(const MySequenceWithPrecisionDecimalAttribute& original)
: d_attribute1(original.d_attribute1)
{
}

MySequenceWithPrecisionDecimalAttribute::~MySequenceWithPrecisionDecimalAttribute()
{
}

// MANIPULATORS

MySequenceWithPrecisionDecimalAttribute&
MySequenceWithPrecisionDecimalAttribute::operator=(const MySequenceWithPrecisionDecimalAttribute& rhs)
{
    if (this != &rhs) {
        d_attribute1 = rhs.d_attribute1;
    }

    return *this;
}

#if defined(BSLS_COMPILERFEATURES_SUPPORT_RVALUE_REFERENCES) \
 && defined(BSLS_COMPILERFEATURES_SUPPORT_NOEXCEPT)
MySequenceWithPrecisionDecimalAttribute&
MySequenceWithPrecisionDecimalAttribute::operator=(MySequenceWithPrecisionDecimalAttribute&& rhs)
{
    if (this != &rhs) {
        d_attribute1 = bsl::move(rhs.d_attribute1);
    }

    return *this;
}
#endif

void MySequenceWithPrecisionDecimalAttribute::reset()
{
    bdlat_ValueTypeFunctions::reset(&d_attribute1);
}

// ACCESSORS

bsl::ostream& MySequenceWithPrecisionDecimalAttribute::print(
        bsl::ostream& stream,
        int           level,
        int           spacesPerLevel) const
{
    bslim::Printer printer(&stream, level, spacesPerLevel);
    printer.start();
    printer.printAttribute("attribute1", this->attribute1());
    printer.end();
    return stream;
}


}  // close package namespace
}  // close enterprise namespace

// GENERATED BY BLP_BAS_CODEGEN_2020.12.08
// USING bas_codegen.pl s_baltst.xsd -m msg -p s_baltst -C tmp_singles --msgSplit 1 --noExternalization --noHashSupport --noAggregateConversion
// ----------------------------------------------------------------------------
// NOTICE:
//      Copyright 2020 Bloomberg Finance L.P. All rights reserved.
//      Property of Bloomberg Finance L.P. (BFLP)
//      This software is made available solely pursuant to the
//      terms of a BFLP license agreement which governs its use.
// ------------------------------- END-OF-FILE --------------------------------
