// s_baltst_mysequencewithdefault.cpp    *DO NOT EDIT*     @generated -*-C++-*-

#include <bsls_ident.h>
BSLS_IDENT_RCSID(s_baltst_mysequencewithdefault_cpp, "$Id$ $CSID$")

#include <s_baltst_mysequencewithdefault.h>

#include <bdlat_formattingmode.h>
#include <bdlat_valuetypefunctions.h>
#include <bdlb_print.h>
#include <bdlb_printmethods.h>
#include <bdlb_string.h>

#include <bslim_printer.h>
#include <bsls_assert.h>

#include <bsl_cstring.h>
#include <bsl_iomanip.h>
#include <bsl_limits.h>
#include <bsl_ostream.h>
#include <bsl_utility.h>

namespace BloombergLP {
namespace s_baltst {

                        // ---------------------------
                        // class MySequenceWithDefault
                        // ---------------------------

// CONSTANTS

const char MySequenceWithDefault::CLASS_NAME[] = "MySequenceWithDefault";

const int MySequenceWithDefault::DEFAULT_INITIALIZER_ATTRIBUTE2 = 42;

const bdlat_AttributeInfo MySequenceWithDefault::ATTRIBUTE_INFO_ARRAY[] = {
    {
        ATTRIBUTE_ID_ATTRIBUTE1,
        "attribute1",
        sizeof("attribute1") - 1,
        "",
        bdlat_FormattingMode::e_DEC
    },
    {
        ATTRIBUTE_ID_ATTRIBUTE2,
        "attribute2",
        sizeof("attribute2") - 1,
        "",
        bdlat_FormattingMode::e_DEC
      | bdlat_FormattingMode::e_DEFAULT_VALUE
    }
};

// CLASS METHODS

const bdlat_AttributeInfo *MySequenceWithDefault::lookupAttributeInfo(
        const char *name,
        int         nameLength)
{
    for (int i = 0; i < 2; ++i) {
        const bdlat_AttributeInfo& attributeInfo =
                    MySequenceWithDefault::ATTRIBUTE_INFO_ARRAY[i];

        if (nameLength == attributeInfo.d_nameLength
        &&  0 == bsl::memcmp(attributeInfo.d_name_p, name, nameLength))
        {
            return &attributeInfo;
        }
    }

    return 0;
}

const bdlat_AttributeInfo *MySequenceWithDefault::lookupAttributeInfo(int id)
{
    switch (id) {
      case ATTRIBUTE_ID_ATTRIBUTE1:
        return &ATTRIBUTE_INFO_ARRAY[ATTRIBUTE_INDEX_ATTRIBUTE1];
      case ATTRIBUTE_ID_ATTRIBUTE2:
        return &ATTRIBUTE_INFO_ARRAY[ATTRIBUTE_INDEX_ATTRIBUTE2];
      default:
        return 0;
    }
}

// CREATORS

MySequenceWithDefault::MySequenceWithDefault()
: d_attribute1()
, d_attribute2(DEFAULT_INITIALIZER_ATTRIBUTE2)
{
}

// MANIPULATORS

void MySequenceWithDefault::reset()
{
    bdlat_ValueTypeFunctions::reset(&d_attribute1);
    d_attribute2 = DEFAULT_INITIALIZER_ATTRIBUTE2;
}

// ACCESSORS

bsl::ostream& MySequenceWithDefault::print(bsl::ostream& stream,
                                           int           level,
                                           int           spacesPerLevel) const
{
    bslim::Printer printer(&stream, level, spacesPerLevel);
    printer.start();
    printer.printAttribute("attribute1", this->attribute1());
    printer.printAttribute("attribute2", this->attribute2());
    printer.end();
    return stream;
}


}  // close package namespace
}  // close enterprise namespace

// GENERATED BY BLP_BAS_CODEGEN_2025.06.26
// USING bas_codegen.pl s_baltst_mysequencewithdefault.xsd --mode msg --includedir . --msgComponent mysequencewithdefault --noRecurse --noExternalization --noHashSupport --noAggregateConversion
// ----------------------------------------------------------------------------
// NOTICE:
//      Copyright 2025 Bloomberg Finance L.P. All rights reserved.
//      Property of Bloomberg Finance L.P. (BFLP)
//      This software is made available solely pursuant to the
//      terms of a BFLP license agreement which governs its use.
// ------------------------------- END-OF-FILE --------------------------------
