// s_baltst_myintenumeration.cpp       *DO NOT EDIT*       @generated -*-C++-*-

#include <bsls_ident.h>
BSLS_IDENT_RCSID(s_baltst_myintenumeration_cpp, "$Id$ $CSID$")

#include <s_baltst_myintenumeration.h>

#include <bdlat_formattingmode.h>
#include <bdlat_valuetypefunctions.h>
#include <bdlde_utf8util.h>
#include <bdlb_print.h>
#include <bdlb_printmethods.h>
#include <bdlb_string.h>

#include <bslim_printer.h>
#include <bsls_assert.h>

#include <bsl_cstring.h>
#include <bsl_iomanip.h>
#include <bsl_limits.h>
#include <bsl_ostream.h>
#include <bsl_utility.h>

namespace BloombergLP {
namespace s_baltst {

                           // ----------------------
                           // class MyIntEnumeration
                           // ----------------------

// PUBLIC CLASS METHODS

int MyIntEnumeration::checkRestrictions(const int& value)
{
    if (0 != value
     && 1 != value) {
        return -1;
    }

    return 0;
}

// CONSTANTS

const char MyIntEnumeration::CLASS_NAME[] = "MyIntEnumeration";

const int MyIntEnumeration::VALUE1 = 0;

const int MyIntEnumeration::VALUE2 = 1;



                        // ----------------------------
                        // class MyIntEnumerationRecord
                        // ----------------------------

// CONSTANTS

const char MyIntEnumerationRecord::CLASS_NAME[] = "MyIntEnumerationRecord";

const bdlat_AttributeInfo MyIntEnumerationRecord::ATTRIBUTE_INFO_ARRAY[] = {
    {
        ATTRIBUTE_ID_VALUE,
        "value",
        sizeof("value") - 1,
        "",
        bdlat_FormattingMode::e_DEC
    }
};

// CLASS METHODS

const bdlat_AttributeInfo *MyIntEnumerationRecord::lookupAttributeInfo(
        const char *name,
        int         nameLength)
{
    for (int i = 0; i < 1; ++i) {
        const bdlat_AttributeInfo& attributeInfo =
                    MyIntEnumerationRecord::ATTRIBUTE_INFO_ARRAY[i];

        if (nameLength == attributeInfo.d_nameLength
        &&  0 == bsl::memcmp(attributeInfo.d_name_p, name, nameLength))
        {
            return &attributeInfo;
        }
    }

    return 0;
}

const bdlat_AttributeInfo *MyIntEnumerationRecord::lookupAttributeInfo(int id)
{
    switch (id) {
      case ATTRIBUTE_ID_VALUE:
        return &ATTRIBUTE_INFO_ARRAY[ATTRIBUTE_INDEX_VALUE];
      default:
        return 0;
    }
}

// CREATORS

MyIntEnumerationRecord::MyIntEnumerationRecord()
: d_value()
{
}

MyIntEnumerationRecord::MyIntEnumerationRecord(const MyIntEnumerationRecord& original)
: d_value(original.d_value)
{
}

MyIntEnumerationRecord::~MyIntEnumerationRecord()
{
}

// MANIPULATORS

MyIntEnumerationRecord&
MyIntEnumerationRecord::operator=(const MyIntEnumerationRecord& rhs)
{
    if (this != &rhs) {
        d_value = rhs.d_value;
    }

    return *this;
}

#if defined(BSLS_COMPILERFEATURES_SUPPORT_RVALUE_REFERENCES) \
 && defined(BSLS_COMPILERFEATURES_SUPPORT_NOEXCEPT)
MyIntEnumerationRecord&
MyIntEnumerationRecord::operator=(MyIntEnumerationRecord&& rhs)
{
    if (this != &rhs) {
        d_value = bsl::move(rhs.d_value);
    }

    return *this;
}
#endif

void MyIntEnumerationRecord::reset()
{
    bdlat_ValueTypeFunctions::reset(&d_value);
}

// ACCESSORS

bsl::ostream& MyIntEnumerationRecord::print(bsl::ostream& stream,
                                            int           level,
                                            int           spacesPerLevel) const
{
    bslim::Printer printer(&stream, level, spacesPerLevel);
    printer.start();
    printer.printAttribute("value", this->value());
    printer.end();
    return stream;
}


}  // close package namespace
}  // close enterprise namespace

// GENERATED BY BLP_BAS_CODEGEN_2023.10.25
// USING bas_codegen.pl s_baltst_myintenumeration.xsd --mode msg --includedir . --msgComponent myintenumeration --noRecurse --noExternalization --noHashSupport --noAggregateConversion
// ----------------------------------------------------------------------------
// NOTICE:
//      Copyright 2023 Bloomberg Finance L.P. All rights reserved.
//      Property of Bloomberg Finance L.P. (BFLP)
//      This software is made available solely pursuant to the
//      terms of a BFLP license agreement which governs its use.
// ------------------------------- END-OF-FILE --------------------------------
