#!/bin/sh

echo "Linking library contents..."
ln -s LIBRARY/src/bid64_acos.c             library_src_bid64_acos.c
ln -s LIBRARY/src/bid64_acosh.c            library_src_bid64_acosh.c
ln -s LIBRARY/src/bid64_asin.c             library_src_bid64_asin.c
ln -s LIBRARY/src/bid64_asinh.c            library_src_bid64_asinh.c
ln -s LIBRARY/src/bid64_atan.c             library_src_bid64_atan.c
ln -s LIBRARY/src/bid64_atan2.c            library_src_bid64_atan2.c
ln -s LIBRARY/src/bid64_atanh.c            library_src_bid64_atanh.c
ln -s LIBRARY/src/bid64_cbrt.c             library_src_bid64_cbrt.c
ln -s LIBRARY/src/bid64_cos.c              library_src_bid64_cos.c
ln -s LIBRARY/src/bid64_cosh.c             library_src_bid64_cosh.c
ln -s LIBRARY/src/bid64_erf.c              library_src_bid64_erf.c
ln -s LIBRARY/src/bid64_erfc.c             library_src_bid64_erfc.c
ln -s LIBRARY/src/bid64_exp.c              library_src_bid64_exp.c
ln -s LIBRARY/src/bid64_exp10.c            library_src_bid64_exp10.c
ln -s LIBRARY/src/bid64_exp2.c             library_src_bid64_exp2.c
ln -s LIBRARY/src/bid64_expm1.c            library_src_bid64_expm1.c
ln -s LIBRARY/src/bid64_hypot.c            library_src_bid64_hypot.c
ln -s LIBRARY/src/bid64_lgamma.c           library_src_bid64_lgamma.c
ln -s LIBRARY/src/bid64_log.c              library_src_bid64_log.c
ln -s LIBRARY/src/bid64_log10.c            library_src_bid64_log10.c
ln -s LIBRARY/src/bid64_log1p.c            library_src_bid64_log1p.c
ln -s LIBRARY/src/bid64_log2.c             library_src_bid64_log2.c
ln -s LIBRARY/src/bid64_pow.c              library_src_bid64_pow.c
ln -s LIBRARY/src/bid64_sin.c              library_src_bid64_sin.c
ln -s LIBRARY/src/bid64_sinh.c             library_src_bid64_sinh.c
ln -s LIBRARY/src/bid64_tan.c              library_src_bid64_tan.c
ln -s LIBRARY/src/bid64_tanh.c             library_src_bid64_tanh.c
ln -s LIBRARY/src/bid64_tgamma.c           library_src_bid64_tgamma.c
ln -s LIBRARY/src/bid128_acos.c            library_src_bid128_acos.c
ln -s LIBRARY/src/bid128_acosh.c           library_src_bid128_acosh.c
ln -s LIBRARY/src/bid128_asin.c            library_src_bid128_asin.c
ln -s LIBRARY/src/bid128_asinh.c           library_src_bid128_asinh.c
ln -s LIBRARY/src/bid128_atan.c            library_src_bid128_atan.c
ln -s LIBRARY/src/bid128_atan2.c           library_src_bid128_atan2.c
ln -s LIBRARY/src/bid128_atanh.c           library_src_bid128_atanh.c
ln -s LIBRARY/src/bid128_cbrt.c            library_src_bid128_cbrt.c
ln -s LIBRARY/src/bid128_cos.c             library_src_bid128_cos.c
ln -s LIBRARY/src/bid128_cosh.c            library_src_bid128_cosh.c
ln -s LIBRARY/src/bid128_erf.c             library_src_bid128_erf.c
ln -s LIBRARY/src/bid128_erfc.c            library_src_bid128_erfc.c
ln -s LIBRARY/src/bid128_exp.c             library_src_bid128_exp.c
ln -s LIBRARY/src/bid128_exp10.c           library_src_bid128_exp10.c
ln -s LIBRARY/src/bid128_exp2.c            library_src_bid128_exp2.c
ln -s LIBRARY/src/bid128_expm1.c           library_src_bid128_expm1.c
ln -s LIBRARY/src/bid128_hypot.c           library_src_bid128_hypot.c
ln -s LIBRARY/src/bid128_lgamma.c          library_src_bid128_lgamma.c
ln -s LIBRARY/src/bid128_log.c             library_src_bid128_log.c
ln -s LIBRARY/src/bid128_log10.c           library_src_bid128_log10.c
ln -s LIBRARY/src/bid128_log1p.c           library_src_bid128_log1p.c
ln -s LIBRARY/src/bid128_log2.c            library_src_bid128_log2.c
ln -s LIBRARY/src/bid128_pow.c             library_src_bid128_pow.c
ln -s LIBRARY/src/bid128_sin.c             library_src_bid128_sin.c
ln -s LIBRARY/src/bid128_sinh.c            library_src_bid128_sinh.c
ln -s LIBRARY/src/bid128_tan.c             library_src_bid128_tan.c
ln -s LIBRARY/src/bid128_tanh.c            library_src_bid128_tanh.c
ln -s LIBRARY/src/bid128_tgamma.c          library_src_bid128_tgamma.c
ln -s LIBRARY/src/bid32_add.c              library_src_bid32_add.c
ln -s LIBRARY/src/bid32_compare.c          library_src_bid32_compare.c
ln -s LIBRARY/src/bid32_div.c              library_src_bid32_div.c
ln -s LIBRARY/src/bid32_fdimd.c            library_src_bid32_fdimd.c
ln -s LIBRARY/src/bid32_fma.c              library_src_bid32_fma.c
ln -s LIBRARY/src/bid32_fmod.c             library_src_bid32_fmod.c
ln -s LIBRARY/src/bid32_frexp.c            library_src_bid32_frexp.c
ln -s LIBRARY/src/bid32_ldexp.c            library_src_bid32_ldexp.c
ln -s LIBRARY/src/bid32_llrintd.c          library_src_bid32_llrintd.c
ln -s LIBRARY/src/bid32_logb.c             library_src_bid32_logb.c
ln -s LIBRARY/src/bid32_logbd.c            library_src_bid32_logbd.c
ln -s LIBRARY/src/bid32_lrintd.c           library_src_bid32_lrintd.c
ln -s LIBRARY/src/bid32_lround.c           library_src_bid32_lround.c
ln -s LIBRARY/src/bid32_minmax.c           library_src_bid32_minmax.c
ln -s LIBRARY/src/bid32_modf.c             library_src_bid32_modf.c
ln -s LIBRARY/src/bid32_mul.c              library_src_bid32_mul.c
ln -s LIBRARY/src/bid32_nearbyintd.c       library_src_bid32_nearbyintd.c
ln -s LIBRARY/src/bid32_next.c             library_src_bid32_next.c
ln -s LIBRARY/src/bid32_nexttowardd.c      library_src_bid32_nexttowardd.c
ln -s LIBRARY/src/bid32_noncomp.c          library_src_bid32_noncomp.c
ln -s LIBRARY/src/bid32_quantexpd.c        library_src_bid32_quantexpd.c
ln -s LIBRARY/src/bid32_quantize.c         library_src_bid32_quantize.c
ln -s LIBRARY/src/bid32_rem.c              library_src_bid32_rem.c
ln -s LIBRARY/src/bid32_round_integral.c   library_src_bid32_round_integral.c
ln -s LIBRARY/src/bid32_scalb.c            library_src_bid32_scalb.c
ln -s LIBRARY/src/bid32_scalbl.c           library_src_bid32_scalbl.c
ln -s LIBRARY/src/bid32_sqrt.c             library_src_bid32_sqrt.c
ln -s LIBRARY/src/bid32_string.c           library_src_bid32_string.c
ln -s LIBRARY/src/bid32_to_int16.c         library_src_bid32_to_int16.c
ln -s LIBRARY/src/bid32_to_int32.c         library_src_bid32_to_int32.c
ln -s LIBRARY/src/bid32_to_int64.c         library_src_bid32_to_int64.c
ln -s LIBRARY/src/bid32_to_int8.c          library_src_bid32_to_int8.c
ln -s LIBRARY/src/bid32_to_uint16.c        library_src_bid32_to_uint16.c
ln -s LIBRARY/src/bid32_to_uint32.c        library_src_bid32_to_uint32.c
ln -s LIBRARY/src/bid32_to_uint64.c        library_src_bid32_to_uint64.c
ln -s LIBRARY/src/bid32_to_uint8.c         library_src_bid32_to_uint8.c
ln -s LIBRARY/src/bid64_add.c              library_src_bid64_add.c
ln -s LIBRARY/src/bid64_compare.c          library_src_bid64_compare.c
ln -s LIBRARY/src/bid64_div.c              library_src_bid64_div.c
ln -s LIBRARY/src/bid64_fdimd.c            library_src_bid64_fdimd.c
ln -s LIBRARY/src/bid64_fma.c              library_src_bid64_fma.c
ln -s LIBRARY/src/bid64_fmod.c             library_src_bid64_fmod.c
ln -s LIBRARY/src/bid64_frexp.c            library_src_bid64_frexp.c
ln -s LIBRARY/src/bid64_ldexp.c            library_src_bid64_ldexp.c
ln -s LIBRARY/src/bid64_llrintd.c          library_src_bid64_llrintd.c
ln -s LIBRARY/src/bid64_logb.c             library_src_bid64_logb.c
ln -s LIBRARY/src/bid64_logbd.c            library_src_bid64_logbd.c
ln -s LIBRARY/src/bid64_lrintd.c           library_src_bid64_lrintd.c
ln -s LIBRARY/src/bid64_lround.c           library_src_bid64_lround.c
ln -s LIBRARY/src/bid64_minmax.c           library_src_bid64_minmax.c
ln -s LIBRARY/src/bid64_modf.c             library_src_bid64_modf.c
ln -s LIBRARY/src/bid64_mul.c              library_src_bid64_mul.c
ln -s LIBRARY/src/bid64_nearbyintd.c       library_src_bid64_nearbyintd.c
ln -s LIBRARY/src/bid64_next.c             library_src_bid64_next.c
ln -s LIBRARY/src/bid64_nexttowardd.c      library_src_bid64_nexttowardd.c
ln -s LIBRARY/src/bid64_noncomp.c          library_src_bid64_noncomp.c
ln -s LIBRARY/src/bid64_quantexpd.c        library_src_bid64_quantexpd.c
ln -s LIBRARY/src/bid64_quantize.c         library_src_bid64_quantize.c
ln -s LIBRARY/src/bid64_rem.c              library_src_bid64_rem.c
ln -s LIBRARY/src/bid64_round_integral.c   library_src_bid64_round_integral.c
ln -s LIBRARY/src/bid64_scalb.c            library_src_bid64_scalb.c
ln -s LIBRARY/src/bid64_scalbl.c           library_src_bid64_scalbl.c
ln -s LIBRARY/src/bid64_sqrt.c             library_src_bid64_sqrt.c
ln -s LIBRARY/src/bid64_string.c           library_src_bid64_string.c
ln -s LIBRARY/src/bid64_to_int16.c         library_src_bid64_to_int16.c
ln -s LIBRARY/src/bid64_to_int32.c         library_src_bid64_to_int32.c
ln -s LIBRARY/src/bid64_to_int64.c         library_src_bid64_to_int64.c
ln -s LIBRARY/src/bid64_to_int8.c          library_src_bid64_to_int8.c
ln -s LIBRARY/src/bid64_to_uint16.c        library_src_bid64_to_uint16.c
ln -s LIBRARY/src/bid64_to_uint32.c        library_src_bid64_to_uint32.c
ln -s LIBRARY/src/bid64_to_uint64.c        library_src_bid64_to_uint64.c
ln -s LIBRARY/src/bid64_to_uint8.c         library_src_bid64_to_uint8.c
ln -s LIBRARY/src/bid128_add.c             library_src_bid128_add.c
ln -s LIBRARY/src/bid128_compare.c         library_src_bid128_compare.c
ln -s LIBRARY/src/bid128_div.c             library_src_bid128_div.c
ln -s LIBRARY/src/bid128_fdimd.c           library_src_bid128_fdimd.c
ln -s LIBRARY/src/bid128_fma.c             library_src_bid128_fma.c
ln -s LIBRARY/src/bid128_fmod.c            library_src_bid128_fmod.c
ln -s LIBRARY/src/bid128_frexp.c           library_src_bid128_frexp.c
ln -s LIBRARY/src/bid128_ldexp.c           library_src_bid128_ldexp.c
ln -s LIBRARY/src/bid128_llrintd.c         library_src_bid128_llrintd.c
ln -s LIBRARY/src/bid128_logb.c            library_src_bid128_logb.c
ln -s LIBRARY/src/bid128_logbd.c           library_src_bid128_logbd.c
ln -s LIBRARY/src/bid128_lrintd.c          library_src_bid128_lrintd.c
ln -s LIBRARY/src/bid128_lround.c          library_src_bid128_lround.c
ln -s LIBRARY/src/bid128_minmax.c          library_src_bid128_minmax.c
ln -s LIBRARY/src/bid128_modf.c            library_src_bid128_modf.c
ln -s LIBRARY/src/bid128_mul.c             library_src_bid128_mul.c
ln -s LIBRARY/src/bid128_nearbyintd.c      library_src_bid128_nearbyintd.c
ln -s LIBRARY/src/bid128_next.c            library_src_bid128_next.c
ln -s LIBRARY/src/bid128_nexttowardd.c     library_src_bid128_nexttowardd.c
ln -s LIBRARY/src/bid128_noncomp.c         library_src_bid128_noncomp.c
ln -s LIBRARY/src/bid128_quantexpd.c       library_src_bid128_quantexpd.c
ln -s LIBRARY/src/bid128_quantize.c        library_src_bid128_quantize.c
ln -s LIBRARY/src/bid128_rem.c             library_src_bid128_rem.c
ln -s LIBRARY/src/bid128_round_integral.c  library_src_bid128_round_integral.c
ln -s LIBRARY/src/bid128_scalb.c           library_src_bid128_scalb.c
ln -s LIBRARY/src/bid128_scalbl.c          library_src_bid128_scalbl.c
ln -s LIBRARY/src/bid128_sqrt.c            library_src_bid128_sqrt.c
ln -s LIBRARY/src/bid128_string.c          library_src_bid128_string.c
ln -s LIBRARY/src/bid128_to_int16.c        library_src_bid128_to_int16.c
ln -s LIBRARY/src/bid128_to_int32.c        library_src_bid128_to_int32.c
ln -s LIBRARY/src/bid128_to_int64.c        library_src_bid128_to_int64.c
ln -s LIBRARY/src/bid128_to_int8.c         library_src_bid128_to_int8.c
ln -s LIBRARY/src/bid128_to_uint16.c       library_src_bid128_to_uint16.c
ln -s LIBRARY/src/bid128_to_uint32.c       library_src_bid128_to_uint32.c
ln -s LIBRARY/src/bid128_to_uint64.c       library_src_bid128_to_uint64.c
ln -s LIBRARY/src/bid128_to_uint8.c        library_src_bid128_to_uint8.c
ln -s LIBRARY/src/strtod32.c               library_src_strtod32.c
ln -s LIBRARY/src/strtod64.c               library_src_strtod64.c
ln -s LIBRARY/src/strtod128.c              library_src_strtod128.c
ln -s LIBRARY/src/wcstod32.c               library_src_wcstod32.c
ln -s LIBRARY/src/wcstod64.c               library_src_wcstod64.c
ln -s LIBRARY/src/wcstod128.c              library_src_wcstod128.c
ln -s LIBRARY/src/bid32_acos.c             library_src_bid32_acos.c
ln -s LIBRARY/src/bid32_acosh.c            library_src_bid32_acosh.c
ln -s LIBRARY/src/bid32_asin.c             library_src_bid32_asin.c
ln -s LIBRARY/src/bid32_asinh.c            library_src_bid32_asinh.c
ln -s LIBRARY/src/bid32_atan.c             library_src_bid32_atan.c
ln -s LIBRARY/src/bid32_atan2.c            library_src_bid32_atan2.c
ln -s LIBRARY/src/bid32_atanh.c            library_src_bid32_atanh.c
ln -s LIBRARY/src/bid32_cbrt.c             library_src_bid32_cbrt.c
ln -s LIBRARY/src/bid32_cos.c              library_src_bid32_cos.c
ln -s LIBRARY/src/bid32_cosh.c             library_src_bid32_cosh.c
ln -s LIBRARY/src/bid32_erf.c              library_src_bid32_erf.c
ln -s LIBRARY/src/bid32_erfc.c             library_src_bid32_erfc.c
ln -s LIBRARY/src/bid32_exp.c              library_src_bid32_exp.c
ln -s LIBRARY/src/bid32_exp10.c            library_src_bid32_exp10.c
ln -s LIBRARY/src/bid32_exp2.c             library_src_bid32_exp2.c
ln -s LIBRARY/src/bid32_expm1.c            library_src_bid32_expm1.c
ln -s LIBRARY/src/bid32_hypot.c            library_src_bid32_hypot.c
ln -s LIBRARY/src/bid32_lgamma.c           library_src_bid32_lgamma.c
ln -s LIBRARY/src/bid32_log.c              library_src_bid32_log.c
ln -s LIBRARY/src/bid32_log10.c            library_src_bid32_log10.c
ln -s LIBRARY/src/bid32_log1p.c            library_src_bid32_log1p.c
ln -s LIBRARY/src/bid32_log2.c             library_src_bid32_log2.c
ln -s LIBRARY/src/bid32_pow.c              library_src_bid32_pow.c
ln -s LIBRARY/src/bid32_sin.c              library_src_bid32_sin.c
ln -s LIBRARY/src/bid32_sinh.c             library_src_bid32_sinh.c
ln -s LIBRARY/src/bid32_tan.c              library_src_bid32_tan.c
ln -s LIBRARY/src/bid32_tanh.c             library_src_bid32_tanh.c
ln -s LIBRARY/src/bid32_tgamma.c           library_src_bid32_tgamma.c
ln -s LIBRARY/src/bid32_sub.c              library_src_bid32_sub.c
ln -s LIBRARY/src/bid32_to_bid128.c        library_src_bid32_to_bid128.c
ln -s LIBRARY/src/bid32_to_bid64.c         library_src_bid32_to_bid64.c
ln -s LIBRARY/src/bid64_to_bid128.c        library_src_bid64_to_bid128.c
ln -s LIBRARY/src/bid128_2_str_tables.c    library_src_bid128_2_str_tables.c
ln -s LIBRARY/src/bid_binarydecimal.c      library_src_bid_binarydecimal.c
ln -s LIBRARY/src/bid_convert_data.c       library_src_bid_convert_data.c
ln -s LIBRARY/src/bid_decimal_data.c       library_src_bid_decimal_data.c
ln -s LIBRARY/src/bid_decimal_globals.c    library_src_bid_decimal_globals.c
ln -s LIBRARY/src/bid_dpd.c                library_src_bid_dpd.c
ln -s LIBRARY/src/bid_feclearexcept.c      library_src_bid_feclearexcept.c
ln -s LIBRARY/src/bid_fegetexceptflag.c    library_src_bid_fegetexceptflag.c
ln -s LIBRARY/src/bid_feraiseexcept.c      library_src_bid_feraiseexcept.c
ln -s LIBRARY/src/bid_fesetexceptflag.c    library_src_bid_fesetexceptflag.c
ln -s LIBRARY/src/bid_fetestexcept.c       library_src_bid_fetestexcept.c
ln -s LIBRARY/src/bid_flag_operations.c    library_src_bid_flag_operations.c
ln -s LIBRARY/src/bid_from_int.c           library_src_bid_from_int.c
ln -s LIBRARY/src/bid_round.c              library_src_bid_round.c
ln -s LIBRARY/src/bid128.c                 library_src_bid128.c

echo "Linking float128 contents..."
ln -s LIBRARY/float128/dpml_ux_bid.c       library_float128_dpml_ux_bid.c
ln -s LIBRARY/float128/dpml_ux_bessel.c    library_float128_dpml_ux_bessel.c
ln -s LIBRARY/float128/dpml_ux_cbrt.c      library_float128_dpml_ux_cbrt.c
ln -s LIBRARY/float128/dpml_ux_erf.c       library_float128_dpml_ux_erf.c
ln -s LIBRARY/float128/dpml_ux_exp.c       library_float128_dpml_ux_exp.c
ln -s LIBRARY/float128/dpml_ux_int.c       library_float128_dpml_ux_int.c
ln -s LIBRARY/float128/dpml_ux_inv_hyper.c library_float128_dpml_ux_inv_hyper.c
ln -s LIBRARY/float128/dpml_ux_inv_trig.c  library_float128_dpml_ux_inf_trig.c
ln -s LIBRARY/float128/dpml_ux_lgamma.c    library_float128_dpml_ux_lgamma.c
ln -s LIBRARY/float128/dpml_ux_log.c       library_float128_dpml_ux_log.c
ln -s LIBRARY/float128/dpml_ux_mod.c       library_float128_dpml_ux_mod.c
ln -s LIBRARY/float128/dpml_ux_powi.c      library_float128_dpml_ux_powi.c
ln -s LIBRARY/float128/dpml_ux_pow.c       library_float128_dpml_ux_pow.c
ln -s LIBRARY/float128/dpml_ux_sqrt.c      library_float128_dpml_ux_sqrt.c
ln -s LIBRARY/float128/dpml_ux_trig.c      library_float128_dpml_ux_trig.c
ln -s LIBRARY/float128/dpml_ux_ops.c       library_float128_dpml_ux_ops.c
ln -s LIBRARY/float128/dpml_ux_ops_64.c    library_float128_dpml_ux_ops_64.c
ln -s LIBRARY/float128/dpml_four_over_pi.c library_float128_dpml_four_over_pi.c
ln -s LIBRARY/float128/dpml_exception.c    library_float128_dpml_exception.c
ln -s LIBRARY/float128/sqrt_tab_t.c        library_float128_sqrt_tab_t.c

echo "Linking headers..."
ln -s LIBRARY/src/bid_functions.h bid_functions.h
ln -s LIBRARY/src/bid_conf.h bid_conf.h
