// bdem_configschema.cpp   -*-C++-*-   GENERATED FILE -- DO NOT EDIT

#include <bdes_ident.h>
BDES_IDENT_RCSID(bdem_configschema_cpp,"$Id$ $CSID$")

#include <bdem_configschema.h>

namespace BloombergLP {

// CONSTANTS

const char bdem_ConfigSchema::TEXT[] =
"<?xml version='1.0' encoding='UTF-8'?>\n"
"<xs:schema xmlns:xs=\"http://www.w3.org/2001/XMLSchema\"\n"
"        xmlns:bdem='http://bloomberg.com/schemas/bdem'\n"
"        bdem:package='bdem'\n"
"        elementFormDefault='qualified'>\n"
"\n"
"  <!-- WARNING: Use 'bdem_generateoptions.pl', rather than 'bas_codegen.pl'\n"
"       to regenerate these components and automatically convert from\n"
"       package namespaces to package prefix naming style.             -->\n"
"\n"
"  <xs:annotation>\n"
"    <xs:documentation>\n"
"       Schema of options records for bdem codecs\n"
"    </xs:documentation>\n"
"  </xs:annotation>\n"
"\n"
"  <xs:complexType name='BerDecoderOptions'>\n"
"    <xs:annotation>\n"
"      <xs:documentation>BER decoding options</xs:documentation>\n"
"    </xs:annotation>\n"
"    <xs:sequence>\n"
"      <xs:element name='MaxDepth' type='xs:int'\n"
"                  minOccurs='0' maxOccurs='1'\n"
"                  default='32'\n"
"                  bdem:allowsDirectManipulation='0'>\n"
"        <xs:annotation>\n"
"          <xs:documentation>maximum recursion depth</xs:documentation>\n"
"        </xs:annotation>\n"
"      </xs:element>\n"
"      <xs:element name='SkipUnknownElements' type='xs:boolean'\n"
"                   minOccurs='0' maxOccurs='1'\n"
"                   default='true'\n"
"                   bdem:allowsDirectManipulation='0'>\n"
"        <xs:annotation>\n"
"          <xs:documentation>Option to skip unknown elements</xs:documentation>\n"
"        </xs:annotation>\n"
"      </xs:element>\n"
"      <xs:element name='TraceLevel' type='xs:int'\n"
"                  minOccurs='0' maxOccurs='1'\n"
"                  default='0'\n"
"                  bdem:allowsDirectManipulation='0'>\n"
"        <xs:annotation>\n"
"          <xs:documentation>trace (verbosity) level</xs:documentation>\n"
"        </xs:annotation>\n"
"      </xs:element>\n"
"      <xs:element name='MaxSequenceSize' type='xs:int'\n"
"                  minOccurs='0' maxOccurs='1'\n"
"                  default='8388608'\n"
"                  bdem:allowsDirectManipulation='0'>\n"
"        <xs:annotation>\n"
"          <xs:documentation>maximum sequence size</xs:documentation>\n"
"        </xs:annotation>\n"
"      </xs:element>\n"
"    </xs:sequence>\n"
"  </xs:complexType>\n"
"\n"
"  <xs:complexType name='BerEncoderOptions'>\n"
"    <xs:annotation>\n"
"      <xs:documentation>BER encoding options</xs:documentation>\n"
"    </xs:annotation>\n"
"    <xs:sequence>\n"
"      <xs:element name='TraceLevel' type='xs:int'\n"
"                  minOccurs='0' maxOccurs='1'\n"
"                  default='0'\n"
"                  bdem:allowsDirectManipulation='0'>\n"
"        <xs:annotation>\n"
"          <xs:documentation>trace (verbosity) level</xs:documentation>\n"
"        </xs:annotation>\n"
"      </xs:element>\n"
"      <xs:element name='BdeVersionConformance' type='xs:int' default='10500'>\n"
"        <xs:annotation>\n"
"          <xs:documentation>\n"
"            The largest BDE version that can be assumed of the corresponding\n"
"            decoder for the encoded message, expressed as 10000*majorVersion +\n"
"            100*minorVersion + patchVersion (e.g. 1.5.0 is expressed as 10500).\n"
"\n"
"            Ideally, the BER encoder should be permitted to generate any BER\n"
"            that conforms to X.690 (Basic Encoding Rules) and X.694 (mapping\n"
"            of XSD to ASN.1).  In practice, however, certain unimplemented\n"
"            features and missunderstandings of these standards have resulted\n"
"            in a decoder that cannot accept the full range of legal inputs.\n"
"            Even when the encoder and decoder are both upgraded to a richer\n"
"            subset of BER, the program receiving the encoded values may not\n"
"            have been recompiled with the latest version and, thus restricting\n"
"            the encoder to emit BER that can be understood by the decoder at\n"
"            the other end of the wire.  If it is that the receiver has a more\n"
"            modern decoder, set this variable to a larger value to allow the\n"
"            encoder to produce BER that is richer and more standards\n"
"            conformant.  The default should be increased only when old copies\n"
"            of the decoder are completely out of circulation.\n"
"          </xs:documentation>\n"
"        </xs:annotation>\n"
"      </xs:element>\n"
"      <xs:element name='EncodeEmptyArrays' type='xs:boolean' default='true'\n"
"                  bdem:allowsDirectManipulation='0'>\n"
"        <xs:annotation>\n"
"          <xs:documentation>\n"
"            This option allows users to control if empty arrays are encoded.\n"
"            By default empty arrays are encoded as not encoding empty arrays is\n"
"            non-compliant with the BER encoding specification.\n"
"          </xs:documentation>\n"
"        </xs:annotation>\n"
"      </xs:element>\n"
"    </xs:sequence>\n"
"  </xs:complexType>\n"
"\n"
"  <xs:complexType name='BdemDecoderOptions'>\n"
"    <xs:annotation>\n"
"      <xs:documentation>BDEM decoding options</xs:documentation>\n"
"    </xs:annotation>\n"
"    <xs:sequence>\n"
"      <xs:element name='BdemVersion' type='xs:int'\n"
"                  minOccurs='0' maxOccurs='1'\n"
"                  default='2'\n"
"                  bdem:allowsDirectManipulation='0'>\n"
"        <xs:annotation>\n"
"          <xs:documentation>BDEM version</xs:documentation>\n"
"        </xs:annotation>\n"
"      </xs:element>\n"
"      <xs:element name='MaxDepth' type='xs:int'\n"
"                  minOccurs='0' maxOccurs='1'\n"
"                  default='32'\n"
"                  bdem:allowsDirectManipulation='0'>\n"
"        <xs:annotation>\n"
"          <xs:documentation>maximum recursion depth</xs:documentation>\n"
"        </xs:annotation>\n"
"      </xs:element>\n"
"    </xs:sequence>\n"
"  </xs:complexType>\n"
"\n"
"  <xs:complexType name='BdemEncoderOptions'>\n"
"    <xs:annotation>\n"
"      <xs:documentation>BDEM encoding options</xs:documentation>\n"
"    </xs:annotation>\n"
"    <xs:sequence>\n"
"      <xs:element name='BdemVersion' type='xs:int'\n"
"                  minOccurs='0' maxOccurs='1'\n"
"                  default='2'\n"
"                  bdem:allowsDirectManipulation='0'>\n"
"        <xs:annotation>\n"
"          <xs:documentation>BDEM version</xs:documentation>\n"
"        </xs:annotation>\n"
"      </xs:element>\n"
"    </xs:sequence>\n"
"  </xs:complexType>\n"
"\n"
"</xs:schema>\n"
;

}  // close namespace BloombergLP

// GENERATED BY BLP_BAS_CODEGEN_3.6.9 Wed Feb  1 12:50:28 2012
// ----------------------------------------------------------------------------
// NOTICE:
//      Copyright (C) Bloomberg L.P., 2012
//      All Rights Reserved.
//      Property of Bloomberg L.P. (BLP)
//      This software is made available solely pursuant to the
//      terms of a BLP license agreement which governs its use.
// ------------------------------ END-OF-FILE ---------------------------------
