// balxml_encodingstyle.cpp   -*-C++-*-   GENERATED FILE -- DO NOT EDIT

#include <bsls_ident.h>
BSLS_IDENT_RCSID(balxml_encodingstyle_cpp,"$Id$ $CSID$ $CCId$")

#include <balxml_encodingstyle.h>

#include <bdlat_formattingmode.h>
#include <bdlat_valuetypefunctions.h>
#include <bdlb_chartype.h>
#include <bdlb_print.h>
#include <bdlb_printmethods.h>

#include <bsls_assert.h>

#include <bsl_iomanip.h>
#include <bsl_limits.h>
#include <bsl_ostream.h>

namespace BloombergLP {

                            // --------------------------                      
                            // class balxml::EncodingStyle
                            // --------------------------                      

// CONSTANTS

const char balxml::EncodingStyle::CLASS_NAME[] = "balxml::EncodingStyle";

const bdeat_EnumeratorInfo balxml::EncodingStyle::ENUMERATOR_INFO_ARRAY[] = {
    {
        balxml::EncodingStyle::BAEXML_COMPACT,
        "COMPACT",
        sizeof("COMPACT") - 1,
        ""
    },
    {
        balxml::EncodingStyle::BAEXML_PRETTY,
        "PRETTY",
        sizeof("PRETTY") - 1,
        ""
    }
};

namespace balxml {
// CLASS METHODS

int EncodingStyle::fromInt(EncodingStyle::Value *result, int number)
{
    switch (number) {
      case EncodingStyle::BAEXML_COMPACT:
      case EncodingStyle::BAEXML_PRETTY:
        *result = (EncodingStyle::Value)number;
        return 0;
      default:
        return -1;
    }
}

int EncodingStyle::fromString(EncodingStyle::Value *result,
                            const char         *string,
                            int                 stringLength)
{
    
    switch(stringLength) {
        case 6: {
            if ((string[0]|0x20)=='p'
             && (string[1]|0x20)=='r'
             && (string[2]|0x20)=='e'
             && (string[3]|0x20)=='t'
             && (string[4]|0x20)=='t'
             && (string[5]|0x20)=='y')
            {
                *result = EncodingStyle::BAEXML_PRETTY;
                return 0;
            }
        } break;
        case 7: {
            if ((string[0]|0x20)=='c'
             && (string[1]|0x20)=='o'
             && (string[2]|0x20)=='m'
             && (string[3]|0x20)=='p'
             && (string[4]|0x20)=='a'
             && (string[5]|0x20)=='c'
             && (string[6]|0x20)=='t')
            {
                *result = EncodingStyle::BAEXML_COMPACT;
                return 0;
            }
        } break;
        case 13: {
            if ((string[0]|0x20)=='b'
             && (string[1]|0x20)=='a'
             && (string[2]|0x20)=='e'
             && (string[3]|0x20)=='x'
             && (string[4]|0x20)=='m'
             && (string[5]|0x20)=='l'
             &&  string[6]      =='_'
             && (string[7]|0x20)=='p'
             && (string[8]|0x20)=='r'
             && (string[9]|0x20)=='e'
             && (string[10]|0x20)=='t'
             && (string[11]|0x20)=='t'
             && (string[12]|0x20)=='y')
            {
                *result = EncodingStyle::BAEXML_PRETTY;
                return 0;
            }
        } break;
        case 14: {
            if ((string[0]|0x20)=='b'
             && (string[1]|0x20)=='a'
             && (string[2]|0x20)=='e'
             && (string[3]|0x20)=='x'
             && (string[4]|0x20)=='m'
             && (string[5]|0x20)=='l'
             &&  string[6]      =='_'
             && (string[7]|0x20)=='c'
             && (string[8]|0x20)=='o'
             && (string[9]|0x20)=='m'
             && (string[10]|0x20)=='p'
             && (string[11]|0x20)=='a'
             && (string[12]|0x20)=='c'
             && (string[13]|0x20)=='t')
            {
                *result = EncodingStyle::BAEXML_COMPACT;
                return 0;
            }
        } break;
    }
    
    return -1;
}

const char *EncodingStyle::toString(EncodingStyle::Value value)
{
    switch (value) {
      case BAEXML_COMPACT: {
        return "COMPACT";
      } break;
      case BAEXML_PRETTY: {
        return "PRETTY";
      } break;
    }

    BSLS_ASSERT(!"invalid enumerator");
    return 0;
}
}  // close package namespace

}  // close namespace BloombergLP

// GENERATED BY BLP_BAS_CODEGEN_3.6.1 Mon Jan  3 12:39:26 2011
// ----------------------------------------------------------------------------
// NOTICE:
//      Copyright (C) Bloomberg L.P., 2011
//      All Rights Reserved.
//      Property of Bloomberg L.P. (BLP)
//      This software is made available solely pursuant to the
//      terms of a BLP license agreement which governs its use.
// ------------------------------ END-OF-FILE ---------------------------------
