#!/bin/bash

# ----------------------------------------------------------------------------
# Copyright (C) 2013 Bloomberg L.P.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
# ----------------------------------------------------------------------------

if [ "$1" = "init" ]
then
    rm -rf coverage
    mkdir -p coverage
    echo > coverage.mk
    echo "init-info =" >> coverage.mk
    echo "gather-info =" >> coverage.mk
    echo "aggregate-info =" >> coverage.mk
    echo "coverage-info = " >> coverage.mk
    for compdir in `find -name \*.gcno -printf "%h\n" | sort -u`
    do
	comp=${compdir##*obj.target/}
	comp=${comp%%/*}
	# skip some targets that do not generate coverage data
	if [ $comp = bsldoc ]; then continue; fi
	if [ $comp = bslmf ]; then continue; fi
	if [ $comp = bslscm ]; then continue; fi
	echo "init-info += coverage/${comp}-initial.info" >> coverage.mk
	echo "coverage/${comp}-initial.info: ${compdir}/*.gcno" >> coverage.mk
	echo -e "\ttools/lcov/bin/lcov --base-directory build --output-file coverage/${comp}-initial.info --capture --initial --directory ${compdir}" >> coverage.mk
	echo >> coverage.mk

	echo "gather-info += coverage/${comp}-test.info" >> coverage.mk
	echo "coverage/${comp}-test.info: ${compdir}/*.gcda" >> coverage.mk
	echo -e "\ttools/lcov/bin/lcov --base-directory build --output-file coverage/${comp}-test.info --capture --directory ${compdir}" >> coverage.mk
	echo >> coverage.mk

	echo "aggregate-info += coverage/${comp}-final.info" >> coverage.mk
	echo "coverage/${comp}-final.info: coverage/${comp}-initial.info coverage/${comp}-test.info" >> coverage.mk
	echo -e "\ttools/lcov/bin/lcov --add-tracefile coverage/${comp}-initial.info --add-tracefile coverage/${comp}-test.info --output-file coverage/${comp}-final.info" >> coverage.mk
	echo >> coverage.mk

	echo "coverage-info += coverage/${comp}-coverage.xml" >> coverage.mk
	echo "coverage/${comp}-coverage.xml: coverage/${comp}-final.info" >> coverage.mk
	echo -e "\tpython tools/lcov_cobertura/lcov_cobertura.py -o coverage/${comp}-coverage.xml --excludes \".*.usr.include.*\" --excludes \"build\" --demangle-cpp coverage/${comp}-final.info" >> coverage.mk
	echo -e "\tsed -i -e \"s/groups\\.bsl\\.//\" coverage/${comp}-coverage.xml" >> coverage.mk
	echo >> coverage.mk
    done
    echo ".PHONY: init gather aggregate coverage" >> coverage.mk
    echo "init: \$(init-info)" >> coverage.mk
    echo "gather: \$(gather-info)" >> coverage.mk
    echo "aggregate: \$(aggregate-info)" >> coverage.mk
    echo "coverage: \$(coverage-info)" >> coverage.mk
    make -f coverage.mk $@
fi

if [ "$1" = "gather" ]
then
    make -f coverage.mk $@
fi

if [ "$1" = "aggregate" ]
then
    make -f coverage.mk $@
fi

if [ "$1" = "coverage" ]
then
    make -f coverage.mk $@
fi
